import type { Essay } from "./types";

export const MANUAL_A: Essay[] = [
{
  slug: "focus-is-a-market-discipline",
  n: 1,
  title: "Focus is a market discipline, not a product count",
  deck: "The most repeated advice in startups is right about the disease and wrong about the cure.",
  reading: "6 min",
  tags: ["Strategy", "First principles"],
  thesis: "Focus means knowing exactly whose problem you own. It has never meant owning only one of their problems.",
  body: [
    { t: "p", x: "Every investor, every advisor, every blog post tells you the same thing: focus. Do one thing. Do it better than anyone. Earn the right to do the second thing. It is the most repeated sentence in this industry and it is repeated because it is usually true. Most startups do not die from competition. They die from dilution — three half-built things, none of which anyone would miss." },
    { t: "p", x: "So I want to be careful here, because I am about to disagree with it and I do not want to be misread as saying discipline does not matter. Discipline is the whole game. I just think the industry collapsed two different disciplines into one word and then handed everyone the wrong one." },
    { t: "h", x: "The two focuses" },
    { t: "p", x: "There is focus on a customer, and there is focus on a product. They are not the same commitment and they do not trade off the same way." },
    { t: "cmp", a: { h: "Customer focus", x: "You know exactly who you serve, what they do all day, what they will pay for, and — critically — who you refuse to serve. This is non-negotiable. Losing it is fatal." }, b: { h: "Product focus", x: "You ship one thing. This is a tactic. It is the right tactic under specific conditions, and those conditions are not universal." } },
    { t: "p", x: "We are close to religious about the first one. Our customer is a company — specifically the administrative machinery of a company between roughly fifty and five thousand people. Not consumers. Not the enterprise with a bespoke everything. Not the two-person LLC. We have turned down whole markets that would have been real revenue because they were a different customer wearing similar clothes." },
    { t: "p", x: "We are almost entirely undisciplined about the second one. We run more product lines than most companies our age run features. And I do not think that is a contradiction, because every one of those products is an answer to the same customer's day." },
    { t: "q", x: "Focus is a question about your customer, not your changelog." },
    { t: "h", x: "The test we actually run" },
    { t: "p", x: "When someone proposes a new product line, I do not ask whether we are ready. Readiness is unfalsifiable and everybody argues it forever. I ask four questions, and the answer has to be yes to all four." },
    { t: "ol", x: [
      "Does it read from the same record? If the product's core object is the employee — who they are, where they work, what they are paid, what they are allowed to touch — it is in scope. If it needs a different primary key, it is a different company.",
      "Does the same person buy it? Not the same logo. The same human being, with the same budget and the same signature.",
      "Does it ship through the same pipe? Same sales motion, same onboarding, same support surface. If we need a new go-to-market, we are not extending, we are starting over.",
      "Does it make the products we already have better? Not neutral. Better. If it is merely adjacent, it is a distraction with good manners.",
    ]},
    { t: "p", x: "Four yeses and it is not a new bet, it is more of the existing bet. Any no and the answer is no, no matter how large the market looks. We have killed proposals with enormous TAM on question two." },
    { t: "note", label: "Where this bites", x: "The fourth question is the one people try to skip. It is very easy to argue that a product is adjacent, uses the same data, sells to the same buyer, and simply sits beside the others without improving them. That is a portfolio, not a platform. Portfolios do not compound." },
    { t: "h", x: "Why the standard advice exists anyway" },
    { t: "p", x: "The advice is calibrated for the median company, and most companies should take it. If you do not yet have one product that works, adding a second is not strategy, it is avoidance — it feels like progress and it costs you the only thing that was going to save you." },
    { t: "p", x: "The advice is also self-protecting for the person giving it. Telling a founder to focus is never wrong in hindsight. If they focus and fail, they picked the wrong thing. If they broaden and fail, they were unfocused. Nobody has ever been blamed for saying focus." },
    { t: "p", x: "So take it seriously and then ask whether your situation is the one it was written for. Ours was not. Our customer had eleven vendors and a spreadsheet holding them together, and no amount of excellence in one of those eleven was going to fix the spreadsheet." },
    { t: "h", x: "What focus actually buys you, and what it costs" },
    { t: "p", x: "What you buy with single-product focus is sequencing clarity. Every argument about what to build next has an obvious tiebreaker, which is enormously valuable when you are twelve people and cannot afford a wrong quarter." },
    { t: "p", x: "What you pay is a ceiling. You have capped the company at the size of one product's market, and you have accepted that the seams between your product and the rest of your customer's stack are somebody else's problem forever. For a lot of companies that is a fine trade. For us the seams were the entire reason the customer was unhappy." },
    { t: "p", x: "If you take one thing: do not let anyone tell you focus is about doing less. Focus is about being unambiguous. We are the least ambiguous company I know about who we serve, and we will keep building until there is nothing left in their week that we have made them do twice." },
  ],
},
{
  slug: "the-employee-is-the-schema",
  n: 2,
  title: "The employee is the schema",
  deck: "Almost everything a company does administratively is a function of one record. Own that record and the integration problem stops existing.",
  reading: "7 min",
  tags: ["Architecture", "First principles"],
  thesis: "Every business system is downstream of the same object. Most vendors sync it. We store it. That single difference produces everything else.",
  body: [
    { t: "p", x: "Strip a company down to its administrative core and ask what it actually does. It hires people. It pays them. It gives them tools and takes the tools back. It buys things on their behalf. And it proves, to several governments, that it did all of that legally." },
    { t: "p", x: "Now look at what each of those depends on. Payroll needs to know who works here, in what country, at what rate, in what entity, since when. Benefits needs the same, plus dependents and jurisdiction. Device management needs identity, role, and employment status. App provisioning needs department, seniority, manager. Expense policy needs level and cost center. Every single one is a function of the same row." },
    { t: "q", x: "There is one object. Everything else is a view of it." },
    { t: "h", x: "The difference between storing and syncing" },
    { t: "p", x: "Here is the part that sounds obvious and is not. Everyone in this category has an employee table. That is not the insight. The insight is about who owns the truth." },
    { t: "cmp", a: { h: "The normal architecture", x: "One system is nominally the source of truth. The other twelve keep their own copy and reconcile on a schedule. Every copy is a foreign key with a sync job and a drift problem. Nobody is wrong, exactly — everyone is just a little bit stale in a different direction." }, b: { h: "Ours", x: "There are no copies. Payroll does not have an employee table. Devices does not have an employee table. They read the employee. When the record changes, they have already changed, because there was never a second thing to update." } },
    { t: "p", x: "That is the whole architectural bet, and it is why we could not have bought our way here. You cannot acquire five companies and merge their employee tables into one. You can put a single login in front of them and a shared nav bar on top, and customers will discover within a quarter that changing someone's department still takes five clicks in five places. The unification has to be structural or it is theatre." },
    { t: "h", x: "What the customer actually experiences" },
    { t: "p", x: "Nobody buys a data model. I have never once won a deal by explaining normalization. What they buy is a specific afternoon they no longer have." },
    { t: "p", x: "Someone moves from Hardware to Engineering. In the normal world that is: an HR ticket, a payroll cost-center change that someone remembers next month, a request to IT that revokes two licenses and grants four, a note to Finance to repoint the approval chain, and an org chart that stays wrong until the next all-hands. Five systems, four humans, about nine days, and a nonzero chance that in eight months an auditor finds that person still holds a license to software they have not opened since March." },
    { t: "p", x: "For us it is one dropdown. Everything I just listed is a consequence of the write, not a follow-up task. Forty seconds for the access changes, next payroll run for the cost center, instant for everything else." },
    { t: "note", label: "The demo that closes deals", x: "We do not demo features. We change one field and let the customer watch six systems move. Everyone in the room has personally lived the nine-day version. The pitch lands in about four seconds and there is nothing left to explain." },
    { t: "h", x: "The rule we will never relax" },
    { t: "p", x: "No product owns its own copy of the employee. Not for performance. Not for a deadline. Not for a customer who needs one weird field by Friday." },
    { t: "p", x: "This comes up constantly and the argument is always reasonable. A team is blocked on a platform change they need, the platform team is three weeks out, and the pragmatic move is to keep a local copy just for now, just this field, we will migrate it later. That local copy has never once been migrated later. It becomes a second source of truth, and now you have a reconciliation problem that will outlive everyone involved." },
    { t: "p", x: "So the answer is no, and the cost of that no is real: a team sits blocked, a date slips, and I personally take the escalation. That is the correct price. The alternative is that in four years we are the thing we were built to replace, except our seams are internal, which is worse, because at least the customer could see the old ones." },
    { t: "h", x: "What makes the record hard" },
    { t: "p", x: "The idea is simple. The implementation is where the years go, and it is worth being honest about why." },
    { t: "ul", x: [
      "Effective dating. Every fact about a person is true only within a window. What was their department on March 4th? Not what is it now — what was it then, because that is what the amended filing needs. Retrofitting this is close to impossible; it touches every read path you have ever written.",
      "Jurisdictional shape. An employee in Germany has fields a US employee does not, and required-ness varies by country, entity, and worker type. You either build a system where the shape of the record is data, or you build thirty forks.",
      "Worker types that blur. Contractor, EOR, part-time, intern, on leave. Each one changes which downstream systems apply. The elegant answer is not a boolean, it is a set of capabilities the record carries.",
      "Correction versus change. A promotion is a change: history is preserved. A typo in a start date is a correction: history was always wrong. These are different operations and treating them the same corrupts your audit trail.",
    ]},
    { t: "p", x: "None of that is glamorous. No customer has ever asked for effective dating by name. But every product we ship afterwards gets it for free, and a competitor who skipped it has to solve it separately, badly, in every product they own." },
    { t: "p", x: "That is the compounding. Not in the pitch deck sense. In the sense that the twelfth product costs a fraction of the second one, because eleven products' worth of hard problems were already solved centrally, once." },
  ],
},
{
  slug: "the-seams-are-the-product",
  n: 3,
  title: "The seams are the product",
  deck: "Best-of-breed assumes the value lives inside each tool. It doesn't. It lives in the space between them, which is exactly where nobody is accountable.",
  reading: "6 min",
  tags: ["Strategy", "Market"],
  thesis: "Point solutions cannot fix the seam, because the seam is not theirs. Integration is a treaty between parties with no shared incentive.",
  body: [
    { t: "p", x: "Go to any company with two hundred people and ask to meet whoever owns Operations. Then ask what they actually do all day. Some of it will be real operational work. A surprising amount of it will be moving the same information between systems that will not talk to each other." },
    { t: "q", x: "Every company past a hundred people employs somebody whose real job is to be middleware. They have a title. It is rarely the title they were hired for." },
    { t: "p", x: "This person exports a CSV from the applicant tracking system, cleans it, and imports it to payroll. They keep a spreadsheet reconciling license counts against the headcount report because the two disagree by eleven and nobody knows which is right. When someone leaves, they work a checklist of fourteen items across nine systems, and the checklist is in a doc, and the doc is out of date, and item nine was added after an audit finding." },
    { t: "p", x: "None of the vendors are at fault. Each tool, evaluated alone, is probably good. The applicant tracking system is a fine applicant tracking system. That is the trap." },
    { t: "h", x: "Why best-of-breed is a story point solutions have to tell" },
    { t: "p", x: "The argument goes: specialists beat generalists, buy the best of each category, connect them with integrations. It is intuitive and it is what you say if you sell one category and cannot build a second." },
    { t: "p", x: "The hidden assumption is that value is concentrated inside each tool and the connections are cheap plumbing. Invert it. Ask where the customer's pain actually is, hour by hour. It is almost never inside a tool. It is at the boundaries — the double entry, the drift, the reconciliation, the thing that silently did not sync, the offboarding that missed one system and became an incident." },
    { t: "cmp", a: { h: "What the category sells", x: "Depth. Our reporting module has forty-one dimensions. Our workflow builder has conditional branching. Look at how deep this one thing goes." }, b: { h: "What the customer feels", x: "I typed this person's name into six systems this week. Two of them disagree about their manager. I do not know which one payroll believes." } },
    { t: "h", x: "Integrations are a treaty, not a solution" },
    { t: "p", x: "The standard response is: we integrate. And they do. But think about what an integration actually is — an agreement between two companies with different roadmaps, different incentives, and no shared owner of the outcome." },
    { t: "ul", x: [
      "It moves fields, not meaning. It can copy a department string. It cannot know that a department change should also re-route approvals, because approvals live in a third system that is not party to this treaty.",
      "It is nobody's priority. When it breaks, each side is confident it is the other side's bug, and both are partly right. The customer files two tickets and gets two apologies.",
      "It degrades silently. A sync that stops working looks exactly like a period with no changes. You find out at an audit.",
      "It is one-way about history. Even when the current value syncs, the timeline usually does not — so the answer to 'what was true in March' exists in only one of the systems.",
    ]},
    { t: "p", x: "You cannot fix a seam from one side of it. That is not a criticism of any vendor. It is a structural fact about where the seam lives." },
    { t: "h", x: "The move" },
    { t: "p", x: "So the bet is not that we will build a better applicant tracking system than a company that only builds applicant tracking systems. Some quarters we will not, and I will say so." },
    { t: "p", x: "The bet is that a customer will trade some depth in each tool for the disappearance of the space between them, and that the trade gets more attractive every year, because the seam cost grows with headcount while the depth advantage stays roughly flat." },
    { t: "note", label: "The honest version", x: "There is a real customer for whom this trade is wrong. If your entire company lives inside one function all day — a two-hundred-person recruiting agency, say — the depth of that one tool matters more to you than every seam combined. We lose those deals, and we should. That is not a bug in the strategy, it is the strategy having edges." },
    { t: "p", x: "But most companies are not that. Most companies have eleven vendors and one exhausted person in Operations, and what they want is not a better eleventh vendor. It is to not have eleven." },
  ],
},
];
