import type { Essay } from "./types";

export const MANUAL_D: Essay[] = [
{
  slug: "the-graph-was-always-the-point",
  n: 11,
  title: "The graph was always the point. Agents just made it obvious.",
  deck: "For nine years, having everything in one place was a convenience argument. It has quietly become a capability argument — and the gap between those two is the whole next decade.",
  reading: "8 min",
  tags: ["AI", "Architecture", "Strategy"],
  thesis: "Everyone will have the same models. Not everyone will have the graph. An agent is a function of what it can see, what it is allowed to see, and what it is permitted to change.",
  body: [
    { t: "p", x: "I want to be careful with this one, because every company in software is currently explaining why their existing strategy was secretly an AI strategy all along. Most of those explanations are retrofitted. So let me state the claim narrowly enough to be wrong." },
    { t: "p", x: "The claim is not that we saw agents coming. We did not. The claim is that the specific thing we spent nine years building — a live, permission-aware, effective-dated model of a company and everything it does administratively — turns out to be the scarce input for a category of software we were not designing for." },
    { t: "h", x: "Assistants answer. Agents act." },
    { t: "p", x: "The distinction gets blurred in marketing and it is the only thing that matters technically. An assistant reads and summarises. An agent changes something. The gap between them is entirely about what the system underneath can be trusted to do." },
    { t: "p", x: "Building an assistant over business data is now close to trivial. Any vendor can index their own corpus and put a chat box on it, and by the end of any given quarter most of them will have. That is not a differentiated capability and it will not be one." },
    { t: "p", x: "Building an agent that can move someone from Hardware to Engineering is a different problem entirely, and it is not a model problem. It is a question of whether anything in your system can absorb the consequences." },
    { t: "q", x: "Everyone will have the same models. Not everyone will have the graph." },
    { t: "h", x: "What an agent actually needs" },
    { t: "p", x: "Four things, and only the first one gets discussed." },
    { t: "ol", x: [
      "A live model of what is true right now. Not a snapshot, not a nightly export, not an embedding computed on Tuesday. If the agent is going to act, it has to be reading the same object the action will be applied to — otherwise it is reasoning about a company that no longer exists.",
      "Permissions enforced at the read, not at the prompt. This is the part almost nobody has solved and almost everybody demos past. The question is never 'can this user see this document'. It is 'can this user see this field, of this person, as of this date, given their span of control and their entity'. That is not metadata you can attach to a chunk. It is a query, and it has to run on the way in.",
      "The ability to write with the same machinery a human write goes through. Approval chain, effective dating, actor attribution, audit trail. An agent that writes through a side door has just created a class of change that nobody can reconstruct later, which in a regulated category is not a feature, it is a liability with a latency of about three years.",
      "Reversibility, classified honestly. Revoking someone's access is annoying and reversible. Running payroll is not. An agent that treats those two the same way is not a productivity tool, it is a hazard, and the classification has to live in the system rather than in a prompt.",
    ]},
    { t: "h", x: "The seam problem gets worse, not better" },
    { t: "p", x: "Here is the part I did not expect, and it is the strongest version of the argument." },
    { t: "p", x: "When two systems disagree about who someone's manager is, a human notices. Not immediately, but eventually — an approval routes to the wrong person, somebody says 'why am I getting this', and the discrepancy surfaces through friction. The friction is annoying and it is also the error-correction mechanism." },
    { t: "p", x: "An agent does not notice. It reads one of the two systems, gets an answer, and acts on it with complete confidence. There is no puzzled human in the loop to generate the friction. The inconsistency that used to produce a mildly irritating email now produces a confidently wrong action, at machine speed, at volume." },
    { t: "cmp", a: { h: "Seams with humans in the loop", x: "Drift produces friction. Friction produces questions. Questions produce corrections. The system is slow and mildly infuriating, and it self-heals because a person is confused often enough to check." }, b: { h: "Seams with agents in the loop", x: "Drift produces confident action. Nobody is confused, because nobody is reading it. The system is fast and self-consistent and wrong, and it does not self-heal — it compounds until something forces an accounting." } },
    { t: "p", x: "So the integration layer that was a productivity tax for ten years becomes a correctness problem the moment you put an agent on top of it. Every treaty between two vendors that mostly works is now a place where an autonomous system will act on stale data without hesitating." },
    { t: "h", x: "Why a point solution cannot follow us here" },
    { t: "p", x: "This is the part where I think the structural advantage is genuinely larger than it was, and I want to lay it out rather than assert it." },
    { t: "p", x: "Suppose a best-in-class HR vendor ships an excellent agent. A customer asks it to move someone between departments. To actually complete that action it must: update its own record, then call the payroll vendor to reclassify the cost center, the identity vendor to change group membership, the device vendor to update conditional access, the expense vendor to repoint the approval chain, and the learning vendor to reassign training." },
    { t: "p", x: "Six external calls, six auth models, six failure modes, no shared transaction, and no way to roll back call four when call five fails. That is not an agent. That is a distributed systems problem with a chat interface on it, and the thing that makes it hard is not intelligence." },
    { t: "p", x: "For us that action is a write, followed by reads. Not because we are better engineers. Because there is nothing to coordinate." },
    { t: "note", label: "The decision this forced", x: "Several teams proposed embedding employee and policy data into per-product vector stores to power assistants. Each proposal was individually reasonable. Each created a second copy of the record, with different staleness, and — worse — one where the permission boundary had been flattened into the index at write time. We said no. It is the oldest rule in the company wearing new clothes, and this is the version of it where getting it wrong is most expensive." },
    { t: "h", x: "What this costs us, right now" },
    { t: "p", x: "Being honest about the trade, because there is one and we are currently paying it." },
    { t: "ul", x: [
      "We are slower. A permission-checked query against a live graph is more expensive than a similarity search over a pre-computed index. We lose demos on responsiveness to products that will happily embed everything and answer in 200 milliseconds.",
      "We ship fewer assistant features per quarter than competitors who treat this as a retrieval problem. That gap is visible in comparison grids and it is going to be visible for a while.",
      "The hard version is genuinely hard. Permission-scoped, effective-dated retrieval is an open problem in our system and I would not claim we have solved it. It is being worked. It may take another year.",
    ]},
    { t: "p", x: "I think that trade is obviously correct and I also think it will look wrong for four to six quarters, which is exactly the shape of every other decision in this manual." },
    { t: "h", x: "The risk I actually worry about" },
    { t: "p", x: "Not competition. Data quality." },
    { t: "p", x: "When the record is read by humans, a stale field is an annoyance. Somebody notices, somebody fixes it, life continues. When the record is the substrate for autonomous action, a stale field is an incident with a blast radius, and the radius scales with how much we have automated." },
    { t: "p", x: "So the thing that used to be an operations concern — is this data right — becomes a first-order product concern with existential edges. We have started treating record accuracy the way we treat uptime: measured, alerted, owned by a named team, with a number I look at weekly. That is new, it is a direct consequence of agents, and it is the part of this transition I would tell another founder to start on first." },
    { t: "p", x: "The compounding argument has not changed. It has just stopped being about saving people time and started being about whether autonomous systems can be trusted to touch your company at all. Same graph. Much higher stakes." },
  ],
},
{
  slug: "where-we-lose-on-purpose",
  n: 12,
  title: "Where we lose, on purpose",
  deck: "We lose four kinds of deal. Three of them are the strategy working correctly. The fourth is the one worth being upset about.",
  reading: "6 min",
  tags: ["Go-to-market", "Strategy", "Hard parts"],
  thesis: "A strategy without a loss column is a pitch. The useful question is never whether you lose deals — it is whether the ones you lose are the ones you chose to.",
  body: [
    { t: "p", x: "Every company has a competitive slide where they win every column. I have never found one useful, including ours. So here is the version I actually use internally, which is organised around losing." },
    { t: "h", x: "The four things we run into" },
    { t: "p", x: "Not companies — shapes. Naming individual competitors makes people emotional and stops them thinking structurally." },
    { t: "ul", x: [
      "The point specialist. Deep in one category, genuinely excellent at it, usually beloved by the team that lives in it all day. Their entire argument is depth, and in their category the argument is often correct.",
      "The suite assembled by acquisition. Broad surface, one login, a shared nav bar, and five employee tables underneath. Demos extremely well. Falls apart the first time a customer changes someone's department and watches it not propagate.",
      "The legacy enterprise platform. Genuinely unified, genuinely comprehensive, built for a company an order of magnitude larger, and priced and implemented accordingly. Wins on the top end for real reasons.",
      "The services-led implementer. Not really a software competitor. They sell people who will make whatever the customer already owns work, which is a completely rational purchase and one we are structurally unable to match.",
    ]},
    { t: "h", x: "What actually happens in the room" },
    { t: "cmp", a: { h: "Against the point specialist", x: "We lose on depth in their category and win on everything around it. The deal turns on one question: does the team that lives in that tool all day get to decide, or does the person who owns the seams? If it is the former, we lose, and we should." }, b: { h: "Against the assembled suite", x: "We win by asking for a live demo of a department change. That is the entire competitive strategy and it does not require us to say a word about anyone else. Either it propagates or it does not." } },
    { t: "cmp", a: { h: "Against the legacy platform", x: "We win below their comfortable floor and lose above it. Their implementation cost is a fixed overhead that a mid-market company cannot absorb — which is a moat in both directions." }, b: { h: "Against services", x: "We win when the customer wants the problem to stop existing. We lose when they want their current stack preserved, and no amount of product quality changes that, because the thing being purchased is not product." } },
    { t: "h", x: "Three losses that are the strategy working" },
    { t: "ol", x: [
      "The single-function company. Two hundred people who all do one thing. Their entire day is inside one category, so depth in that category is worth more to them than every seam combined. They should buy the specialist. We bid anyway, sometimes, and we should stop.",
      "The customer who needs the core record configured for them. Big contract, real revenue, and their requirement is a per-customer branch in the employee model. We have declined eight-figure opportunities on this and the sales organisation did not enjoy it. It is a fork with a purchase order attached.",
      "The different buyer wearing similar clothes. Adjacent market, similar-sounding needs, different signature and different budget line. Fails question two of the four-question test. The TAM slide always looks wonderful and the answer is still no.",
    ]},
    { t: "p", x: "Each of those is a designed edge. A strategy that has no edges is not a strategy, it is an ambition." },
    { t: "h", x: "The fourth loss, which is not fine" },
    { t: "p", x: "We lose deals where the customer genuinely lives in one of our categories daily, we are meaningfully thinner than the specialist there, and the seam argument does not compensate — not because they do not understand it, but because it is honestly worth less to them than the depth is." },
    { t: "p", x: "The failure mode is responding to this by explaining the seam better. It is not a comprehension problem. They did the arithmetic and got a different answer, and their answer is right for their company." },
    { t: "q", x: "When you lose to depth, the answer is depth. Not a better explanation of why depth should not have mattered." },
    { t: "p", x: "So this one goes on the product roadmap, not into sales enablement. The test is specific: is there a category where our customers spend more than about two hours a day, and where we are more than one generation behind? That is a small list and it is the list that matters." },
    { t: "note", label: "The uncomfortable version", x: "There is a scenario where this loss compounds instead of staying contained — where good-enough-everywhere becomes a ceiling rather than a floor, and we discover the market will pay for depth in more categories than we assumed. I do not think that is happening. I do think it is the most plausible way this strategy is wrong, and it is worth more of my attention than any competitor's roadmap." },
  ],
},
];
