import type { Essay } from "./types";

export const MANUAL_B: Essay[] = [
{
  slug: "the-j-curve",
  n: 4,
  title: "The J-curve you have to survive",
  deck: "For about three years, a compound startup and an unfocused company are indistinguishable from the outside. That is the actual risk — not competition.",
  reading: "6 min",
  tags: ["Strategy", "Capital", "Hard parts"],
  thesis: "You pay for the platform years before you can monetize it. Everyone around you will read that spending as a lack of discipline, and some of the time they will be right.",
  body: [
    { t: "p", x: "I want to spend a whole section on the part that is genuinely bad, because the strategy gets talked about as though the only hard bit is having the courage to be contrarian. It is not. The hard bit is arithmetic, and it arrives on a schedule." },
    { t: "p", x: "For the first few years you are building a platform whose entire value is that it makes products five through twenty cheap. But you only have products one and two. So you are carrying the cost of leverage you cannot yet use." },
    { t: "h", x: "What this looks like on the numbers" },
    { t: "ul", x: [
      "Burn is high relative to revenue, and the reason is invisible. A meaningful share of engineering is building things no customer will ever name: the permissions model, effective dating, the workflow engine, the country abstraction.",
      "Each individual product looks thinner than its focused competitor, because it is. You are spending on shared depth, they are spending on visible depth.",
      "Time to first revenue on product two is long, and the argument that product three will be faster is, at that moment, a claim rather than evidence.",
      "Your revenue per customer looks ordinary, because the multi-product expansion that makes the model work has not had time to happen yet.",
    ]},
    { t: "p", x: "Every one of those is also what a company with no discipline looks like. That is the problem. There is no metric in year two that separates the two cases." },
    { t: "q", x: "The strategy and the failure mode are visually identical from outside. They are not identical inside the data — but only if you instrumented for it early." },
    { t: "h", x: "What you owe the people who have to live in it" },
    { t: "p", x: "Investors will pattern-match. That is manageable; you self-select for the ones who can hold a model in their head. The harder audience is internal, and they deserve better than conviction." },
    { t: "p", x: "Your best engineer will ask why we are starting a fourth product when the second is not done. That is not disloyalty, it is the correct question, and the answer 'trust me' is a resignation letter with a delay fuse." },
    { t: "p", x: "So we instrument the thesis and we show the instrument. Specifically: time-to-first-customer for each new product line, plotted in order. If that curve is not falling, the platform is not working and I want to know before anyone else does. It is the single number that tells you whether you are compounding or just spending." },
    { t: "note", label: "The number we watch hardest", x: "Product one took nineteen months to first paying customer. Product four took seven. Product nine took eleven weeks. That declining curve is the entire argument, and it is the only version of the argument I trust, because it cannot be told as a story." },
    { t: "h", x: "How you actually get through it" },
    { t: "ol", x: [
      "Raise more than feels comfortable, earlier than feels necessary, and be explicit about what it funds. This strategy is capital-intensive by construction. Running it on a normal balance sheet is not brave, it is a plan to die at the bottom of the curve.",
      "Sequence so that something works early. The platform investment has to ride on the back of a product that is genuinely selling. If nothing is working, you are not building a platform, you are avoiding a market.",
      "Publish the model internally. Not the vibe — the model. Which product is subsidizing which, what has to be true by when, and what would falsify it.",
      "Name the falsifier out loud. Ours is the time-to-first-customer curve. If it flattens for eighteen months, the platform is a story we tell ourselves and I will say so.",
    ]},
    { t: "h", x: "The part I cannot make comfortable" },
    { t: "p", x: "Some companies that look exactly like this are, in fact, just unfocused, and they also have a curve, and they also believe it. Conviction is not evidence. I have been wrong with total confidence before and the feeling was indistinguishable from being right." },
    { t: "p", x: "The only defence is to pick the falsifying metric before you need it, commit to it publicly while it is still abstract, and then actually look at it when it is inconvenient. That is not a satisfying answer. It is the honest one." },
  ],
},
{
  slug: "the-second-product",
  n: 5,
  title: "The second product is the whole company",
  deck: "Product one buys the account at full price. Every product after it arrives at a cost structure a standalone competitor can never match.",
  reading: "5 min",
  tags: ["Economics", "Go-to-market"],
  thesis: "Compounding is arithmetic, not narrative. But you only get to run the arithmetic if the second product is something the customer would have bought anyway.",
  body: [
    { t: "p", x: "The strategic argument for a compound startup is interesting. The financial argument is boring, which is why I trust it more." },
    { t: "h", x: "The arithmetic" },
    { t: "p", x: "Acquiring a customer is the single most expensive thing a software company does. Sales, marketing, evaluation cycles, security review, procurement, implementation — all of it, before a dollar of margin." },
    { t: "p", x: "You pay that once. Every product you sell into that account afterwards skips almost all of it. Same buyer, same contract, same security review, same implementation, often no new integration work at all because the data is already there." },
    { t: "cmp", a: { h: "Standalone competitor selling product two", x: "Full customer acquisition cost. Fresh evaluation, fresh procurement, fresh security review, fresh implementation, and an integration to build against whatever the customer already runs." }, b: { h: "Us selling product two", x: "An in-product upgrade to somebody already logged in, whose data is already correct, whose contract already exists. A fraction of the cost, structurally, forever." } },
    { t: "p", x: "That gap does not close with scale or cleverness. It is a property of where the products sit relative to the account. Which means our second product can be sold at the same price as theirs with a materially better contribution margin, or at a lower price with the same one. We get to choose which weapon to use, and they do not get a counter-move." },
    { t: "h", x: "Why this is not just bundling" },
    { t: "p", x: "This is where the strategy goes wrong for most people who try it, so I want to be blunt about the failure mode." },
    { t: "q", x: "If your second product only sells because it is bundled, you do not have a compound startup. You have a discount with extra steps." },
    { t: "p", x: "Attach rate is not a birthright. A product that customers accept because it is free and then never open is worse than not shipping it — it consumes engineering, it carries support load, it pollutes your usage data, and it teaches your sales team that the bundle does the work so the product does not have to." },
    { t: "p", x: "So the bar for product two is the same as the bar for product one: would this customer buy it standalone, on its merits, from us, if we charged for it? If the honest answer is no, we do not ship it and call the attach rate a win. We fix it or we kill it." },
    { t: "h", x: "The metrics that actually tell you" },
    { t: "ul", x: [
      "Products per customer, cohorted by signup year. This is the leading indicator of everything. If your 2023 cohort is not on more products today than they were at signup, the compounding is theoretical.",
      "Net revenue retention. In a compound model this should be well above one hundred percent without price increases doing the lifting. If NRR is carried by pricing rather than expansion, look closer.",
      "Payback period on product N, specifically excluding the acquisition cost of the account. This is the number that proves the structural advantage. It should be dramatically shorter than product one's.",
      "Standalone-willingness. Sample real customers on new products and ask whether they would pay for it alone. Unglamorous, qualitative, and the best early warning you have that a product is riding the bundle.",
      "Single-product churn versus multi-product churn. The gap here is the retention half of the thesis, and it is usually large enough to be the quiet reason the whole model works.",
    ]},
    { t: "p", x: "Notice that most of these are invisible in a normal SaaS dashboard, which reports on the company as though it sells one thing. If you run a compound startup on single-product metrics you will conclude you are mediocre at everything, because averaged across product lines, you are. The average is not the story. The cohort is." },
  ],
},
{
  slug: "the-platform-tax",
  n: 6,
  title: "The platform tax",
  deck: "Anyone can put one login in front of five products. The test is whether product six ships faster than product five did.",
  reading: "6 min",
  tags: ["Architecture", "Org design"],
  thesis: "Compounding is a claim about marginal cost. If your marginal cost per product is not falling, you do not have a platform — you have a holding company with a nav bar.",
  body: [
    { t: "p", x: "The compound story is easy to tell and easy to fake. Acquire four companies, put them behind one login, print a diagram with a layer at the bottom labelled Platform. Nothing about that is illegal and quite a lot of it is common." },
    { t: "p", x: "The customer finds out within a quarter. They change someone's department and discover it takes five clicks in five places, because underneath the shared nav there are still five employee tables and a sync job." },
    { t: "q", x: "A platform is not a layer on a diagram. It is a claim about marginal cost, and it is falsifiable." },
    { t: "h", x: "The only test that matters" },
    { t: "p", x: "Does product N ship faster than product N-1, with fewer people, at higher quality? If yes, the platform is real. If not, you are paying platform costs for holding-company outcomes, which is the worst position available." },
    { t: "p", x: "So we track it like a financial metric, by product line, over the life of the company: engineering months to general availability, headcount at launch, and defect rate in the first ninety days. Three columns, one row per product, in order. It is the most useful table in the company and it takes about a minute to read." },
    { t: "h", x: "What the tax actually pays for" },
    { t: "p", x: "A large share of our engineering builds things no customer will ever ask for by name. That share does not shrink as we grow — that is what makes it a tax rather than a project." },
    { t: "ul", x: [
      "Effective dating, applied uniformly. Every fact is true within a window. Every read can ask 'as of when'. Solve it once centrally or solve it badly in twenty places.",
      "The permissions model. Not roles — a model that can express 'managers can see comp for their own reports, in their own entity, excluding anyone above their level.' Every product needs this and no product should invent it.",
      "The workflow engine. Triggers, conditions, actions, approvals, effective dates, retries, and an audit trail. Products contribute triggers and actions; they never own orchestration.",
      "The country abstraction. Jurisdictional differences as data, not code. The moment 'what is different in Germany' lives in a conditional inside a product, you have started forking the company.",
      "One identity, one audit log, one notification surface. Boring, invisible, and the difference between a product suite and a product.",
    ]},
    { t: "note", label: "How we fund it", x: "The platform team is not funded from product budgets, because a product team asked to donate headcount to shared infrastructure will always find a reason not to, and will always be locally correct. It is funded off the top, as a fixed fraction, and the fraction is defended at the same level as headcount for a product line." },
    { t: "h", x: "The organizational fight this creates" },
    { t: "p", x: "This is a permanent tension and it does not resolve. A product team is blocked on a platform capability. The platform team is three weeks out. The pragmatic move — the one a good engineer will propose, with a good argument — is to build it locally, just this once, and migrate later." },
    { t: "p", x: "It is never migrated later. Every local copy becomes a permanent second source of truth, and the reconciliation logic it spawns outlives everyone who wrote it." },
    { t: "p", x: "So the rule is: teams own their product, never their primitives. Fork the interface freely. Never fork the employee, the permissions model, or the workflow engine." },
    { t: "p", x: "The cost of that rule is real and it lands on identifiable people. A team sits blocked. A date slips. Someone senior writes a memo about how this is slowing us down, and the memo is correct about the local facts and wrong about the global ones. I read it, I agree with the facts, and the answer is still no." },
    { t: "p", x: "Which is why the platform team's response time is a company-level metric, not a team-level one. If we are going to deny teams the escape hatch, we owe them a platform that is not the bottleneck. When platform lead time goes up, that is my problem, not theirs." },
  ],
},
{
  slug: "small-teams-big-surface",
  n: 7,
  title: "Small teams, big surface",
  deck: "The org chart is a consequence of the architecture. If the platform is real, teams can be small. If it isn't, they can't.",
  reading: "6 min",
  tags: ["Org design", "Hiring"],
  thesis: "You buy company-level speed with team-level friction. Anyone who wants that trade reversed is asking you to stop being a compound startup.",
  body: [
    { t: "p", x: "People assume that running many products means a huge organization. It means the opposite, if the platform is doing its job. A product team that does not have to build identity, permissions, audit, workflow, or country handling is a genuinely small team — often six or eight people owning a product line that a standalone company would staff with sixty." },
    { t: "p", x: "That is not because our people are better. It is because ninety percent of what a standalone company builds, we already have." },
    { t: "h", x: "Why small, specifically" },
    { t: "p", x: "A team of six that owns an entire product outperforms a team of twenty that owns a slice of one, and the reason is not headcount efficiency. It is that the team of six can hold the whole thing in their heads. They know every customer complaint, every edge case, every ugly compromise. Nobody has to be told what matters." },
    { t: "p", x: "Past about ten people that stops being true. You get specialization, then coordination overhead, then a manager whose job is translation, and the loop from customer pain to shipped fix gets a week longer every time you add a layer." },
    { t: "q", x: "Small teams are not a cost decision. They are a latency decision." },
    { t: "h", x: "The trade nobody likes" },
    { t: "p", x: "Here is the uncomfortable part, said plainly: this structure is slower for any individual team than the alternative would be." },
    { t: "cmp", a: { h: "What a team gives up", x: "The ability to solve their own problem their own way, today. They queue for platform work. They inherit constraints they did not choose. They ship a design that is eighty percent right for them because it is the design that is eighty percent right for everyone." }, b: { h: "What the company gets", x: "Product nine ships in eleven weeks instead of nineteen months. Every customer gets consistent permissions, consistent audit, consistent behaviour across every surface — which is the actual product." } },
    { t: "p", x: "That trade is the company. Anyone advocating to reverse it locally — even with an excellent local argument, even when they are right about their own team — is advocating to stop being a compound startup one exception at a time." },
    { t: "h", x: "What this means for who we hire" },
    { t: "ul", x: [
      "People who can hold a whole product. Breadth over depth in a narrow specialty, because a six-person team has no room for someone who only does one layer.",
      "People who are genuinely fine with the platform being someone else's decision. This is the single most common failure. Strong engineers with strong opinions who cannot accept a constraint they did not set will spend two years trying to route around it, and they will be locally right the entire time.",
      "People who ask about the seams. In interviews, the ones who ask how the product interacts with the rest of the system — rather than only about their own surface — are the ones who thrive here.",
      "Enough patience for a queue. If waiting three weeks for a platform capability reads as an insult rather than a trade, this is the wrong company, and it is better for everyone to find that out in the interview.",
    ]},
    { t: "h", x: "How the friction gets resolved" },
    { t: "p", x: "Not by escalation to me, most of the time. Escalation to me does not scale and it teaches people that volume wins." },
    { t: "ol", x: [
      "Product teams can always fork the interface. Anything above the primitive is theirs, no permission required. Most disputes evaporate here once people realise how much is actually theirs.",
      "Platform capabilities are requested in writing, with the customer problem stated first. Half of these turn out to be solvable with something that already exists, and writing it down surfaces that in a day instead of a sprint.",
      "Platform lead time is published. Every team can see the queue and its own position in it. Nothing corrodes trust faster than an invisible queue, because people assume they are last.",
      "If a team is blocked for more than a month, that is a platform staffing failure and it goes on my list, not theirs. The rule only holds if the platform holds up its end.",
    ]},
    { t: "p", x: "None of this eliminates the tension, and I would be suspicious of any version of it that claimed to. The tension is structural. The job is to keep it productive rather than to pretend it is resolved." },
  ],
},
];
