import type { Essay } from "./types";

export const MANUAL_C: Essay[] = [
{
  slug: "compliance-is-infrastructure",
  n: 8,
  title: "Compliance is infrastructure, not a department",
  deck: "In a regulated category, the regulatory surface is the product surface. Treat it as a review function and you have built a machine that generates violations and a team that finds some of them.",
  reading: "6 min",
  tags: ["Compliance", "Architecture", "Hard parts"],
  thesis: "The goal is not a team that catches the bad action. The goal is a system where the bad action cannot be expressed.",
  body: [
    { t: "p", x: "If you sell payroll, benefits, or anything touching employment law, you are not a software company with a compliance obligation. You are a compliance company that ships software. The distinction sounds like word games until you look at where it changes a decision, and it changes almost all of them." },
    { t: "h", x: "Two ways to hold it" },
    { t: "cmp", a: { h: "Compliance as a function", x: "A team reviews things. They sit downstream of product decisions and say yes or no. Their success is measured in issues caught. Structurally, they are a tax on velocity and everyone experiences them that way, including them." }, b: { h: "Compliance as infrastructure", x: "The rules are encoded in the system. The non-compliant action is not available in the interface. Success is measured in violations that were never possible. The team's job is to build the constraint, not to police the exception." } },
    { t: "p", x: "The first version fails in a specific and predictable way: it depends on humans catching things, at volume, forever, under deadline pressure, in a system that is generating new opportunities to be wrong faster than anyone can review them. Review-based compliance has a hit rate below one, and the misses compound silently until something forces an accounting." },
    { t: "q", x: "You do not want a team that catches it. You want a form that will not let you type it." },
    { t: "h", x: "What this looks like concretely" },
    { t: "ul", x: [
      "An employee cannot be created in a state where the entity has no registration. The form does not warn you. It opens the registration and blocks the hire until it clears.",
      "Benefits elections are filtered by jurisdiction before they render. An ineligible plan is not shown and rejected — it does not exist on that screen for that person.",
      "Contractor-to-employee conversion cannot be completed without the country-correct agreement executed, because the status change is gated on the document, not accompanied by it.",
      "Every write to the employee record is append-only with an actor, a timestamp, and a reason. Not for us. For the auditor who arrives in three years asking what was true in March, and for the amended filing that depends on the answer.",
      "Termination sequencing is encoded per jurisdiction. Final-pay timing in California is not the same as Ontario is not the same as Germany, and no human should be expected to hold that.",
    ]},
    { t: "p", x: "In each case the compliance work happened at design time, once, and then it is simply how the software behaves. Nobody has to remember. Nobody has to be trained. Nobody catches anything, because there is nothing to catch." },
    { t: "h", x: "Why I hold this so hard" },
    { t: "p", x: "I have watched a company be destroyed by the gap between what a system permitted and what the rules required. It is a matter of public record and I am not going to relitigate it here. What I will say is what I took from it, because that is the part that is actually useful to anyone." },
    { t: "p", x: "The lesson is not 'be more careful.' Careful is not a system. Careful degrades under pressure, at scale, at 6pm on the last day of a quarter, in an org where the person with the context is on leave." },
    { t: "p", x: "The lesson is that if a system makes a violation possible, the violation will eventually occur, and the interval is a function of volume rather than of anyone's intent. So the only durable answer is to make it not expressible. Everything else is hoping." },
    { t: "note", label: "The cost, stated plainly", x: "This is slower. Encoding a rule in the system is dramatically more expensive than writing it in a policy document and asking a team to enforce it. We accept a real velocity cost for it, deliberately, and I will not let that cost be traded away when a quarter is tight — because the quarter when it gets traded away is exactly the quarter it matters." },
    { t: "h", x: "The version of this that is wrong" },
    { t: "p", x: "There is a failure mode on this side too, and it is worth naming so nobody weaponises the principle. You can encode rules so aggressively that the product cannot express legitimate reality — the genuine edge case, the negotiated exception, the situation the regulation did not anticipate. Then people route around your system entirely, into a spreadsheet, and now you have neither compliance nor data." },
    { t: "p", x: "So the design rule is narrower than it first sounds: encode the constraint, always provide a documented path for the exception, and make that path leave a record. The goal is not that nothing unusual can happen. It is that nothing unusual can happen invisibly." },
  ],
},
{
  slug: "when-not-to-do-this",
  n: 9,
  title: "When this is the wrong strategy",
  deck: "The compound model has preconditions. Most companies do not meet them, and running it anyway is the most expensive mistake available.",
  reading: "5 min",
  tags: ["Strategy", "Hard parts"],
  thesis: "If your products share a category but not a record, you are not compounding. You are diversifying, which is a different thing with none of the same advantages.",
  body: [
    { t: "p", x: "I get asked to endorse this strategy for companies it will destroy. So here is the version I would give you privately, which is mostly a list of reasons not to." },
    { t: "h", x: "The four preconditions" },
    { t: "ol", x: [
      "A shared record. Not a shared theme — a literal object that every product reads and writes. If product A's core object is the employee and product B's is the shipment, you have two companies sharing a lobby. The compounding comes from the record, and there is no substitute for it.",
      "A shared buyer. The same human being, with the same budget and the same signature. 'Both sold to enterprises' is not a shared buyer. If the second product needs a new champion, a new budget line, and a new procurement path, you are paying full acquisition cost again and the core arithmetic collapses.",
      "A shared pipe. Same motion, same onboarding, same support surface. If product two is self-serve and product one is field sales, you are running two companies with one logo.",
      "A market that amortizes the platform. The shared layer is expensive and mostly fixed. If your total addressable market supports three products, the platform will never pay back. This strategy needs breadth to be worth its own overhead.",
    ]},
    { t: "p", x: "Miss any one and the model does not partially work. It inverts — you carry all of the cost and get none of the leverage, which is strictly worse than having built one good product." },
    { t: "h", x: "Categories where it usually fails" },
    { t: "ul", x: [
      "Consumer. There is rarely a shared record with real gravity, the acquisition cost advantage is thin because consumer acquisition is not a one-time gate, and users do not consolidate vendors for the sake of consolidation.",
      "Marketplaces. Both sides are customers, so 'shared buyer' fails immediately. Adding products usually means picking a side, which is a strategy change wearing a product costume.",
      "Infrastructure sold to developers. The buyer is real but the record often is not — your products may share an API surface without sharing an object, and developers are the one buyer segment who genuinely will assemble best-of-breed themselves and enjoy it.",
      "Anything pre-product-market-fit. This is the big one and it is not about category at all.",
    ]},
    { t: "q", x: "Compound is a second act. If the first act did not work, there is nothing to compound." },
    { t: "h", x: "The sequencing mistake" },
    { t: "p", x: "The most common way to get this wrong is to start compound. To decide at founding that you are building a platform, and to build the shared layer before you have a single product anyone loves." },
    { t: "p", x: "It is fatal for a boring reason: you cannot know what to abstract. Platform decisions made before you have shipped anything are guesses dressed as architecture, and you will spend three years supporting abstractions that solved problems you turned out not to have." },
    { t: "p", x: "The order is: build one product that genuinely works. Then, while building the second, notice what you are rebuilding, and extract that. The platform is discovered, not designed. Anyone who tells you they designed theirs up front is describing it with the benefit of hindsight." },
    { t: "h", x: "The capital test" },
    { t: "p", x: "Last one, and it is not about the idea at all. Can you raise through the J-curve? Three or four years where the numbers look mediocre and the story requires the listener to hold a model?" },
    { t: "p", x: "If you cannot — if you have eighteen months of runway and a board that wants efficient growth next year — then this strategy is not available to you regardless of whether it is correct. That is not a failure of nerve. It is a constraint, and choosing a strategy your balance sheet cannot survive is not conviction, it is negligence with a good narrative." },
  ],
},
{
  slug: "write-it-down",
  n: 10,
  title: "Write it down",
  deck: "Openness here is not a value, it is a compression algorithm. With this many teams, alignment by conversation is quadratic and writing is the only thing that scales.",
  reading: "5 min",
  tags: ["Culture", "Org design"],
  thesis: "Transparency has real costs and we pay them on purpose, because the alternative is a company where every decision is auditable by exactly the three people who were in the room.",
  body: [
    { t: "p", x: "We write a lot here and new people usually think it is a stylistic preference of mine. It is not. It is a direct consequence of the strategy, and if we ran fewer products I would care about it less." },
    { t: "h", x: "The coordination math" },
    { t: "p", x: "With one product, alignment happens by proximity. Everyone is working on the same thing, they overhear each other, and the shared context maintains itself for free." },
    { t: "p", x: "With twenty product teams on a shared platform, that breaks completely. Team A's decision constrains Team M in a way neither of them will discover for two quarters. The number of pairs that need to stay aligned grows with the square of the number of teams, and there is no meeting schedule that fixes a quadratic." },
    { t: "q", x: "Every decision that lives only in a conversation is a decision auditable by exactly the people who were in the room." },
    { t: "p", x: "Writing converts that. A decision written down is discoverable by anyone, at any time, without the author present, including years later when the author has left and someone is asking why this constraint exists. That is the whole argument. It is not about eloquence and I do not care if the prose is good." },
    { t: "h", x: "What we actually require" },
    { t: "ul", x: [
      "Decisions get logged with the alternative that was rejected and the reason. The rejected path is the valuable half. Anyone can see what we chose by looking at the code; only the log says what we chose against, which is what stops the same debate recurring annually.",
      "Every decision names a revisit trigger. Not a date — a condition. 'Revisit if platform lead time exceeds four weeks.' Decisions without triggers become permanent by accident.",
      "Platform requests are written before they are discussed. This one is unpopular and it survives because roughly half of all requests dissolve on contact with a written problem statement.",
      "Numbers are shared broadly and by default. Revenue by product line, retention, the platform lead time queue, burn. People make better local decisions with global context, and they make worse ones when they are guessing.",
    ]},
    { t: "h", x: "The costs, which are real" },
    { t: "p", x: "I want to be honest that this is not free, because the way transparency usually gets discussed is as an unalloyed good, and it is not." },
    { t: "ol", x: [
      "Things leak. Not often, and rarely maliciously, but if you share numbers with hundreds of people some of them will travel. We price that in rather than pretending our culture prevents it.",
      "Bad quarters are visible to everyone, including people with no ability to affect them. That produces anxiety, and telling people not to be anxious does not work. What works is pairing every number with the decision it informs, so context arrives with the data rather than a week later.",
      "Writing is slow. A memo takes an afternoon that a conversation takes twenty minutes. The payback is real but it is deferred, and on any given day the conversation is genuinely the better local choice.",
      "It advantages good writers in a way that is not entirely fair, and left alone it becomes a quiet promotion filter. That is a real equity problem, and the mitigation is editing help and explicitly separating the quality of an argument from the quality of its prose in review conversations.",
    ]},
    { t: "p", x: "We pay all four. Not because openness is virtuous — I think a lot of companies that talk about transparency are describing a mood rather than a practice — but because the arithmetic of running many teams on one platform does not leave another option." },
    { t: "note", label: "The test", x: "If a decision cannot be explained in writing to someone who was not in the room, it is not a decision. It is a preference that has not been examined yet, and it will be relitigated by someone new in about nine months." },
  ],
},
];
