import type { CompanyStudy } from "../companies";
import { TALENT_NAVIGATION } from "./talent-navigation";
import type { VendorSkin } from "../vendors/types";

const S = {
  origin: "https://www.servicenow.com/uk/workflow/platform-foundations/servicenow-platform-first-forever.html",
  founder: "https://www.servicenow.com/company/leadership/frederic-luddy.html",
  csdm: "https://www.servicenow.com/docs/r/servicenow-platform/common-service-data-model-csdm/foundation-domain.html",
  sow: "https://www.servicenow.com/docs/r/it-service-management/service-operations-workspace/view-update-inc-overview-tab.html",
  dependencies: "https://www.servicenow.com/docs/r/it-service-management/service-operations-workspace/work-on-change-sow.html",
  assist: "https://www.servicenow.com/docs/r/it-service-management/now-assist-for-it-service-management-itsm/now-assist-itsm-incident-assist-workflow.html",
  debt: "https://www.servicenow.com/docs/r/servicenow-platform/service-catalog/customization-vs-configuration-concepts.html",
  bill: "https://www.servicenow.com/company/media/press-room/servicenow-announces-bill-mcdermott-to-become-ceo-succeeding-john-donahoe-who-is-stepping-down-to-become-ceo-of-nike.html",
  leaders: "https://www.servicenow.com/in/company/leadership.html",
  amit: "https://newsroom.servicenow.com/press-releases/details/2024/ServiceNow-appoints-Amit-Zavery-as-president-CPO-and-COO-10-23-2024-traffic/default.aspx",
  element: "https://www.sec.gov/Archives/edgar/data/1373715/000137371521000006/now-20210108.htm",
  deals: "https://www.sec.gov/Archives/edgar/data/1373715/000137371525000309/R12.htm",
  logik: "https://www.servicenow.com/docs/r/zurich/order-management/guided-setup-prereq.html?contentId=3bvWIMZLG0RDBHwDj~5RpQ",
  moveworks: "https://newsroom.servicenow.com/press-releases/details/2025/ServiceNow-completes-acquisition-of-Moveworks/default.aspx",
  employeeworks: "https://investor.servicenow.com/news/news-details/2026/ServiceNow-launches-Autonomous-Workforce-that-thinks-and-acts-adds-Moveworks-to-the-ServiceNow-AI-Platform/default.aspx",
  employeeui: "https://www.servicenow.com/community/sn-employeeworks-blog/servicenow-employeeworks-introducing-employeeworks-web-app/ba-p/3537890",
  employeeupdate: "https://www.servicenow.com/community/sn-employeeworks-blog/servicenow-employeeworks-what-s-new-in-employeeworks-web-app/ba-p/3585488",
  lifecycle: "https://www.servicenow.com/docs/r/employee-service-management/lifecycle-events/hr-lifecycle-events-landing-page.html",
  veza: "https://veza.com/blog/veza-servicenow-the-enterprise-agent-identity-control-plane/",
  armis: "https://newsroom.servicenow.com/press-releases/details/2026/ServiceNow-completes-Armis-acquisition-closing-the-gap-between-asset-visibility-and-cyber-risk/default.aspx",
  security: "https://newsroom.servicenow.com/press-releases/details/2026/ServiceNow-launches-Autonomous-Security--Risk-integrating-Armis-and-Veza-to-govern-every-AI-agent-identity-and-connected-asset/default.aspx",
  tower: "https://www.servicenow.com/docs/r/intelligent-experiences/aict-activity-center.html",
  towerrelease: "https://www.servicenow.com/community/ai-control-tower-articles/ai-control-tower-what-s-new-in-the-june-2026-release/ta-p/3561445",
  connectors: "https://www.servicenow.com/docs/r/intelligent-experiences/aict-configuring-integrations.html",
  fabric: "https://newsroom.servicenow.com/press-releases/details/2026/ServiceNow-opens-its-full-system-of-action-to-every-AI-Agent-in-the-enterprise/default.aspx",
  crm: "https://www.servicenow.com/docs/r/customer-relationship-management/crm-data-models.html",
  partners: "https://newsroom.servicenow.com/press-releases/details/2026/ServiceNow-and-Accenture-launch-forward-deployed-engineering-program-to-scale-agentic-AI-across-the-enterprise/default.aspx",
};
const skin: VendorSkin = {
  id: "servicenow", name: "ServiceNow", studyOf: "ServiceNow's service context, workflow and governed AI execution", bet: "Make the obligation survive the handoffs.",
  ethos: "Records, relationships, accountable owners and separate completion evidence.", href: "/companies/servicenow/app", depth: "Full study",
  theme: { bg: "#F2F5F2", surface: "#FFFFFF", surfaceAlt: "#F8FAF8", border: "#D9E1DB", ink: "#19362D", inkMuted: "#53675E", inkFaint: "#64776D", accent: "#21684F", accentInk: "#FFFFFF", accentSoft: "#E3EEE6", radius: "10px", radiusSm: "6px", font: 'Inter, system-ui, "Segoe UI", sans-serif', chrome: "sidebar", density: "normal" },
  nav: [], greeting: { eyebrow: "Meridian Optics", title: "ServiceNow", sub: "Illustrative enterprise operations" }, home: [], xray: [],
};

export const SERVICENOW_STUDY: CompanyStudy = {
  ecosystem: { href: "/atlas/servicenow", label: "ANZ ecosystem" },
  id: "servicenow", name: "ServiceNow", archetype: "Enterprise workflow & AI platform", skin,
  brand: { chrome: "#17352C", ink: "#FFFFFF", highlight: "#B8DDB6" },
  appScreens: ["", "operations", "employees", "control-tower"], workflowScreen: "operations",
  backstage: {
    navigation: TALENT_NAVIGATION,
    headline: "Make the obligation survive the handoffs.",
    thesis: "ServiceNow turns fragmented enterprise obligations into work that can be assigned, governed and completed. Its service model explains what matters; its workflows carry the responsibility; its current AI strategy tries to make that machinery useful wherever the request begins. The hard part is earning coherence as the company expands both its reach and the records it owns.",
    object: "Accountable work + service relationships", question: "Who owns the next action—and what proves the outcome?",
    sequence: ["Understand the request and affected service", "Assign work with its context and authority", "Carry the obligation across teams and systems", "Confirm the outcome before closing the record"],
    premises: [
      { title: "Restore the service, not just close the incident", body: "A technical alert becomes a business decision when the affected service, its dependencies, its owner and a relevant change are visible together. ServiceNow's operational depth matters at that connection. The demo makes a shared database change consequential: both service owners participate, and both outcomes need fresh checks after execution.", screen: "operations" },
      { title: "Carry intent across departmental boundaries", body: "EmployeeWorks and Otto bring an employee's request into the workflow. Lifecycle tasks carry it through HR, IT and workplace teams while specialist systems retain their own responsibilities. The value is a completed obligation, not a collection of locally closed tickets.", screen: "employees" },
      { title: "Make AI accountable before it acts", body: "AI Control Tower connects assets, ownership, evidence and lifecycle decisions. Action Fabric extends governed workflows to external AI front doors. Inventory is a starting point; authority and a verified execution result are additional things the system must establish. The fictional workflow preserves owner revisions, new reviews and rollback receipts in the same record.", screen: "control-tower" },
    ],
    choices: [
      { choice: "Reuse a configurable workflow foundation", gain: "New obligations can inherit assignment, state, approvals, service relationships and an audit trail instead of rebuilding them.", cost: "Someone must maintain the model and process. Bespoke customisation can increase upgrade work and make the next change harder, not easier." },
      { choice: "Orchestrate existing systems while expanding the owned core", gain: "A workflow can cross an HRIS or ERP boundary without first replacing the source system; native CRM objects can remove other handoffs.", cost: "Neutrality is conditional. Owning more selling, fulfilment and service records changes the relationship with incumbents ServiceNow also connects to." },
      { choice: "Expose work to agents and buy more of the surrounding context", gain: "Moveworks adds intent and search; data.world adds semantic context; Armis and Veza add asset and permission intelligence.", cost: "Acquisition closes do not prove a unified runtime. Integration, scoped authority, licensing and customer implementation still determine what can actually execute." },
    ],
    proof: [
      { metric: "Business recovery, not ticket velocity", test: "Follow an incident from its affected service through a controlled fix and a returned health check. Measure disruption, wrong-team handoffs and recurrence.", failure: "The incident closes sooner but service restoration is unverified or the same outage returns." },
      { metric: "The original obligation reaches completion", test: "Trace one employee transition through manager review, an external identity task and workplace readiness. Include elapsed time across all teams.", failure: "Each queue looks efficient while the employee still cannot work. A dispatched task is counted as a completed outcome." },
      { metric: "Useful, authorised outcomes per unit of AI consumption", test: "Measure completed work against model cost, platform consumption, human review and rework. Try a request outside the agent's scope.", failure: "Assists grow while useful completion does not, or governance inventories assets without controlling consequential changes." },
    ],
    sources: [
      { title: "Platform-first history · Pat Casey, July 2025", url: S.origin, supports: "First-person account of Glide, the ITSM beachhead and the reusable platform foundation. Not an independent performance study." },
      { title: "Fred Luddy · official biography", url: S.founder, supports: "Founder and 2004 origin." },
      { title: "CSDM foundation and stewardship", url: S.csdm, supports: "Trusted data sources, maintainers and update cadence. A populated CMDB is not inherently current." },
      { title: "Service Operations Workspace incident anatomy", url: S.sow, supports: "Incident context, affected services/CIs, dependency view and related work." },
      { title: "Change impact and dependency views", url: S.dependencies, supports: "Inspect CIs and services potentially affected by a change. The two-service recovery policy in the app is fictional, not a default ServiceNow approval rule." },
      { title: "Current incident-assist workflow", url: S.assist, supports: "Otto contextual retrieval workflow; the old Incident assist skill is deprecated in Australia Patch 2. Retrieval is not autonomous rollback." },
      { title: "Configuration, customisation and maintenance", url: S.debt, supports: "Upgrade and maintenance consequences of customisation." },
      { title: "McDermott appointment · October 2019", url: S.bill, supports: "CEO succession announcement. The study uses the November 2019 transition month, not announcement as effective date." },
      { title: "Current leadership", url: S.leaders, supports: "Bill McDermott chairman/CEO; Amit Zavery president/CPO/COO at the research date." },
      { title: "Zavery appointment · October 2024", url: S.amit, supports: "Combined platform, products, engineering, infrastructure, experience and operations remit, effective 28 October." },
      { title: "Element AI completion · January 2021", url: S.element, supports: "SEC filing: completed 8 January 2021. Historical capability acquisition, not a separate current app." },
      { title: "Logik and data.world completion · SEC", url: S.deals, supports: "Logik.io closed 30 May 2025; data.world closed July 2025. No exact July day inferred." },
      { title: "CPQ setup and Logik tenant boundary", url: S.logik, supports: "Current setup still requires CPQ provisioning, Logik tenant information and OAuth configuration." },
      { title: "Moveworks completion · December 2025", url: S.moveworks, supports: "15 December close; employee assistant, search and reasoning capabilities." },
      { title: "EmployeeWorks launch · February 2026", url: S.employeeworks, supports: "EmployeeWorks GA on 26 February. A forecast for autonomous specialist availability is not treated as proof of shipment." },
      { title: "EmployeeWorks web app · current anatomy", url: S.employeeui, supports: "Conversational home, Tasks & Requests, split-view content and employee navigation. Public screenshots informed the scene." },
      { title: "EmployeeWorks updates · August 2026", url: S.employeeupdate, supports: "Explore/Browse and configured external context for task insights. External HR data is not automatically native." },
      { title: "HR Lifecycle Events", url: S.lifecycle, supports: "Cross-department fulfilment of employee transitions." },
      { title: "Veza close · March 2026", url: S.veza, supports: "Veza's first-party confirmation of 2 March completion and identity/permission context." },
      { title: "Armis close · April 2026", url: S.armis, supports: "20 April completion and cyber-asset/exposure intelligence across operational environments." },
      { title: "Autonomous Security & Risk · May 2026", url: S.security, supports: "New portfolio direction combining Armis and Veza; a partner ecosystem remains part of the model." },
      { title: "AI Control Tower Activity Center · July 2026 docs", url: S.tower, supports: "Current light workspace, ownership filters, work types and model-change request example." },
      { title: "AI Control Tower June 2026 release", url: S.towerrelease, supports: "GA discovery and managed-asset rules; Agent 365 publication is not proof of universal runtime enforcement." },
      { title: "AI Control Tower connector boundaries", url: S.connectors, supports: "Discovered/unmanaged versus managed assets; configured discovery and trace collection." },
      { title: "Action Fabric · May 2026", url: S.fabric, supports: "Generally available MCP Server and headless action consumption using Assists. Consumption is not guaranteed business-outcome pricing." },
      { title: "CRM data architecture", url: S.crm, supports: "Shared customer, product and transactional records across selling, fulfilment and service." },
      { title: "Accenture delivery programme · May 2026", url: S.partners, supports: "Customer-embedded implementation and industry expertise remain part of delivery, even in the agentic proposition." },
    ],
  },
  strategy: {
    contrast: "Rippling starts with the employee and follows the consequences. ServiceNow starts with an obligation and follows the work required to discharge it. The source record may live elsewhere; the responsibility for the handoff cannot remain nowhere.",
    flywheel: { title: "The next workflow should inherit what the last one established.", body: "Reusable owners, service relationships, permissions and resolution knowledge can reduce the effort of the next outcome. This is the compounding argument to test—not the assumption that buying another module automatically makes the organisation more effective.", steps: ["Establish trusted context", "Complete accountable work", "Retain reusable knowledge", "Extend to the next obligation"], constraint: "A neglected service model and a growing backlog of bespoke process can compound maintenance cost instead of value." },
    moments: [
      { date: "2004 →", title: "A platform finds its demanding first application", fact: "Fred Luddy founds ServiceNow in 2004. Pat Casey's account describes a platform whose saleable beachhead became IT service management.", consequence: "Workflows, relationships and configuration precede the later portfolio. The history is more useful than treating every new category as a ticketing-tool extension.", source: S.origin, sources: [S.founder] },
      { date: "2019 → 2024", title: "A broader executive remit, then combined product authority", fact: "McDermott's CEO transition follows the October 2019 announcement. Zavery joins in October 2024 with a combined product, engineering and operations remit.", consequence: "Enterprise-wide ambition now has to translate into coherent product execution. Neither leader originated the platform foundation.", source: S.amit, sources: [S.bill] },
      { date: "2021", title: "AI investment predates the agentic chapter", fact: "Element AI acquisition completes on 8 January 2021.", consequence: "The recent shift is in interaction, execution and governance. An early capability acquisition is not evidence that every current model descends from it.", source: S.element },
      { date: "2025", title: "Logik adds commercial rules; data.world adds semantic context", fact: "Logik.io closes on 30 May; data.world closes in July. Current CPQ setup still exposes a Logik tenant and connection boundary.", consequence: "A quote must become executable, and an agent must understand its data. Ownership of those capabilities does not settle how completely the products are integrated.", source: S.deals, sources: [S.logik] },
      { date: "Dec 2025 → Feb 2026", title: "Moveworks changes the employee's front door", fact: "Moveworks closes on 15 December 2025; EmployeeWorks reaches general availability on 26 February 2026.", consequence: "Search and conversational intent can lead into the existing process foundation. An answer-only assistant would leave much of the acquired value unrealised.", source: S.moveworks, sources: [S.employeeworks] },
      { date: "Mar → May 2026", title: "Asset and permission context move inside the perimeter", fact: "Veza closes on 2 March; Armis closes on 20 April. The May security launch combines their capabilities in the expanded portfolio.", consequence: "The agent strategy creates a control problem of its own: which identity may change which asset? Better context matters before remediation, not just after an incident.", source: S.security, sources: [S.veza, S.armis] },
    ],
    leadership: {
      title: "McDermott's breadth; Zavery's coherence test.",
      fact: "Bill McDermott remains chairman and CEO. Amit Zavery joined as president, chief product officer and COO in October 2024, with a remit spanning product, engineering, cloud infrastructure, user experience and enterprise operations.",
      reading: "The company is broadening from enterprise workflow into the context, entry points and controls around AI execution. McDermott's enterprise ambition and Zavery's combined remit make the direction intelligible. They do not prove personal authorship of each release. The useful leadership test is whether acquisitions and new experiences make the customer's next outcome easier to deliver.",
      watch: "Follow one request from an AI front door into its governing workflow and back with a receipt. Then repeat it across an acquired product boundary. If the customer must reconstruct identity, data meaning and ownership each time, portfolio breadth is running ahead of coherence.", sources: [S.leaders, S.amit, S.moveworks, S.security],
    },
    essays: [
      { slug: "service-context", title: "The incident was the wedge. Service ownership is the asset.", standfirst: "The useful graph connects technical events to business consequences.", paragraphs: [
        "A ticket queue records demand. A service model helps explain why the demand matters, which team owns the consequence and what a response might disturb. The jump from a database alarm to an unavailable ordering service is where technical context becomes a business decision.",
        "ServiceNow's early platform was shaped by work that needed assignment, deadlines, related records and change control. Those primitives can be reused beyond IT without pretending every department has the same process. The expansion case is that the next obligation inherits a foundation, rather than starting with a new queue and an unrelated set of owners.",
        "The foundation has a carrying cost. CSDM documentation calls for trusted sources, maintainers and an update cadence. An impressive count of configuration items says little about whether today's service relationships are correct. Summarising a case may still be useful with partial context; automatically changing infrastructure demands stronger evidence of dependencies and authority.",
        "Installed knowledge can therefore compound or fossilise. Trusted relationships and resolution history make new work easier. Bespoke process can turn into technical debt and upgrade friction. The strategic asset is an operational model the customer can maintain—not the volume of records the platform has accumulated.",
      ], test: "Track business-service recovery and recurrence alongside the incident clock. A faster closure with an unverified service state is a reporting improvement, not operational recovery.", sources: [S.origin, S.csdm, S.sow, S.debt] },
      { slug: "unfinished-handoffs", title: "The enterprise pays for unfinished handoffs.", standfirst: "Local completion is cheap to report. The whole obligation is harder to finish.", paragraphs: [
        "An HR system can record a transfer while the employee still lacks access. An order system can record a sale while fulfilment is waiting on an exception. Each application can be correct about its own transaction and still leave the original human obligation unfinished.",
        "ServiceNow's expansion opportunity is to own that remaining work: one visible request, linked tasks in the right domains, explicit approvals and a way to confirm the outcome. EmployeeWorks puts a conversational front door on this machinery. The August 2026 addition of browsing and configured external task context suggests the experience must support navigation and detailed follow-through as well as conversation.",
        "The boundary with existing systems is a strategic choice, not a permanent promise of neutrality. A workflow can coordinate an external HRIS; ServiceNow's CRM data architecture also owns shared customer, product and transactional objects across selling and service. Owning more records can remove friction and enlarge the commercial relationship, while changing whom ServiceNow competes with.",
        "Delivery expertise remains part of the economics. Customer policy, data stewardship and process redesign do not disappear because the platform adds agents. The Accenture delivery programme makes that visible. The sharp test is whether a second department becomes cheaper to bring onto the foundation after including implementation, support and the customer's own operating effort.",
      ], test: "Measure the elapsed time to an employee being able to work, including every external handoff. Do not count a dispatched identity task as access delivered.", sources: [S.lifecycle, S.employeeupdate, S.crm, S.partners] },
      { slug: "workflow-still-earns", title: "When the front door moves, the workflow still has a job.", standfirst: "An answer can travel freely. Enterprise authority cannot be invented by the assistant.", paragraphs: [
        "An employee may stop navigating a traditional application and ask Otto or another assistant instead. That threatens a portal's share of attention, but it does not eliminate the need for an authorised execution path. The durable claim moves toward current identity, operational context, approved procedures and evidence of what happened.",
        "Moveworks strengthens ServiceNow's own front door. Action Fabric gives external agents another way into the work. Its May 2026 announcement describes a generally available MCP Server and headless actions using the same Assist currency. This is a concrete revenue mechanism: work can remain commercially valuable even when a human never opens the workspace. It is consumption pricing, not proof of a useful business outcome.",
        "AI Control Tower addresses a related but different problem: which AI assets exist, who owns them, what evidence supports a lifecycle change and which exceptions need a decision? Armis and Veza broaden asset and permission context. Discovery alone is insufficient. An inventoried agent may still be unmanaged, and an approved model change may still be waiting for the external runtime to deploy it.",
        "The risk is that the platform becomes another console the enterprise must operate. The stronger outcome is that governance is attached to consequential work and lowers the total cost of doing it safely. More Assist consumption can accompany more useful automation—or more loops, retries and review. The denominator must be completed, authorised work, with exceptions and remediation included.",
      ], test: "Submit an out-of-scope request, then a permitted one. The first should stop or escalate; the second should produce an inspectable result. Count the whole cost of reaching that result.", sources: [S.moveworks, S.fabric, S.tower, S.connectors, S.security] },
    ],
    watch: { title: "A broader execution layer, with the release boundaries intact", shipped: "EmployeeWorks is GA, with a newer web experience and August updates. Current AI Control Tower docs show assigned work and lifecycle requests; June releases identify specific GA discovery and management capabilities. Action Fabric's MCP Server was announced as GA in May.", next: "Watch whether acquired intent, semantic context, asset visibility and permission intelligence reduce the effort to complete a governed cross-system action.", boundary: "The May roadmap does not prove every later Control Tower enhancement shipped. Agent 365 publication does not establish universal runtime enforcement. A recorded approval, a completed deployment and an observed outcome remain separate facts.", source: S.towerrelease },
  },
};
