"use client";
import Link from "next/link";
import { useState } from "react";
import { companyHref, type CompanyStudy } from "@/lib/companies";
import { TEAM, REVIEW_BUDGET, remunerationSummary, canSubmitRemuneration, validIncrease } from "@/lib/data/study-scenarios";
import { PageHeading, StudyAppShell } from "./shell";
import s from "./study.module.css";

const NAV = [["", "Home"], ["people", "My Team"], ["learning", "Learning"], ["remuneration", "Remuneration"], ["integrations", "Payroll connections"]] as const;
const dollars = (n: number) => new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD", maximumFractionDigits: 0 }).format(n);
export function ElmoApp({ company, screen }: { company: CompanyStudy; screen: string }) {
  return <StudyAppShell company={company} screen={screen} nav={NAV}>{screen === "" ? <Home/> : screen === "people" || screen === "learning" ? <Capability learning={screen === "learning"}/> : screen === "remuneration" ? <Remuneration/> : <Connections/>}</StudyAppShell>;
}
function Home() {
  return <>
    <PageHeading eyebrow="Manager workspace" title="Make the next people decision in context.">Your team's capability, development and reward cycle belong together. Start with the gap or review that needs your attention.</PageHeading>
    <div className={s.grid}>{[
      ["Team capability", "2", "People below a role target", "people"], ["Review cycle", "$14,000", "Illustrative increase budget", "remuneration"], ["Payroll connections", "1", "Mapped-field conflict to review", "integrations"],
    ].map(([title, value, detail, route]) => <Link key={title} className={s.card} href={companyHref("elmo", "app", route)}><p className={s.label}>{title}</p><div className={s.stat}>{value}</div><p className={s.muted}>{detail}</p><div className={`${s.link} mt-4`}>Open workspace →</div></Link>)}</div>
    <section className={`${s.card} ${s.section}`}><div className={s.strip}><h2>My Team</h2><span className={s.badge}>Engineering · 3 demo people</span></div><div className={s.tablewrap}><table className={s.table}><thead><tr><th>Person</th><th>Role</th><th>Capability</th><th>Next action</th></tr></thead><tbody>{TEAM.map(p => <tr key={p.id}><td className={s.name}>{p.name}</td><td>{p.role}</td><td><span className={`${s.badge} ${p.assessed < p.target ? s.warn : s.good}`}>{p.assessed < p.target ? "Development needed" : "At target"}</span></td><td><Link className={s.link} href={companyHref("elmo", "app", "people")}>Review capability →</Link></td></tr>)}</tbody></table></div></section>
    <div className={s.callout}><strong>The ELMO idea:</strong> start with the team's needs and connect the HR actions that follow. Learning completion, demonstrated capability and pay approval remain different facts.</div>
  </>;
}
function Capability({ learning }: { learning: boolean }) {
  const [selected, setSelected] = useState(0), [assigned, setAssigned] = useState<string[]>([]); const p = TEAM[selected];
  const levels = ["Novice", "Competent", "Proficient", "Leading", "Expert"];
  return <>
    <PageHeading eyebrow={learning ? "Learning / Development plans" : "My Team / Capability framework"} title={learning ? "Development with a reason." : "The role sets the target."}>Compare assessed capability with the role's required proficiency. Assigning development starts a plan; it does not erase the gap.</PageHeading>
    <div className={s.tabs} aria-label="Team member">{TEAM.map((person, i) => <button key={person.id} aria-pressed={selected === i} onClick={() => setSelected(i)}>{person.name}</button>)}</div>
    <div className={s.two}><section className={s.card}><p className={s.label}>Job family · Engineering</p><h2 className="mt-3">{p.role}</h2><p className={s.muted}>{p.name} · manager assessment · September review</p><div className={s.strip}><h3>{p.capability}</h3><span className={`${s.badge} ${p.assessed < p.target ? s.warn : s.good}`}>{p.assessed < p.target ? "Below role target" : "At role target"}</span></div><div className={s.tablewrap}><table className={s.table}><thead><tr><th>Assessed proficiency</th><th>Role target</th></tr></thead><tbody><tr><td><strong>{p.assessed} · {levels[p.assessed - 1]}</strong></td><td><strong>{p.target} · {levels[p.target - 1]}</strong></td></tr></tbody></table></div>
      <div className={s.evidence}><strong>Assessment evidence</strong><p>{selected === 0 ? "Ava can run an established test procedure, but still asks a lead to set review criteria. The next role target requires independently leading the validation review." : selected === 1 ? "Leo gives effective technical feedback. The next target requires consistent coaching across the team, with observed follow-through." : "Mina independently maintains the quality process and has demonstrated the role's required level in the latest review."}</p></div>
      <p className={s.small}>Scale: 1 Novice · 2 Competent · 3 Proficient · 4 Leading · 5 Expert. Fictional assessments using the public framework's vocabulary.</p>
    </section><aside className={s.card}><p className={s.label}>Development plan</p><h2 className="mt-3">{p.course}</h2><p className={s.muted}>{p.assessed < p.target ? "Use a learning activity and an observed practical review to work toward the role target." : "Optional development beyond the current role target. No gap is recorded in this scenario."}</p><ol className={s.journey}><li>Assign the development activity</li><li>Apply it to a live team exercise</li><li>Reassess with new evidence</li></ol><div className={s.actions}><button className={s.button} disabled={assigned.includes(p.id)} onClick={() => setAssigned([...assigned, p.id])}>{assigned.includes(p.id) ? "Demo plan assigned" : "Assign demo development plan"}</button></div><p className={s.small} role="status">{assigned.includes(p.id) ? `Plan assigned to ${p.name}. Assessed proficiency remains ${p.assessed}; reassessment is still required.` : "This action only updates the local scenario."}</p></aside></div>
    <div className={s.callout}><strong>Learning heritage, expressed as a decision:</strong> the target explains the development action. The development action does not prove readiness.</div>
  </>;
}
function Remuneration() {
  const [increases, setIncreases] = useState<number[]>(TEAM.map(p => p.increase)), [reason, setReason] = useState(""), [submitted, setSubmitted] = useState(false);
  const result = remunerationSummary(increases), exception = result.overBudget || result.overBand.length > 0;
  return <>
    <PageHeading eyebrow="Performance / Remuneration" title="A pay proposal is a decision, not a percentage.">Model a review within the team's salary bands and budget. Any exception needs an explanation before it can be sent for approval.</PageHeading>
    <div className={s.grid}>{[["Review budget", REVIEW_BUDGET], ["Proposed increases", result.cost], ["Remaining budget", result.remaining]].map(([label, value]) => <div key={label} className={s.card}><p className={s.label}>{label}</p><div className={s.stat}>{result.valid ? dollars(Number(value)) : "—"}</div></div>)}</div>
    <div className={`${s.tablewrap} ${s.section}`}><table className={s.table}><thead><tr><th>Person / performance</th><th>Current / band ceiling</th><th>Increase %</th><th>Proposed salary</th><th>Policy check</th></tr></thead><tbody>{result.proposals.map((p, i) => <tr key={p.id}><td><div className={s.name}>{p.name}</div><div className={s.small}>{p.rating}</div></td><td>{dollars(p.salary)}<div className={s.small}>Ceiling {dollars(p.band)}</div></td><td><input className={s.input} type="number" min="0" max="20" step="0.5" aria-label={`${p.name} proposed increase percentage`} aria-invalid={!validIncrease(increases[i])} aria-describedby={!validIncrease(increases[i]) ? `increase-error-${p.id}` : undefined} value={Number.isFinite(increases[i]) ? increases[i] : ""} disabled={submitted} onChange={e => setIncreases(increases.map((x, idx) => idx === i ? e.target.value === "" ? NaN : Number(e.target.value) : x))}/>{!validIncrease(increases[i]) && <p id={`increase-error-${p.id}`} className={s.small}>Use 0–20 in steps of 0.5.</p>}</td><td>{validIncrease(increases[i]) ? dollars(p.nextSalary) : "—"}</td><td><span className={`${s.badge} ${p.nextSalary > p.band ? s.warn : s.good}`}>{!validIncrease(increases[i]) ? "Incomplete" : p.nextSalary > p.band ? "Above band" : "Within band"}</span></td></tr>)}</tbody></table></div>
    <div className={`${s.two} ${s.section}`}><section className={s.card}><h2>Review context</h2><p className={s.muted}>Performance is an input to the decision. Salary bands and the total pool constrain it; a person approves the result.</p><p className={s.small}>Try 8% for Leo to expose a band exception. All salaries, bands, percentages and policies are invented for the demonstration.</p></section><section className={s.card}><h2>{submitted ? "Submitted for demo approval" : !result.valid ? "Complete review inputs" : exception ? "Explain the exception" : "Ready for review"}</h2><p className={s.muted} role="status">{submitted ? "The reviewer now has the proposals and their context. Salaries and payroll have not changed." : !result.valid ? "Enter 0 to 20 in steps of 0.5 for every person." : exception ? `${result.overBand.length} above-band proposal(s). ${result.overBudget ? "The total is also over budget." : "The total remains within budget."}` : "All proposals fit the scenario's budget and salary bands."}</p>
      {exception && <label className={s.field}>Reason for exception<textarea className={s.input} rows={3} value={reason} disabled={submitted} onChange={e => setReason(e.target.value)} placeholder="Explain the proposed exception (at least 10 characters)"/></label>}
      <div className={s.actions}><button className={s.button} disabled={submitted || !canSubmitRemuneration(increases, reason)} onClick={() => setSubmitted(true)}>Submit demo review</button><button className={s.secondary} onClick={() => {setIncreases(TEAM.map(p => p.increase));setReason("");setSubmitted(false);}}>Reset scenario</button></div></section></div>
  </>;
}
function Connections() {
  const [resolved, setResolved] = useState(false), [inspect, setInspect] = useState(false);
  return <>
    <PageHeading eyebrow="HR Core / Payroll connections" title="The handoff needs an owner.">An illustrative provider connection makes mapped-field ownership and a conflicting update visible. ELMO's current payroll proposition includes provider choice and integration controls.</PageHeading>
    <div className={s.two}><section className={s.card}><div className={s.strip}><h2>Payroll provider connection</h2><span className={`${s.badge} ${resolved ? s.good : s.warn}`}>{resolved ? "Conflict reviewed" : "1 conflict requires review"}</span></div><div className={s.tablewrap}><table className={s.table}><thead><tr><th>Mapped field</th><th>Scenario owner</th><th>State</th></tr></thead><tbody><tr><td>Job title</td><td>HR Core</td><td>Aligned</td></tr><tr><td>Employment start date</td><td>HR Core</td><td>Aligned</td></tr><tr><td>Cost centre</td><td>HR Core</td><td><button className={s.link} onClick={() => setInspect(true)}>Review conflict →</button></td></tr><tr><td>Pay run calculation</td><td>Payroll provider</td><td>Separate responsibility</td></tr></tbody></table></div><p className={s.small}>Field ownership here is fictional configuration, not a claim about every ELMO connection.</p></section><section className={s.card}><p className={s.label}>Conflict detail</p><h2 className="mt-3">Ava Nguyen · cost centre</h2>{inspect ? <><div className={s.evidence}><p>HR Core: <strong>Engineering / AU-204</strong><br/>Provider copy: <strong>Operations / AU-110</strong></p><p className={s.small}>Both claim the same effective date. This scenario assigns the field to HR Core.</p></div><div className={s.actions}><button className={s.button} disabled={resolved} onClick={() => setResolved(true)}>{resolved ? "Resolution recorded" : "Use HR-owned value in demo"}</button></div><p className={s.small} role="status">{resolved ? "Audit: manager selected AU-204 using the mapped ownership rule. Provider confirmation remains a separate step; no live sync occurred." : "Review the mapped owner before choosing a value."}</p></> : <p className={s.muted}>Open the conflict to compare both values and their ownership. A green connection indicator alone would not explain this disagreement.</p>}</section></div>
    <div className={s.callout}><strong>Connected does not mean every calculation is native.</strong> The platform earns trust by making the boundary understandable, including what has been resolved and what still needs a receipt.</div>
  </>;
}
