"use client";
import Link from "next/link";
import { useState } from "react";
import { companyHref, type CompanyStudy } from "@/lib/companies";
import { FIND_TALENT_CANDIDATES as TALENT, payrollScenario } from "@/lib/data/study-scenarios";
import { PageHeading, StudyAppShell } from "./shell";
import s from "./study.module.css";
const NAV = [["", "Home"], ["payroll", "Payroll"], ["talent", "Recruitment · Find Talent"], ["people", "People"]] as const;
const money = (n: number) => new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD", maximumFractionDigits: 0 }).format(n);
export function HeroApp({ company, screen }: { company: CompanyStudy; screen: string }) {
  return <StudyAppShell company={company} screen={screen} nav={NAV}>{screen === "" ? <Home/> : screen === "payroll" ? <Payroll/> : screen === "talent" ? <FindTalent/> : <People/>}</StudyAppShell>;
}
function Home() {
  return <>
    <PageHeading eyebrow="Employment operating system" title="Less employment admin. Clearer decisions.">Three places the platform can take work off a small team's hands: preparing pay, finding interested talent and operating employment.</PageHeading>
    <section className={s.hero}><span className={`${s.badge} ${s.warn}`}>Payroll · attention required</span><h2 className="mt-4">The run is prepared. One time entry needs you.</h2><p>Ava's imported overtime does not match the approved timesheet. Inspect the source, correct the draft and then review finalisation.</p><Link className={`${s.button} mt-5`} href={companyHref("employment-hero", "app", "payroll")}>Review pay run →</Link></section>
    <div className={s.grid}><Link className={s.card} href={companyHref("employment-hero", "app", "talent")}><p className={s.label}>Find Talent</p><h2 className="mt-4">Start with people, not a blank pipeline.</h2><p className={s.muted}>Inspect three fictional opt-in profiles against a role, then check their interest.</p><div className={`${s.link} mt-5`}>Explore candidates →</div></Link><Link className={s.card} href={companyHref("employment-hero", "app", "people")}><p className={s.label}>People / HeroForce</p><h2 className="mt-4">Who will run the employment?</h2><p className={s.muted}>Compare direct employment with a HeroForce scenario before choosing an operating model.</p><div className={`${s.link} mt-5`}>Compare responsibilities →</div></Link><section className={s.card}><p className={s.label}>Employee side</p><h2 className="mt-4">EH Work</h2><p className={s.muted}>Pay information, leave and other employee utilities create recurring reasons to return.</p><Link className={`${s.link} mt-5 inline-block`} href={`${companyHref("employment-hero", "backstage", "essays")}#network`}>Why the worker app matters →</Link></section></div>
  </>;
}
function Payroll() {
  const [expanded, setExpanded] = useState(false), [reviewed, setReviewed] = useState(false), [finalised, setFinalised] = useState(false);
  const run = payrollScenario(reviewed);
  return <>
    <PageHeading eyebrow="Payroll / Fortnightly / AU demo" title="Prepare the run. Stop at the exception.">Review one discrepancy between imported hours and an approved timesheet. Earnings use invented scenario rates; this is not an award, tax or super calculation.</PageHeading>
    <div className={s.grid}><div className={s.card}><p className={s.label}>Illustrative gross earnings</p><div className={s.stat}>{money(run.gross)}</div><p className={s.small}>3 fictional people · ordinary + overtime</p></div><div className={s.card}><p className={s.label}>Warnings</p><div className={s.stat}>{run.warnings}</div><p className={s.small}>Configured to pause this demo run</p></div><div className={s.card}><p className={s.label}>Run status</p><div className="mt-5 text-2xl font-semibold" role="status">{finalised ? "Demo finalised" : reviewed ? "Ready for review" : "Review required"}</div><p className={s.small}>{finalised ? "Simulation only · no payment or filing" : "Finalisation remains a separate control"}</p></div></div>
    <div className={`${s.two} ${s.section}`}><div className={s.stack}><div className={s.tablewrap}><table className={s.table}><thead><tr><th>Employee</th><th>Ordinary earnings</th><th>Overtime</th><th>Gross</th></tr></thead><tbody><tr><td className={s.name}>Ava Nguyen</td><td>$3,200</td><td>{money(run.overtimeAmount)}</td><td>{money(3200 + run.overtimeAmount)}</td></tr><tr><td>Leo Martin</td><td>$3,600</td><td>—</td><td>$3,600</td></tr><tr><td>Mina Patel</td><td>$2,800</td><td>—</td><td>$2,800</td></tr></tbody></table></div>
      <section className={s.card}><div className={s.strip}><h2>Ava · overtime discrepancy</h2><span className={`${s.badge} ${reviewed ? s.good : s.warn}`}>{reviewed ? "Reviewed" : "Needs attention"}</span></div><p className={s.muted}>The imported entry contains four hours; the approved timesheet records two. The run pauses because this warning is configured to require review.</p><button className={`${s.link} mt-4`} onClick={() => setExpanded(!expanded)} aria-expanded={expanded}>{expanded ? "Hide timesheet evidence" : "Review timesheet evidence →"}</button>
      {expanded && <div className={s.evidence}><strong>Timesheet MO-AU-0910 · Ava Nguyen</strong><p>Approved overtime: 2 hours<br/>Imported overtime: 4 hours<br/>Scenario overtime rate: $60 / hour</p><p>Use the approved record to reduce draft earnings by $120.</p><div className={s.actions}><button className={s.button} disabled={reviewed || finalised} onClick={() => setReviewed(true)}>{reviewed ? "Demo adjustment recorded" : "Confirm demo adjustment"}</button></div></div>}</section>
    </div><section className={s.card}><p className={s.label}>Pay run actions</p><h2 className="mt-3">Automation with a stop condition</h2><ul className={s.checklist}><li>Prepare ordinary earnings from the scenario</li><li>Import time entries and evaluate warnings</li><li>Pause on an unreviewed discrepancy</li><li>Require final review before completion</li></ul><div className={s.actions}><button className={s.button} disabled={!run.canFinalise || finalised} onClick={() => setFinalised(true)}>Finalise demo run</button><button className={s.secondary} onClick={() => {setReviewed(false);setFinalised(false);setExpanded(false);}}>Reset run</button></div><p className={s.small} role="status">{finalised ? "Demo run finalised. No bank transaction, statutory filing or live employee update occurred." : reviewed ? "The warning is resolved. Review the corrected earnings, then finalise the demo run." : "Resolve the warning before finalising. Readiness and completion are separate states."}</p></section></div>
    <div className={s.callout}><strong>What the acquisitions explain:</strong> KeyPay brought the engine and partner channel; Employment Innovations brought operational expertise. The next promise is to prepare more of the work and make the exceptions understandable.</div>
  </>;
}
function FindTalent() {
  const [filter, setFilter] = useState("role"), [selected, setSelected] = useState(0), [saved, setSaved] = useState<string[]>([]), [invited, setInvited] = useState<string[]>([]);
  const visible = filter === "melbourne" ? TALENT.filter(p => p.location === "Melbourne") : TALENT; const person = TALENT[selected];
  return <>
    <PageHeading eyebrow="Recruitment / Find Talent" title="A match is the beginning of a conversation.">Search the fictional opt-in pool against an optical engineering role. Inspect the evidence, save a profile and simulate checking their interest.</PageHeading>
    <div className={s.tabs} aria-label="Talent search scope"><button aria-pressed={filter === "role"} onClick={() => setFilter("role")}>Search by job · Optical Systems Engineer</button><button aria-pressed={filter === "melbourne"} onClick={() => {setFilter("melbourne");setSelected(0);}}>Melbourne only</button></div>
    <div className={s.strip}><span className={s.badge}>{visible.length} demo candidates · {saved.length} saved</span><span className={s.small}>Opted in to job opportunities · contact through the platform</span></div>
    <div className={s.two}><section className={s.stack}>{visible.map(p => <button key={p.id} className={`${s.card} text-left`} style={{ borderColor: p.id === person.id ? "#6131AD" : undefined }} aria-pressed={p.id === person.id} onClick={() => setSelected(TALENT.findIndex(x => x.id === p.id))}><div className={s.strip}><h2>{p.name}</h2><span className={s.badge}>{p.location}</span></div><p>{p.role}</p><p className={s.muted}>{p.fit}</p><p className={s.small}>{invited.includes(p.id) ? "Checking interest · demo invitation queued" : "Open the profile to inspect evidence and one unresolved question"}</p></button>)}</section>
      <aside className={s.card}><p className={s.label}>Candidate profile</p><h2 className="mt-3">{person.name}</h2><p className={s.muted}>Criteria supported: {person.fit}</p><div className={s.evidence}>{person.excerpt}<div className={s.small}>{person.source}</div></div><p><strong>Still to verify:</strong> {person.gap}</p><p className={s.small}>This fictional candidate opted in to discovery. Contact stays within the platform; willingness to apply is not yet established.</p><div className={s.actions}><button className={s.secondary} disabled={saved.includes(person.id)} onClick={() => setSaved([...saved, person.id])}>{saved.includes(person.id) ? "Saved to demo talent pool" : "Save to talent pool"}</button><button className={s.button} disabled={invited.includes(person.id)} onClick={() => setInvited([...invited, person.id])}>{invited.includes(person.id) ? "Checking interest" : "Simulate invitation"}</button></div><p className={s.small} role="status">{invited.includes(person.id) ? "Demo invitation queued. No message sent. A candidate response would be a separate event." : "No invitation has been simulated for this candidate."}</p></aside></div>
    <div className={s.callout}><strong>The network advantage:</strong> discovery starts with participating people. The test is interested, suitable applicants—not an AI score or a database count.</div>
  </>;
}
function People() {
  const [model, setModel] = useState<"direct" | "heroforce">("direct"), [saved, setSaved] = useState<"direct" | "heroforce" | null>(null);
  return <>
    <PageHeading eyebrow="People / Proposed role" title="Choose who operates the employment.">Compare responsibility for a proposed Field Service Technician. This only saves a scenario; it cannot create an employment or service agreement.</PageHeading>
    <div className={s.two}><section className={s.card}><p className={s.label}>Meridian Optics · new AU role</p><h2 className="mt-3">Field Service Technician</h2><p className={s.muted}>Melbourne · proposed hire · no worker appointed</p><div className={s.tabs} aria-label="Employment model"><button aria-pressed={model === "direct"} onClick={() => setModel("direct")}>Direct employment</button><button aria-pressed={model === "heroforce"} onClick={() => setModel("heroforce")}>HeroForce</button></div><p>{model === "direct" ? "Meridian remains the legal employer and uses software or services to support its employment administration." : "Employment Hero acts as legal employer under the HeroForce service model. Meridian still chooses the hire and directs the daily work."}</p><div className={s.actions}><button className={s.button} disabled={saved === model} onClick={() => setSaved(model)}>{saved === model ? "Scenario saved" : "Save proposed model in demo"}</button></div><p className={s.small} role="status">{saved ? `Saved scenario: ${saved === "direct" ? "Direct employment" : "HeroForce"}. No contract, engagement or worker change.` : "Review the responsibility map before saving the scenario."}</p></section>
      <section className={s.card}><p className={s.label}>Responsibility map</p><h2 className="mt-3">{model === "direct" ? "Meridian is the employer" : "Employment Hero is the employer"}</h2><div className={`${s.tablewrap} ${s.section}`}><table className={s.table}><thead><tr><th>Responsibility</th><th>Proposed owner</th></tr></thead><tbody>{[
        ["Select the hire", "Meridian Optics"], ["Direct daily work", "Meridian Optics"], ["Legal employer", model === "direct" ? "Meridian Optics" : "Employment Hero / HeroForce"], ["Employment contracts", model === "direct" ? "Meridian's employment operation" : "HeroForce service"], ["Payroll administration", model === "direct" ? "Meridian or its chosen service" : "HeroForce service"],
      ].map(([responsibility, owner]) => <tr key={responsibility}><td>{responsibility}</td><td>{owner}</td></tr>)}</tbody></table></div><p className={s.small}>Conceptual comparison from the AU HeroForce product description. Actual scope depends on the service agreement, eligibility and region.</p></section></div>
    <div className={s.callout}><strong>The current company trajectory:</strong> an employment operating system can become a provider of employment operations. The important change is who carries the work and responsibility.</div>
  </>;
}
