"use client";
import { useState } from "react";
import type { CompanyStudy } from "@/lib/companies";
import { AUDIO_SCRIPTS, type Take, takeKey, takeCurrent, dubInitial, dubCanAccept, AGENT_TESTS, agentTestResults, canReleaseAgent } from "@/lib/data/ai-scenarios";
import audioData from "@/lib/data/ai-audio.json";
import { AIFrame, SceneTitle, Insight } from "./frame";
import s from "./studies.module.css";

const TABS=[["studio","ElevenCreative"],["dubbing","Dubbing"],["agents","ElevenAgents"]] as const;
const AUDIO="/audio/company-studies/";
const CLIPS=audioData as Record<string,{duration:number;peaks:number[]}>;
export function ElevenLabsApp({company,screen}:{company:CompanyStudy;screen:string}) {
  const current=screen||"studio";
  return <AIFrame company={company} screen={current} tabs={TABS}>{current==="studio"?<Studio/>:current==="dubbing"?<Dubbing/>:<Agents/>}</AIFrame>;
}

function Studio() {
  const [settings,setSettings]=useState<Take>({script:"original",pace:"measured"}),[rendered,setRendered]=useState("original-measured"),[history,setHistory]=useState<string[]>(["original-measured"]);
  const current=takeCurrent(settings,rendered),meta=CLIPS[rendered];
  const render=()=>{const key=takeKey(settings);setRendered(key);setHistory([...new Set([key,...history])]);};
  return <><SceneTitle product="ElevenCreative · Studio / Meridian welcome" title="Direct the take. Keep the script and audio together." detail="Compare two original scripts and two delivery samples. Changing either makes the previous take stale until you render the selected demo version."/>
    <div className={s.cols}><section className={s.card}><div className={s.row}><h2>Welcome sequence</h2><span className={`${s.badge} ${current?s.good:s.warn}`}>{current?"Current take":"Take needs updating"}</span></div>
      <div className={s.timeline}><div className={s.ruler}><span>0:00</span><span>{(meta.duration/2).toFixed(1)}s</span><span>{meta.duration}s</span></div><div className={s.track}><span>Narration</span><div className={s.clip}>Welcome · {rendered}<div role="img" aria-label={`Audio waveform for ${rendered}`}>{meta.peaks.map((peak,i)=><i key={i} style={{height:Math.max(3,peak*.36)}}/>)}</div></div></div></div>
      <audio key={rendered} className={s.audio} controls preload="metadata" aria-label="Play illustrative narration"><source src={`${AUDIO}${rendered}.mp3`} type="audio/mpeg"/>Your browser does not support audio playback.</audio>
      <p className={s.small}>Original illustrative narration using generic synthetic voices. These clips are not ElevenLabs model samples; they demonstrate the production workflow.</p>
      <div className={`${s.document} mt-5`}><p className={s.fileTitle}>Selected script · {settings.script}</p><p>{AUDIO_SCRIPTS[settings.script]}</p></div>
      <div className={s.actions}>{current?<a className={s.button} href={`${AUDIO}${rendered}.mp3`} download={`Meridian-${rendered}.mp3`}>Download current demo take ↓</a>:<button className={s.secondary} disabled>Render the selected version before export</button>}</div><p className={s.small} role="status">{current?"Script, delivery and exported audio refer to the same take.":"Playback still refers to the earlier take. The selected script or delivery has changed."}</p>
    </section><section className={s.card}><h2>Selected clip</h2><label className={s.label}>Script version<select className={s.input} value={settings.script} onChange={e=>setSettings({...settings,script:e.target.value as Take["script"]})}><option value="original">Original · open the workspace</option><option value="revised">Revised · start with assigned requests</option></select></label><label className={s.label}>Demo delivery<select className={s.input} value={settings.pace} onChange={e=>setSettings({...settings,pace:e.target.value as Take["pace"]})}><option value="measured">Measured</option><option value="brisk">Brisk</option></select></label><p className={s.small}>Four pre-made takes let you hear a real change without calling a live generation service.</p><button className={`${s.button} mt-4`} disabled={current} onClick={render}>Render selected demo take</button>
      <h2 className="mt-7">Generation history</h2><ul className={s.checks}>{history.map(key=><li key={key}><span>{key}<br/><small>{CLIPS[key].duration}s</small></span><button className={s.link} onClick={()=>{const [script,pace]=key.split("-");setSettings({script:script as Take["script"],pace:pace as Take["pace"]});setRendered(key);}}>Restore take</button></li>)}</ul>
    </section></div><Insight><strong>A good voice is the entry point; revision is the recurring job.</strong> Studio makes script, performance and prior takes part of a project. The surrounding production workflow earns its place when another take is needed.</Insight>
  </>;
}

const TRANSLATIONS={es:{label:"Spanish",text:"Bienvenido a Meridian. Tu equipo ya puede revisar todas las solicitudes en un solo lugar. Abre el espacio de trabajo para ver qué necesita tu atención."},pl:{label:"Polish",text:"Witaj w Meridian. Twój zespół może teraz przeglądać wszystkie zgłoszenia w jednym miejscu. Otwórz obszar roboczy, aby sprawdzić, co wymaga twojej uwagi."}};
function Dubbing() {
  const [state,setState]=useState(dubInitial()),[issue,setIssue]=useState("");
  const target=TRANSLATIONS[state.language],accepted=state.verdict==="accepted";
  return <><SceneTitle product="ElevenCreative · Automatic Dubbing v2 / Alpha" title="The message must survive the language change." detail="Create a fixed demo language version, compare the source and target, and record a handoff decision. This is a review scene around automatic dubbing."/>
    <div className={s.row}><label className={s.label}>Target language<select className={s.input} value={state.language} onChange={e=>{setState(dubInitial(e.target.value as "es"|"pl"));setIssue("");}}><option value="es">Spanish</option><option value="pl">Polish</option></select></label><button className={s.button} disabled={state.generated} onClick={()=>setState({...state,generated:true})}>Create demo language version</button><span className={`${s.badge} ${accepted?s.good:state.verdict==="issue"?s.warn:""}`}>{accepted?"Ready for handoff":state.verdict==="issue"?"Needs language review":state.generated?"Awaiting review":"No target version"}</span></div>
    <div className={s.cols}><section className={s.card}><h2>Original · English</h2><p>{AUDIO_SCRIPTS.original}</p><audio className={s.audio} controls preload="metadata" aria-label="Original English narration"><source src={`${AUDIO}original-measured.mp3`} type="audio/mpeg"/></audio><label className={s.label}><span><input type="checkbox" checked={state.sourceReviewed} disabled={accepted} onChange={e=>setState({...state,sourceReviewed:e.target.checked})}/> I reviewed the source meaning and timing</span></label><p className={s.small}>Source duration: {CLIPS["original-measured"].duration}s. The transcript and duration provide an alternative to audio review.</p></section>
    <section className={s.card}><h2>Target · {target.label}</h2>{state.generated?<><p lang={state.language}>{target.text}</p><audio key={state.language} className={s.audio} controls preload="metadata" aria-label={`${target.label} illustrative narration`}><source src={`${AUDIO}dub-${state.language}.mp3`} type="audio/mpeg"/></audio><p className={s.small}>Target duration: {CLIPS[`dub-${state.language}`].duration}s. Fixed illustrative sample; not an ElevenLabs dubbing output.</p><label className={s.label}><span><input type="checkbox" checked={state.targetReviewed} disabled={accepted} onChange={e=>setState({...state,targetReviewed:e.target.checked})}/> I reviewed the target meaning and timing</span></label></>:<p className={s.muted}>Create the selected language version to compare it with the source.</p>}</section></div>
    <section className={`${s.card} mt-5`}><h2>Language handoff</h2><p>Check that “needs your attention” has not become a promise that every request is urgent. Fluent delivery alone cannot resolve that question.</p><label className={s.label}>Review note<input className={s.input} value={issue} disabled={accepted||state.verdict==="issue"} onChange={e=>setIssue(e.target.value)} placeholder="Describe a meaning or timing issue, if one needs a reviewer"/></label><div className={s.actions}><button className={s.secondary} disabled={!state.generated||issue.trim().length<8||accepted||state.verdict==="issue"} onClick={()=>setState({...state,verdict:"issue"})}>Flag for language review</button><button className={s.button} disabled={!dubCanAccept(state)||accepted} onClick={()=>setState({...state,verdict:"accepted"})}>Accept demo version for handoff</button></div><p className={s.small} role="status">{accepted?"This selected version has a recorded review. A different language starts a new review.":state.verdict==="issue"?`Held for a language reviewer: ${issue}. This scene does not resolve or edit the translation.`:"Acceptance requires both source and target review. A flagged version stays on hold."}</p><button className={`${s.link} mt-4`} onClick={()=>{setState(dubInitial(state.language));setIssue("");}}>Reset this language review</button>
    </section><Insight><strong>Generation and finishing have different maturity boundaries.</strong> Current v2 dubbing is automatic and labelled Alpha. Current v2 has no in-app editor. The editable v1 Dubbing Studio is in maintenance mode; Enterprise API refinement and professional finishing are separate routes.</Insight>
  </>;
}

function Agents() {
  const [tab,setTab]=useState("agent"),[repair,setRepair]=useState(false),[tested,setTested]=useState<boolean|null>(null),[reviewed,setReviewed]=useState(false),[released,setReleased]=useState(false);
  const valid=canReleaseAgent(repair,tested,reviewed),results=agentTestResults(repair);
  return <><SceneTitle product="ElevenAgents · Meridian reservations" title="The caller changed the date. Did the tool call change?" detail="A believable conversation is not enough. Test the corrected intent before a candidate branch receives traffic."/>
    <div className={s.row}><div className={s.tabs}>{[["agent","Agent"],["tests","Tests"],["branches","Branches & traffic"]].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div><span className={s.badge}>Candidate · latest-intent</span></div>
    {tab==="agent"&&<div className={s.cols}><section className={s.card}><h2>Conversation fixture</h2><div className={s.conversation}><div className={s.bubble}><small>Caller</small>Move booking M-208 to 14 October.</div><div className={s.bubble}><small>Agent</small>I’ll check that date for you—</div><div className={s.bubble}><small>Caller · interruption</small>Actually, make that 16 October.</div><div className={s.bubble}><small>Expected response</small>16 October for booking M-208. Let me check availability before making any change.</div></div><p className={s.small}>A scripted text fixture exposes intent handling. It does not measure real acoustic recognition, voice quality or latency.</p></section>
    <section className={s.card}><h2>Agent instructions</h2><p>Check availability before proposing a reservation change. If the provider fails, transfer to a person.</p><label className={s.label}><span><input type="checkbox" checked={repair} disabled={released} onChange={e=>{setRepair(e.target.checked);setTested(null);setReviewed(false);}}/> Reconfirm the latest corrected date before calling the tool</span></label><p className={s.fileTitle}>Proposed tool · check_availability</p><pre className={s.code}>{JSON.stringify({booking_reference:"M-208",arrival_date:repair?"2026-10-16":"2026-10-14"},null,2)}</pre><label className={s.label}><span><input type="checkbox" checked={reviewed} disabled={released} onChange={e=>setReviewed(e.target.checked)}/> I checked the proposed tool arguments against the caller’s correction</span></label><button className={s.button} onClick={()=>setTab("tests")}>Open the test suite →</button></section></div>}
    {tab==="tests"&&<section className={s.card}><div className={s.row}><h2>Tests · candidate branch</h2><button className={s.button} disabled={released} onClick={()=>setTested(repair)}>Run demo tests</button></div><p className={s.muted}>A tool-call check, a missing-information scenario and a provider-error scenario. Results below are deterministic fixtures, not measured model performance.</p><ul className={s.checks}>{AGENT_TESTS.map((test,i)=><li key={test}><span>{test}<br/><small>{i===0?"Tool Call":i===1?"Next Reply":"Simulation"}</small></span><span className={`${s.badge} ${tested===null?"":results[i]?s.good:s.bad}`}>{tested===null?"Not run":results[i]?"Pass":"Fail"}</span></li>)}</ul><p role="status">{tested===false?"The first request's date survived the interruption. Revise the instruction before rollout.":tested===true?"The three scripted cases pass. Production performance remains unmeasured.":"Changing the instruction invalidates earlier results."}</p><div className={s.actions}><button className={s.secondary} onClick={()=>setTab("agent")}>Inspect agent & tool arguments</button><button className={s.button} onClick={()=>setTab("branches")}>Review traffic →</button></div></section>}
    {tab==="branches"&&<section className={s.card}><div className={s.row}><h2>Traffic allocation</h2><span className={`${s.badge} ${released?s.good:""}`}>{released?"Demo experiment running":"Candidate receives no traffic"}</span></div><div className={s.bar} aria-label={`Main ${released?90:100} percent, candidate ${released?10:0} percent`}><span style={{width:released?"90%":"100%"}}/><span style={{width:released?"10%":"0%",background:"#a3baff"}}/></div><p>Main: {released?90:100}% · latest-intent: {released?10:0}%</p><p className={s.muted}>A small experiment limits exposure. Compare completion, transfers and failures on real conversations before increasing traffic.</p><div className={s.actions}><button className={s.button} disabled={!valid||released} onClick={()=>setReleased(true)}>Start demo 10% experiment</button><button className={s.secondary} disabled={!released} onClick={()=>setReleased(false)}>Return all demo traffic to main</button><button className={s.link} onClick={()=>setTab("agent")}>Review agent</button></div><p className={s.small} role="status">{released?"Simulated allocation only. No live calls or customer outcomes have been measured.":"Requires the corrected instruction, a fresh passing test run and inspected tool arguments."}</p></section>}
    <Insight><strong>The useful unit is a resolved interaction.</strong> ElevenLabs controls more of how a conversation behaves while letting the reasoning model remain separable. Tests and traffic controls address the operational burden beyond a convincing voice.</Insight>
  </>;
}
