"use client";
import { useReducer, useState } from "react";
import type { CompanyStudy } from "@/lib/companies";
import { LAUNCH_SOURCES, launchReady, patchInitial, patchReducer, patchResults, patchBefore, PATCH_TESTS, INITIAL_TOOL, toolReducer } from "@/lib/data/ai-scenarios";
import { AIFrame, SceneTitle, Insight } from "./frame";
import s from "./studies.module.css";

const TABS = [["work", "ChatGPT Work"], ["codex", "Codex"], ["responses", "Responses API"]] as const;
export function OpenAIApp({ company, screen }: { company: CompanyStudy; screen: string }) {
  const current=screen||"work";
  return <AIFrame company={company} screen={current} tabs={TABS}>{current==="work"?<Work/>:current==="codex"?<Codex/>:<Responses/>}</AIFrame>;
}

function Work() {
  const [nav,setNav]=useState("sources"),[source,setSource]=useState<keyof typeof LAUNCH_SOURCES>("brief"),[inspected,setInspected]=useState<string[]>(["brief"]),[scope,setScope]=useState("all"),[revised,setRevised]=useState(false);
  const ready=launchReady(inspected,scope);
  const inspect=(id:keyof typeof LAUNCH_SOURCES)=>{setSource(id);setInspected([...new Set([...inspected,id])]);};
  const artifact=revised?"# Harbour launch decision\n\nScope: Australia and New Zealand.\nTarget: 15 October 2026.\n\nEvidence: Signed scope governs the region/date decision. Support readiness confirms ANZ coverage; other regions remain unconfirmed. The working launch brief is superseded.\n\nOpen decision: launch-owner sign-off before release. This is a fictional planning artifact, not authorisation to launch.":"# Harbour launch decision — unreviewed draft\n\nProposed launch: five regions, 1 October.\n\nBasis: working launch brief. Signed scope and support readiness have not yet been reconciled.";
  return <><SceneTitle product="ChatGPT Work · Harbour launch project" title="Turn the launch context into a decision document." detail="A polished first draft has picked the wrong scope. Inspect the project sources and carry the correction into the work product."/>
    <div className={s.workbench}><aside className={s.rail}><h2>Harbour launch</h2><div className={s.tabs}><button aria-pressed={nav==="chats"} onClick={()=>setNav("chats")}>Chats</button><button aria-pressed={nav==="sources"} onClick={()=>setNav("sources")}>Sources</button></div>
      {nav==="sources"?<>{Object.entries(LAUNCH_SOURCES).map(([id,file])=><button key={id} aria-pressed={source===id} onClick={()=>inspect(id as keyof typeof LAUNCH_SOURCES)}>{file.title} {inspected.includes(id)?"✓":""}</button>)}<p>Project instructions<br/>Use signed scope over working notes. Surface decisions that still need an owner.</p></>:<><button aria-pressed>Launch decision · current task</button><p>Related work can share project context. Access still depends on the sources actually available to this task.</p><button className={s.link} onClick={()=>setNav("sources")}>Review the project sources →</button></>}
    </aside><section className={s.centre}><div className={s.prompt}>“Prepare the launch decision document. Flag anything that prevents us from using it.”</div><h2>{revised?"The work product now follows the signed scope.":"There is a source conflict to resolve."}</h2><p className={s.muted}>The first draft followed the older working brief. Inspect the signed scope and support readiness before revising it.</p>
      <div className={`${s.document} mt-5`}><p className={s.fileTitle}>{LAUNCH_SOURCES[source].title} · attached fictional source</p><p>{LAUNCH_SOURCES[source].text}</p></div>
      <label className={s.label}>Scope to use<select className={s.input} value={scope} disabled={revised} onChange={e=>setScope(e.target.value)}><option value="all">Five regions · 1 October</option><option value="anz">Australia & New Zealand · 15 October</option></select></label>
      <button className={s.button} disabled={!ready||revised} onClick={()=>setRevised(true)}>Revise the demo work product</button><p className={s.small} role="status">{revised?"Scope corrected; launch-owner approval remains open.":"Review the signed scope and support note, then choose the supported scope."}</p>
    </section><section className={s.preview}><div className={s.row}><h2>Launch decision.md</h2><span className={`${s.badge} ${revised?s.good:s.warn}`}>{revised?"Sources reconciled":"Unreviewed draft"}</span></div><article className={`${s.document} mt-5`}><p className={s.fileTitle}>Work product · {revised?"revision 2":"revision 1"}</p><h3>{revised?"An ANZ launch, with one decision still open.":"Five regions on 1 October?"}</h3><p>{revised?"Australia and New Zealand are in scope for 15 October. Support coverage is staffed for these markets.":"The working brief suggests five regions on 1 October. This conclusion has not yet been checked against the signed scope."}</p><p><strong>{revised?"Decision needed:":"Review needed:"}</strong> {revised?"The launch owner must sign off before release. The document itself does not authorise the launch.":"Reconcile the signed scope and readiness evidence before this draft is used."}</p>{revised&&<p className={s.small}>Sources: Signed scope.txt; Support readiness.md. Launch brief.md was superseded.</p>}</article>
      <div className={s.actions}>{revised?<a className={s.button} download="Harbour-launch-decision.md" href={`data:text/markdown;charset=utf-8,${encodeURIComponent(artifact)}`}>Download reviewed draft ↓</a>:<button className={s.secondary} disabled>Resolve sources before download</button>}</div>
    </section></div><Insight><strong>The front door has to lead somewhere.</strong> ChatGPT’s familiar starting point becomes more valuable when context survives into a usable artifact—and a correction reaches the artifact, not only the conversation beside it.</Insight>
  </>;
}

function Codex() {
  const [state,dispatch]=useReducer(patchReducer,patchInitial(true)),[view,setView]=useState("branch");
  const visible=view==="staged"?state.accepted:view==="unstaged"?!state.accepted:true;
  const results=patchResults(state.revision);
  return <><SceneTitle product="Codex · worktree / meridian-api" title="Delegate the attempt. Inspect what changed." detail="The same retry task, isolated in a worktree. Review the change and its tests before staging it; staging does not publish anything."/>
    <div className={s.workbench}><aside className={s.rail}><h2>Meridian API</h2><button aria-pressed>Bound timeout retries</button><p>Environment<br/>Git worktree</p><p>Branch<br/>demo/retry-timeout</p><p>Task boundary<br/>request.ts + focused tests.<br/>No deployment access in this scene.</p><p>Branch compares with the base. Last turn shows the latest revision. Staged and Unstaged reflect local acceptance.</p></aside>
    <section className={s.centre}><div className={s.prompt}>“Retry a transient timeout once. Preserve successful results. Stop if the second attempt also fails.”</div><div className={s.event}><span className={s.step}>01</span><div><strong>Isolated attempt prepared</strong><span>Repository context and a dedicated worktree.</span></div></div><div className={s.event}><span className={s.step}>02</span><div><strong>Patch v{state.revision} is available for review</strong><span>{state.revision===1?"The first attempt retries without a limit.":"The revision bounds the retry and preserves the final error."}</span></div></div>
      <button className={`${s.button} mt-5`} disabled={state.accepted} onClick={()=>dispatch({type:"test"})}>Run the demo checks</button>
      {state.tested===state.revision&&<ul className={s.checks}>{PATCH_TESTS.map((test,i)=><li key={test}>{test}<span className={`${s.badge} ${results[i]?s.good:s.bad}`}>{results[i]?"Pass":"Fail"}</span></li>)}</ul>}
      {state.tested===1&&state.revision===1&&<><p>The repeated-timeout case fails. More generated code has not yet produced an acceptable change.</p><button className={`${s.secondary} mt-4`} onClick={()=>dispatch({type:"revise"})}>Request a bounded retry</button></>}
      <p className={s.small} role="status">{state.accepted?"Change staged in the simulation. Nothing committed, pushed or deployed.":state.revision===2&&state.tested!==2?"Revision 2 needs a fresh test run and review.":"The reviewer, the diff and the test evidence are part of this task."}</p>
    </section><section className={s.preview}><div className={s.row}><h2>Review</h2><span className={s.badge}>{state.accepted?"1 file staged":"1 file changed"}</span></div><div className={s.tabs}>{[["branch","Branch"],["last","Last turn"],["staged","Staged"],["unstaged","Unstaged"]].map(([id,label])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}>{label}</button>)}</div>
      {visible?<><p className={s.fileTitle}>request.ts · v{state.revision}</p><div className={s.diff}><p className={s.minus}>− {patchBefore(state.revision,view)}</p><p className={s.plus}>+ {state.revision===1?'while (true) {\n+   try { return await sendRequest(); }\n+   catch (e) { if (!isTimeout(e)) throw e; }\n+ }':'for (let attempt = 0; attempt < 2; attempt++) {\n+   try { return await sendRequest(); }\n+   catch (e) {\n+     if (!isTimeout(e) || attempt === 1) throw e;\n+   }\n+ }'}</p></div></>:<p className={s.muted}>No {view} changes in this scenario.</p>}
      <div className={s.actions}><button className={s.secondary} disabled={!visible||state.inspected===state.revision||state.accepted} onClick={()=>dispatch({type:"inspect"})}>Mark current diff reviewed</button><button className={s.button} disabled={!visible||state.tested!==2||state.inspected!==2||state.accepted} onClick={()=>{dispatch({type:"accept"});setView("staged");}}>Stage demo hunk</button></div><p className={s.small}>A worktree separates attempts. It does not prove the change is correct. These tests and changes are scripted fixtures.</p>
    </section></div><Insight><strong>The environment is part of the product.</strong> A model’s proposed patch becomes useful through the repository, execution feedback and an inspectable change. The acquisition trajectory around developer tools and persistent environments addresses that surrounding work.</Insight>
  </>;
}

function Responses() {
  const [state,dispatch]=useReducer(toolReducer,INITIAL_TOOL);
  const argumentsJson={account_id:"MER-104",amount_minor:2400,currency:"AUD",reason:"Duplicate service charge",idempotency_key:"demo-refund-104"};
  return <><SceneTitle product="OpenAI API · Responses inspector" title="Prepare a refund draft. Do not refund the customer." detail="Inspect a configured MCP interaction: tool discovery, an approval request, the application’s decision, and a separate call result."/>
    <div className={s.workbench}><aside className={s.rail}><h2>Tools</h2><p>MCP server<br/>meridian_support</p><pre className={s.code}>{'allowed_tools:\n ["create_refund_draft"]\n\nrequire_approval:\n "always"'}</pre><p>Allowed scope: prepare a draft.<br/>Excluded: issue a payment.</p><p>This is an illustrative inspector built around documented API events, not a reproduction of the OpenAI dashboard.</p></aside>
    <section className={s.centre}><h2>Exchange events</h2><div className={s.event}><span className={s.step}>01</span><div><strong>mcp_list_tools</strong><span>create_refund_draft is available.</span></div></div><div className={s.event}><span className={s.step}>02</span><div><strong>mcp_approval_request</strong><span>Approve the exact proposed draft operation.</span></div></div>
      {state.phase!=="proposal"&&<div className={s.event}><span className={s.step}>03</span><div><strong>mcp_approval_response</strong><span>approve: {state.phase==="denied"?"false":"true"} · supplied by the application</span></div></div>}
      {["complete","failed"].includes(state.phase)&&<div className={s.event}><span className={s.step}>04</span><div><strong>mcp_call</strong><span>{state.phase==="complete"?"output: draft_id DRAFT-204":"error: request rejected before draft creation"}</span></div></div>}
      <div className={`${s.document} mt-5`}><p className={s.fileTitle}>What is established</p><p role="status">{state.phase==="proposal"?"The model proposed an operation. No authority has been granted.":state.phase==="approved"?"The application approved the call. No tool result has returned.":state.phase==="denied"?"The application denied the request. No draft was created.":state.phase==="failed"?"The provider rejected the call before execution. There is no draft receipt.":"The provider returned draft DRAFT-204. The draft exists in the simulation; no money has been refunded."}</p></div>
    </section><section className={s.preview}><h2>create_refund_draft</h2><pre className={s.code}>{JSON.stringify(argumentsJson,null,2)}</pre><p>AUD 24.00 · Meridian account MER-104. The operation prepares a reviewable draft only.</p>
      {state.phase==="proposal"&&<div className={s.actions}><button className={s.secondary} disabled={state.inspected} onClick={()=>dispatch({type:"inspect"})}>Inspect account, amount & scope</button><button className={s.button} disabled={!state.inspected} onClick={()=>dispatch({type:"approve"})}>Approve demo call</button><button className={s.secondary} onClick={()=>dispatch({type:"deny"})}>Deny</button></div>}
      {state.phase==="approved"&&<div className={s.actions}><button className={s.button} onClick={()=>dispatch({type:"result",success:true})}>Simulate returned draft</button><button className={s.secondary} onClick={()=>dispatch({type:"result",success:false})}>Simulate provider rejection</button></div>}
      {state.phase==="failed"&&<p className={s.small}>This fixture has an explicit rejection before execution. An uncertain timeout would require reconciliation before retrying a side effect.</p>}
      {state.phase==="complete"&&<pre className={s.code}>{JSON.stringify({draft_id:state.receipt,status:"awaiting_review",refunded:false},null,2)}</pre>}
      <button className={`${s.link} mt-5`} onClick={()=>dispatch({type:"reset"})}>Reset exchange</button>
    </section></div><Insight><strong>Intelligence needs an execution contract.</strong> The API can carry structured proposals and receipts through another company’s product. The builder still owns scope, recovery and the difference between a draft and a completed financial action.</Insight>
  </>;
}
