import Link from 'next/link';
import { ILayers } from '@/components/icons';
const doors=[
 ['/', 'Software landscape', 'Find a company, compare its position and follow its products or partner practices.'],
 ['/companies/rippling/backstage', 'Company studies', 'Explore a company’s product logic, strategy, leadership and acquisitions. App scenarios make the choices tangible.'],
 ['/atlas/servicenow', 'Delivery ecosystems', 'Find the people, local capabilities and career lineages behind Workday and ServiceNow practices in ANZ.'],
 ['/earth', 'Global View', 'See how markets, manufacturing, infrastructure and delivery depend on each other.'],
 ['/technology', 'Technology', 'Learn the turning points, physical limits and possible futures. Try the labs and follow the best external explorers.'],
 ['/decisions', 'Decisions', 'Connect innovation and adoption to practical choices for technology buyers and operators.'],
];
export const metadata={title:'About Compound',description:'An open, maintained field guide to technology, companies and the people who make it work.'};
export default function About(){return <div className="min-h-screen bg-[#F7F6F1] text-[#17282C]"><header className="mx-auto flex max-w-[1000px] justify-between px-6 py-6"><Link href="/" className="flex items-center gap-2 font-semibold"><span className="grid h-8 w-8 place-items-center rounded-lg bg-ink text-signal"><ILayers className="h-4 w-4"/></span>Compound</Link><a href="https://github.com/EthDawg/compound" className="text-xs underline underline-offset-4">GitHub ↗</a></header><main className="mx-auto max-w-[1000px] px-6 pb-16"><p className="mt-8 text-[10px] font-bold uppercase tracking-[.2em] text-[#54716B]">An open field guide</p><h1 className="font-serif-display mt-4 max-w-3xl text-4xl leading-tight sm:text-5xl">Understand the technology.<br/>See the company.<br/>Meet the people behind it.</h1><p className="mt-6 max-w-2xl text-base leading-relaxed text-ink-500">Compound connects the product you can see with the strategy, delivery teams, market dependencies and technical ideas underneath it. Start anywhere, then follow the connections.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{doors.map(([href,title,body])=><Link key={href} href={href} className="rounded-xl border border-black/10 bg-white p-5 hover:bg-[#EFF2E8]"><h2 className="text-lg font-semibold">{title} →</h2><p className="mt-2 text-sm leading-relaxed text-ink-500">{body}</p></Link>)}</div><section className="mt-10 grid gap-8 border-t border-black/10 pt-8 md:grid-cols-2"><div><h2 className="font-serif-display text-2xl">One maintained edition.</h2><p className="mt-3 text-sm leading-relaxed text-ink-500">Use the <a href="https://compound-snowy-pi.vercel.app" className="underline underline-offset-4">hosted app</a> without installing anything or creating an account. Ethan Harley maintains the shared edition; research corrections, design improvements and code contributions are welcome.</p><p className="mt-3 text-sm"><a href="https://github.com/EthDawg/compound/issues/new" className="underline underline-offset-4">Suggest a correction ↗</a></p></div><div><h2 className="font-serif-display text-2xl">Know what you’re reading.</h2><p className="mt-3 text-sm leading-relaxed text-ink-500">Sources sit beside facts. Company claims, Compound’s interpretation, calculated examples and conditional futures stay distinguishable. A gap in the research does not establish an absence of capability.</p><p className="mt-3 text-sm leading-relaxed text-ink-500">App scenarios use fictional records. They illustrate product logic and do not connect to real company systems. Compound is independent and unaffiliated with the organisations studied.</p></div></section></main></div>;}
