"use client";

import Link from "next/link";
import { useReducer, useState } from "react";
import { type CompanyStudy, companyHref } from "@/lib/companies";
import { CompoundBar } from "@/components/compound-bar";
import { useXRay } from "@/components/xray-provider";
import { INITIAL_INCIDENT, incidentReducer, INITIAL_JOURNEY, journeyReducer, journeyComplete, INITIAL_GOVERNANCE, governanceReducer } from "@/lib/data/servicenow-scenarios";
import s from "./servicenow.module.css";

const WORKSPACES = [
  ["operations", "Service Operations"], ["employees", "EmployeeWorks"], ["control-tower", "AI Control Tower"],
] as const;
export function ServiceNowApp({ company, screen }: { company: CompanyStudy; screen: string }) {
  const current = screen || "operations", { on } = useXRay();
  return <div className={`${s.study} ${current !== "operations" ? s.light : ""}`} data-company="servicenow">
    <CompoundBar activeId="servicenow"/>
    <header className={s.global}><div><div className={s.brand}>ServiceNow</div><small>Independent app study · Meridian Optics</small></div>
      <nav className={s.switcher} aria-label="ServiceNow study workspaces">{WORKSPACES.map(([id, label]) => <Link key={id} href={companyHref("servicenow", "app", id)} aria-current={current === id ? "page" : undefined}>{label}</Link>)}</nav>
    </header>
    <div className={s.body}>
      <aside className={s.rail} aria-label="Current workspace context"><h2>{current === "operations" ? "Operations workspace" : current === "employees" ? "Employee experience" : "AI governance"}</h2>
        {current === "operations" ? <><p>Service operations</p><p className={s.on}>Incident · INC0010427</p><p>Customer order capture</p></> : current === "employees" ? <><p>Tasks & Requests</p><p className={s.on}>To-dos · team move</p><p>Otto + request details</p></> : <><p>Activity Center</p><p className={s.on}>Work · model change</p><p>Inventory context</p></>}
        <p className={s.note}>A focused scene within this workspace. Use the workspace switcher to explore the three company ideas.</p>
        <Link className={s.link} href={companyHref("servicenow", "backstage")}>The company behind it ↗</Link>
      </aside>
      <main className={s.main}>
        {current === "operations" ? <Operations/> : current === "employees" ? <EmployeeWorks/> : <ControlTower/>}
        {on && <section className={s.insight}><strong>X-ray · {company.backstage.question}</strong><p className="mt-3">{company.strategy?.contrast}</p><Link className={s.link} href={companyHref("servicenow", "backstage", "essays")}>Read the deeper argument →</Link></section>}
        <footer className={s.footer}>Illustrative ServiceNow concepts using fictional Meridian Optics records. Every action is a local simulation, reset when you leave the scene. No real agent, identity system or production service is connected. <Link className="underline" href={companyHref("servicenow", "backstage", "sources")}>Sources & product boundaries</Link></footer>
      </main>
    </div>
  </div>;
}

function Operations() {
  const [state, dispatch] = useReducer(incidentReducer, INITIAL_INCIDENT);
  const [tab, setTab] = useState("overview"), [reason, setReason] = useState("");
  const phaseIndex = ["investigating", "approved", "executed", "recovered", "resolved"].indexOf(state.phase);
  const incidentStatus = state.phase === "resolved" ? "Resolved" : "In progress";
  const reset = () => { dispatch({ type: "reset" }); setReason(""); setTab("overview"); };
  return <>
    <p className={s.eyebrow}>Service Operations Workspace / Incident / INC0010427</p>
    <div className={s.row}><h1 className={s.h1}>Customer checkout is timing out.</h1><div className="flex gap-2"><span className={`${s.badge} ${s.priority}`}>P1 · Critical</span><span className={`${s.badge} ${state.phase === "resolved" ? s.success : ""}`}>{incidentStatus}</span></div></div>
    <p className={s.intro}>The order-capture service depends on an API and database. A recent configuration change is a lead to investigate—not a proven cause.</p>
    <div className={s.tabs} aria-label="Incident view">{[["overview", "Overview"], ["investigate", "Investigate"], ["activity", "Activity"]].map(([id, label]) => <button key={id} aria-pressed={tab === id} onClick={() => setTab(id)}>{label}</button>)}</div>
    <div className={s.columns}><div className={s.stack}>
      {tab === "overview" && <section className={s.card}><h2>Impact summary</h2><dl className={s.details}><div><dt>Business service</dt><dd>Customer order capture</dd></div><div><dt>Service offering</dt><dd>Online parts ordering</dd></div><div><dt>Assignment group</dt><dd>Commerce Operations</dd></div><div><dt>Configuration item</dt><dd>Orders database · DB-02</dd></div></dl>
        <div className={s.graph} aria-label="Service dependencies"><div className={s.node}><strong>Customer order capture</strong><span className={`${s.badge} ${state.health === "healthy" ? s.success : s.warning}`}>{state.health === "healthy" ? "Recovery observed" : "Degraded"}</span></div><div className={s.arrow}>↓ depends on</div><div className={s.node}><strong>Ordering API · APP-07</strong><span>Commerce Operations</span></div><div className={s.arrow}>↓ depends on</div><div className={s.node}><strong>Orders database · DB-02</strong><span>Database Operations</span></div></div>
        <p className={s.small}>Fictional CMDB relationship snapshot, reviewed for this scenario. Relationships describe the service; they do not grant permission to modify the underlying systems.</p><button className={`${s.link} mt-4`} onClick={() => setTab("investigate")}>Inspect the related change →</button>
      </section>}
      {tab === "investigate" && <section className={s.card}><div className={s.row}><h2>Related change · CHG00481</h2><span className={`${s.badge} ${s.warning}`}>Hypothesis</span></div><p>Connection-pool configuration changed shortly before the incident. The temporal relationship warrants investigation; it does not establish causation.</p><div className={s.evidence}><strong>Evidence bundle</strong><p>Monitoring: timeout errors after the change<br/>Configuration: pool limit changed from 80 to 20<br/>Proposed recovery: restore previous configuration v17<br/>Control: linked change approval before execution</p></div><p className={s.small}>An Otto incident-assist workflow can bring related CI, SLA and change context together. This scripted scene does not claim that retrieval itself authorises or executes a rollback.</p><div className={s.actions}><button className={s.secondary} disabled={state.inspected} onClick={() => dispatch({ type: "inspect" })}>{state.inspected ? "Evidence reviewed" : "Mark demo evidence reviewed"}</button></div></section>}
      {tab === "activity" && <section className={s.card}><h2>Activity & completion evidence</h2><ol className={s.log}><li>Incident opened · Commerce Operations assigned</li>{state.inspected && <li>Change context inspected · remediation remains a proposal</li>}{phaseIndex >= 1 && <li>CHG00482 approved in the simulation · rationale retained: {state.rationale}</li>}{phaseIndex >= 2 && <li>Mock connector receipt EXE-017 · configuration v17 restored</li>}{state.healthChecks.map((healthy, index) => <li key={index}>Mock health check {index + 1} · {healthy ? "successful checkout observed" : "failed; service still degraded and incident kept open"}</li>)}{phaseIndex >= 4 && <li>Incident resolved after recovery evidence</li>}</ol></section>}
      <div className={s.insight}><strong>The value is the chain of responsibility.</strong> The service model connects the event to its business consequence. The change process controls the response. A returned health check establishes recovery.</div>
    </div><section className={s.card} aria-label="Controlled remediation"><p className={s.eyebrow}>Linked remediation · CHG00482</p><h2 className="mt-3">A fix needs more than confidence.</h2>
      {state.phase === "investigating" && <><p className={s.muted}>Review the related change, then record the change manager's rationale for the proposed recovery.</p><label className={s.field}>Demo approval rationale<textarea className={s.input} rows={3} value={reason} onChange={e => setReason(e.target.value)} placeholder="Why this controlled recovery is appropriate"/></label><div className={s.actions}><button className={s.btn} disabled={!state.inspected || reason.trim().length < 10} onClick={() => dispatch({ type: "approve", reason })}>Approve demo change</button></div><p className={s.small}>Requires reviewed evidence and a rationale of at least 10 characters.</p></>}
      {state.phase === "approved" && <><p>The change is approved. The database has not changed yet.</p><div className={s.actions}><button className={s.btn} onClick={() => dispatch({ type: "execute" })}>Simulate connector execution</button></div></>}
      {state.phase === "executed" && <><div className={s.evidence}><strong>Execution receipt EXE-017</strong><p>Mock database connector confirms configuration v17 was restored.</p></div><p>Execution is confirmed. Service recovery still needs an observation.</p><div className={s.actions}><button className={s.btn} onClick={() => dispatch({ type: "health", healthy: true })}>Simulate healthy checkout</button><button className={s.secondary} onClick={() => dispatch({ type: "health", healthy: false })}>Simulate failed check</button></div></>}
      {state.phase === "recovered" && <><div className={s.evidence}><strong>Health receipt HC-044</strong><p>Mock checkout succeeds after the controlled change.</p></div><p>Recovery is observed; the incident still needs its resolution step.</p><button className={`${s.btn} mt-4`} onClick={() => dispatch({ type: "resolve" })}>Resolve demo incident</button></>}
      {state.phase === "resolved" && <><span className={`${s.badge} ${s.success}`}>Outcome verified in the simulation</span><p>The incident is resolved with linked approval, execution and recovery evidence. No real system was changed.</p></>}
      <p className={s.small} role="status">{state.health === "failed" ? "The failed check keeps the incident open. Reassess the hypothesis before treating the service as recovered." : state.phase === "investigating" ? state.inspected ? "Evidence reviewed; approval still required." : "Open Investigate to inspect the change evidence." : `Current state: ${state.phase}.`}</p>
      <div className={s.actions}><button className={s.secondary} onClick={reset}>Reset incident</button><button className={s.link} onClick={() => setTab("activity")}>View activity →</button></div>
    </section></div>
  </>;
}

function EmployeeWorks() {
  const [state, dispatch] = useReducer(journeyReducer, INITIAL_JOURNEY), [question, setQuestion] = useState("status"), [policy, setPolicy] = useState(false), [role, setRole] = useState("employee");
  const complete = journeyComplete(state);
  return <>
    <p className={s.eyebrow}>EmployeeWorks / Tasks & Requests / To-dos</p><h1 className={s.h1}>One team move. Several things to finish.</h1>
    <p className={s.intro}>Alex Morgan is joining the Singapore service team. The HR transfer is recorded; role access and workplace readiness still need to follow.</p>
    <div className={s.columns}><section className={s.card}><div className={s.otto}><span>↗</span>Otto</div><div className={s.request}>“I'm moving to the Singapore team next month. What still needs doing?”</div>
      <div className={s.tabs} aria-label="Suggested employee question"><button aria-pressed={question === "status"} onClick={() => setQuestion("status")}>My move</button><button aria-pressed={question === "access"} onClick={() => setQuestion("access")}>Why is access waiting?</button></div>
      <h2>{complete ? "Your move is ready in this scenario." : question === "access" ? state.accessReceipt === "complete" ? "The identity provider returned a completion receipt." : state.approved ? "Approval is recorded; identity fulfilment is a separate step." : "The role-access request needs manager approval." : "The request is still in progress."}</h2>
      <p className={s.muted}>{complete ? "The role-access receipt and workplace confirmation are both recorded. No live employee system was changed." : "The HR record establishes the transfer. It does not prove access has been provisioned or the destination workplace is ready."}</p>
      <button className={`${s.link} mt-4`} aria-expanded={policy} onClick={() => setPolicy(!policy)}>Inspect policy and source context →</button>
      {policy && <div className={s.evidence}><strong>Fictional policy · Team moves, §3</strong><p>Role access requires manager approval before the identity task is sent. Workspace readiness needs a separate confirmation.</p><p><strong>External HRIS context</strong><br/>Transfer HR-108 · effective 1 October 2026<br/>New team: Singapore Service<br/>HR record: approved · read-only in this scene</p><p className={s.small}>This represents configured external context, not an assumption that ServiceNow is the HR/payroll ledger.</p></div>}
      <div className={s.insight}><strong>The front door changed; the obligations remain.</strong> EmployeeWorks and Otto put conversational intent beside forms, tasks and approvals. Each downstream system still has work to do.</div>
    </section><section className={s.card}><div className={s.row}><h2>Request · REQ001083</h2><span className={`${s.badge} ${complete ? s.success : ""}`}>{complete ? "Complete" : "In progress"}</span></div>
      <label className={s.field}>View as · demo role<select className={s.input} value={role} onChange={e => setRole(e.target.value)}><option value="employee">Employee · request status</option><option value="manager">Manager · access approval</option><option value="it">IT · identity fulfilment</option><option value="workplace">Workplace · readiness</option></select></label><p className={s.small}>Explore each owner’s part in the journey. An employee would not receive all of these permissions.</p><div className={s.tasks}><div className={s.task}><h3>Manager · approve role access</h3><p className={s.small}>New service-team application access for Alex. The HR transfer approval is a different record.</p>{role === "manager" ? <button className={s.btn} disabled={state.approved} onClick={() => dispatch({ type: "approve" })}>{state.approved ? "Demo approval recorded" : "Approve demo role access"}</button> : <span className={s.badge}>{state.approved ? "Approval recorded" : "Awaiting manager"}</span>}</div>
        <div className={s.task}><div className={s.row}><h3>IT · provision access</h3><span className={`${s.badge} ${state.accessReceipt === "failed" ? s.warning : state.accessReceipt === "complete" ? s.success : ""}`}>{state.accessReceipt === "complete" ? "Receipt received" : state.accessReceipt === "failed" ? "Needs IT review" : state.dispatched ? "Awaiting receipt" : "Not dispatched"}</span></div>
          {role === "it" && <div className={s.actions}><button className={s.secondary} disabled={!state.approved || (state.dispatched && state.accessReceipt !== "failed")} onClick={() => dispatch({ type: "dispatch" })}>{state.accessReceipt === "failed" ? "Retry demo identity task" : "Send demo identity task"}</button>
            {state.dispatched && state.accessReceipt === "pending" && <><button className={s.btn} onClick={() => dispatch({ type: "receipt", success: true })}>Simulate success receipt</button><button className={s.secondary} onClick={() => dispatch({ type: "receipt", success: false })}>Simulate provider error</button></>}
          </div>}<p className={s.small}>{state.accessReceipt === "failed" ? "Mock provider could not locate the target group. IT retains the task; the journey stays open." : state.accessReceipt === "complete" ? "Mock receipt IDP-218 confirms the requested group membership." : "Sending the task does not establish access. A provider result must return."}</p>
        </div><div className={s.task}><h3>Workplace · confirm team readiness</h3><p className={s.small}>A separate owner confirms the destination workspace is ready.</p>{role === "workplace" ? <button className={s.secondary} disabled={state.workplaceReady} onClick={() => dispatch({ type: "workplace" })}>{state.workplaceReady ? "Readiness confirmed in demo" : "Confirm demo workplace readiness"}</button> : <span className={s.badge}>{state.workplaceReady ? "Readiness confirmed" : "Awaiting workplace owner"}</span>}</div>
      </div><p className={s.small} role="status">{complete ? "Complete: manager approval, identity receipt and workplace confirmation are all present." : `Manager ${state.approved ? "approved" : "pending"} · access ${state.accessReceipt} · workplace ${state.workplaceReady ? "ready" : "pending"}.`}</p><button className={`${s.link} mt-5`} onClick={() => {dispatch({ type: "reset" });setQuestion("status");setPolicy(false);setRole("employee");}}>Reset request</button>
    </section></div>
  </>;
}

function ControlTower() {
  const [state, dispatch] = useReducer(governanceReducer, INITIAL_GOVERNANCE), [note, setNote] = useState(""), [view, setView] = useState("work"), [assessmentOpen, setAssessmentOpen] = useState(false);
  const decisionMade = state.phase !== "open";
  return <>
    <p className={s.eyebrow}>AI Control Tower / Activity Center</p><h1 className={s.h1}>A model change is an operating decision.</h1><p className={s.intro}>Review a request to change the model behind a customer-support agent. Ownership, the impact assessment and the deployment receipt answer different questions.</p>
    <div className={s.tabs} aria-label="Control Tower view"><button aria-pressed={view === "work"} onClick={() => setView("work")}>Work · Assigned to you</button><button aria-pressed={view === "inventory"} onClick={() => setView("inventory")}>Inventory context</button></div>
    {view === "inventory" ? <section className={s.card}><h2>Discovery does not confer control.</h2><div className={s.tablewrap}><table className={s.table}><thead><tr><th>AI asset</th><th>Owner</th><th>Management state</th><th>What is established</th></tr></thead><tbody><tr><td>Customer Support Agent</td><td>Customer Operations</td><td>Managed</td><td>Owner and lifecycle review configured</td></tr><tr><td>Research Assistant</td><td>Not yet assigned</td><td>Discovered · unmanaged</td><td>Inventory only; governance onboarding needed</td></tr></tbody></table></div><p className={s.small}>Fictional inventory. External assets require configured connectors and management decisions. A discovered asset is not automatically within ServiceNow's execution authority.</p><button className={`${s.link} mt-4`} onClick={() => setView("work")}>Return to the model-change request →</button></section> : <>
      <section className={s.card}><div className={s.row}><h2>Requests</h2><span className={s.badge}>Assigned to you · 1 request</span></div><div className={s.tablewrap}><table className={s.table}><thead><tr><th>Number</th><th>Short description</th><th>Asset in review</th><th>Priority</th><th>State</th></tr></thead><tbody><tr><td>AIR00127</td><td>Replace support-response model</td><td>Customer Support Agent</td><td>2 · High</td><td><span className={`${s.badge} ${state.phase === "deployed" ? s.success : ""}`}>{state.phase === "open" ? "Open" : state.phase === "returned" ? "Returned to owner" : state.phase === "approved" ? "Approved · awaiting receipt" : "Deployment receipt received"}</span></td></tr></tbody></table></div></section>
      <div className={s.columns}><section className={s.card}><p className={s.eyebrow}>Asset & change context</p><h2 className="mt-3">Customer Support Agent</h2><dl className={s.details}><div><dt>Accountable owner</dt><dd>Customer Operations</dd></div><div><dt>Proposed change</dt><dd>Response model v2 → v3</dd></div><div><dt>Downstream use</dt><dd>Case-response drafts</dd></div><div><dt>Authority limit</dt><dd>Draft only · no autonomous sends</dd></div></dl><div className={s.evidence}><strong>Impact assessment IA-027 · fictional evidence</strong><p>Case summarisation and response drafts are affected. Human review stays required before a customer message is sent. The proposed change does not add refund or account-update permissions.</p><p>{state.assessed ? "Scope and rollback evidence reviewed for this request." : "Review the unchanged scope and the owner’s rollback plan before approval."}</p></div><div className={s.actions}><button className={s.secondary} aria-expanded={assessmentOpen} onClick={() => setAssessmentOpen(!assessmentOpen)}>Inspect scope & rollback plan</button></div>{assessmentOpen && <div className={s.evidence}><strong>Rollback plan · RP-027</strong><p>Owner: Customer Operations platform lead.<br/>Restore target: response model v2.<br/>Trigger: the canary produces a response outside the approved draft-only scope.<br/>Recovery: pause the canary, restore v2 through the external deployment workflow, and check a returned draft before resuming.</p><p>The human-send requirement and refund/account-write restrictions stay unchanged in both versions.</p><button className={s.secondary} disabled={state.assessed || decisionMade} onClick={() => dispatch({ type: "assess" })}>{state.assessed ? "Assessment reviewed" : "Mark demo assessment reviewed"}</button></div>}<p className={s.small}>This demonstrates a governed request, not a vendor performance comparison. Models v2/v3 and the assessment are invented.</p></section>
      <section className={s.card}><p className={s.eyebrow}>Governance decision</p><h2 className="mt-3">{state.phase === "open" ? "Explain the decision." : state.phase === "returned" ? "The owner has more work to do." : state.phase === "approved" ? "Approval is not deployment." : "A receipt closes this change loop."}</h2>
        {state.phase === "open" && <><label className={s.field}>Decision note<textarea className={s.input} rows={4} value={note} onChange={e => setNote(e.target.value)} placeholder="What evidence supports approval, or what must change?"/></label><div className={s.actions}><button className={s.btn} disabled={!state.assessed || note.trim().length < 10} onClick={() => dispatch({ type: "approve", note })}>Approve demo request</button><button className={s.secondary} disabled={note.trim().length < 10} onClick={() => dispatch({ type: "return", note })}>Return to owner</button></div><p className={s.small}>Approval requires reviewed evidence. Either decision needs at least 10 characters of rationale.</p></>}
        {state.phase === "returned" && <p>The request remains unapproved and cannot proceed to deployment. Owner follow-up is retained in the decision below.</p>}
        {state.phase === "approved" && <><p>The decision is recorded. The external deployment workflow still needs to apply the approved configuration and return its result.</p><button className={`${s.btn} mt-4`} onClick={() => dispatch({ type: "receipt" })}>Simulate deployment receipt</button></>}
        {state.phase === "deployed" && <div className={s.evidence}><strong>Mock receipt DEP-031</strong><p>External runtime reports model v3 active; draft-only permissions retained. The receipt proves a simulated deployment, not improved answer quality.</p></div>}
        {decisionMade && <div className={s.evidence}><strong>Recorded decision note</strong><p>{state.decisionNote}</p></div>}<p className={s.small} role="status">{state.phase === "open" ? state.assessed ? "Evidence reviewed; a reasoned decision is still required." : "Inspect the affected uses and scope before approving." : `Decision state: ${state.phase}.`}</p><div className={s.actions}><button className={s.secondary} onClick={() => {dispatch({ type: "reset" });setNote("");setAssessmentOpen(false);}}>Reset request</button></div>
      </section></div>
    </>}
    <div className={s.insight}><strong>The strategic test:</strong> can governance reach the consequential action? A registry, an approval and a deployment each establish something different. Universal third-party enforcement is not assumed.</div>
  </>;
}
