'use client';
import {useState} from 'react';
import type {GovernanceAction,GovernanceRole,GovernancePhase} from '@/lib/data/servicenow-scenarios';
import {useServiceNowSession,useSceneFocus} from './session';
import s from './servicenow.module.css';
type WithoutActor<T> = T extends unknown ? Omit<T,'actor'> : never;
const phaseLabel:Record<GovernancePhase,string>={open:'Awaiting review',returned:'Returned to owner',approved:'Approved · not deployed',deploying:'Awaiting runtime receipt',deployed:'Canary needs observation','rollback-required':'Rollback required','rolled-back':'v2 restored · owner follow-up',complete:'Canary verified'};
const nextOwner:Record<GovernancePhase,GovernanceRole>={open:'reviewer',returned:'owner',approved:'operator',deploying:'operator',deployed:'operator','rollback-required':'operator','rolled-back':'owner',complete:'reviewer'};
const roleName:Record<GovernanceRole,string>={reviewer:'Governance reviewer',owner:'Asset owner',operator:'Runtime operator'};
export function ControlTower(){
  const {state:{governance:state},dispatch:record,drafts,setDraft,full}=useServiceNowSession();
  const [role,setRole]=useState<GovernanceRole>('reviewer'),[view,setView]=useState('work'),[assessmentOpen,setAssessmentOpen]=useState(false);
  const focus=useSceneFocus(state,'governance-next');
  const send=(action:WithoutActor<GovernanceAction>)=>focus(()=>record({scene:'governance',action:{...action,actor:role} as GovernanceAction}));
  const active=role===nextOwner[state.phase];
  return <>
    <p className={s.eyebrow}>AI Control Tower / Activity Center</p><h1 className={s.h1}>A model change is an operating decision.</h1><p className={s.intro}>The owner proposes, a reviewer decides, and an external runtime returns evidence. Follow the same asset through a return, a new review and a canary that can still fail.</p>
    <div className={s.tabs} aria-label="Control Tower view"><button aria-pressed={view==='work'} onClick={()=>setView('work')}>Work · model change</button><button aria-pressed={view==='inventory'} onClick={()=>setView('inventory')}>Inventory context</button><button aria-pressed={view==='history'} onClick={()=>setView('history')}>Decision history · {state.history.length}</button></div>
    {view==='inventory'?<section className={s.card}><h2>Discovery does not confer control.</h2><div className={s.tablewrap}><table className={s.table}><thead><tr><th>AI asset</th><th>Owner</th><th>Runtime model</th><th>Governance context</th></tr></thead><tbody><tr><td>Customer Support Agent</td><td>Customer Operations</td><td>{state.activeModel}{state.phase==='rollback-required'?' · canary paused':''}</td><td>Managed · {phaseLabel[state.phase]}</td></tr><tr><td>Research Assistant</td><td>Not yet assigned</td><td>Not established</td><td>Discovered · unmanaged</td></tr></tbody></table></div><p className={s.small}>Fictional inventory. The managed asset follows this request’s runtime receipts. Discovery of the Research Assistant establishes neither an owner nor execution authority.</p><button className={`${s.secondary} mt-4`} onClick={()=>setView('work')}>Return to the model-change request →</button></section>:view==='history'?<section className={s.card}><h2>Decision history · AIR00127</h2><p className={s.small}>Each revision retains the earlier decision and the owner’s response.</p><ol className={s.log}><li>Revision 1 proposed · Customer Operations · v2 → v3 · draft-only scope</li>{state.history.map((event,i)=><li key={i}><strong>Revision {event.revision} · {event.kind}</strong><br/>{event.note}</li>)}</ol><button className={`${s.secondary} mt-4`} onClick={()=>setView('work')}>Return to current work →</button></section>:<>
      <section className={s.card}><div className={s.row}><div><h2>AIR00127 · Customer Support Agent</h2><p className={s.small}>Revision {state.revision} · response model v2 → v3</p></div><span className={`${s.badge} ${state.phase==='complete'?s.success:['returned','rollback-required','rolled-back'].includes(state.phase)?s.warning:''}`}>{phaseLabel[state.phase]}</span></div></section>
      <div className={s.columns}><section className={s.card}><p className={s.eyebrow}>Asset & change context</p><h2 className="mt-3">One asset, several kinds of evidence.</h2><dl className={s.details}><div><dt>Accountable owner</dt><dd>Customer Operations</dd></div><div><dt>Runtime model</dt><dd>{state.activeModel}{state.phase==='rollback-required'?' · canary paused':''}</dd></div><div><dt>Downstream use</dt><dd>Case-response drafts</dd></div><div><dt>Authority limit</dt><dd>Draft only · no autonomous sends</dd></div></dl>
        <div className={s.evidence}><strong>Impact assessment IA-027 · revision {state.revision}</strong><p>Case summarisation and response drafts are affected. A person still reviews and sends each message. Refunds and account updates remain outside scope.</p><p>{state.assessed?'Evidence reviewed for this revision.':'This revision needs a fresh review before approval.'}</p></div>
        {state.history.some(e=>e.kind==='Owner resubmitted')&&<div className={s.evidence}><strong>Latest owner response</strong><p>{[...state.history].reverse().find(e=>e.kind==='Owner resubmitted')?.note}</p></div>}
        <button className={`${s.secondary} mt-4`} aria-expanded={assessmentOpen} onClick={()=>setAssessmentOpen(!assessmentOpen)}>Inspect scope & rollback plan</button>
        {assessmentOpen&&<div className={s.evidence}><strong>Rollback plan · RP-027</strong><p>Customer Operations platform lead owns the plan. If the v3 canary attempts an action outside draft-only scope, block the action, pause the canary, and restore v2 through the external deployment workflow.</p><p>A runtime receipt establishes which model is deployed. A reviewed canary sample provides separate, limited outcome evidence. Neither result establishes general model superiority.</p>{role==='reviewer'&&<button className={s.secondary} disabled={state.assessed||state.phase!=='open'} onClick={()=>send({type:'assess'})}>{state.assessed?'Assessment reviewed':'Mark demo assessment reviewed'}</button>}</div>}
        <p className={s.small}>Invented models, policy and evidence. Role switching explores the configured handoffs; it is not a real permission change.</p>
      </section><section className={s.card} aria-label="Governance decision"><label className={s.field}>Explore as · demo role<select className={s.input} value={role} onChange={e=>setRole(e.target.value as GovernanceRole)}>{Object.entries(roleName).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><p className={s.eyebrow}>Next responsibility</p><h2 id="governance-next" tabIndex={-1} className="mt-3">{state.phase==='complete'?'Change verified in this scenario.':roleName[nextOwner[state.phase]]}</h2>
        {!active&&state.phase!=='complete'&&<div className={s.evidence}><p>{roleName[role]} can inspect the record. {roleName[nextOwner[state.phase]]} owns the next action.</p><button className={`${s.secondary} mt-3`} onClick={()=>setRole(nextOwner[state.phase])}>Explore {roleName[nextOwner[state.phase]]} →</button></div>}
        {active&&state.phase==='open'&&<><label className={s.field}>Decision note<textarea className={s.input} maxLength={2000} rows={4} value={drafts.governanceNote} onChange={e=>setDraft('governanceNote',e.target.value)}/></label><div className={s.actions}><button className={s.btn} disabled={!state.assessed||drafts.governanceNote.trim().length<10} onClick={()=>send({type:'approve',note:drafts.governanceNote})}>Approve demo request</button><button className={s.secondary} disabled={drafts.governanceNote.trim().length<10} onClick={()=>send({type:'return',note:drafts.governanceNote})}>Return to owner</button></div><p className={s.small}>Approval needs a reviewed assessment. Missing information can justify a return before that review. Either decision needs at least 10 characters of rationale.</p></>}
        {active&&['returned','rolled-back'].includes(state.phase)&&<><p>{state.phase==='returned'?'Address the reviewer’s feedback before resubmitting.':'The runtime is back on v2. Record what changes before proposing v3 again.'}</p><label className={s.field}>Owner response<textarea className={s.input} maxLength={2000} rows={4} value={drafts.ownerResponse} onChange={e=>setDraft('ownerResponse',e.target.value)}/></label><button className={`${s.btn} mt-4`} disabled={drafts.ownerResponse.trim().length<10} onClick={()=>{send({type:'resubmit',note:drafts.ownerResponse});setDraft('governanceNote','');setDraft('ownerResponse','');setAssessmentOpen(false);}}>Resubmit for a fresh review</button><p className={s.small}>At least 10 characters. Earlier notes remain in Decision history; approval cannot carry over.</p></>}
        {active&&state.phase==='approved'&&<><p>The request is approved. Runtime model {state.activeModel} is still active.</p><button className={`${s.btn} mt-4`} onClick={()=>send({type:'deploy'})}>Send demo deployment request</button></>}
        {active&&state.phase==='deploying'&&<><p>The external workflow has the request. Its result has not returned.</p><button className={`${s.btn} mt-4`} onClick={()=>send({type:'receipt'})}>Simulate deployment receipt</button></>}
        {active&&state.phase==='deployed'&&<><div className={s.evidence}><strong>DEP-031 · v3 deployed</strong><p>Draft-only controls retained. Now observe a sample from the canary.</p></div><div className={s.actions}><button className={s.btn} onClick={()=>send({type:'observe',passed:true})}>Simulate in-scope canary</button><button className={s.secondary} onClick={()=>send({type:'observe',passed:false})}>Simulate out-of-scope attempt</button></div></>}
        {active&&state.phase==='rollback-required'&&<><div className={s.evidence}><strong>Account update blocked · canary paused</strong><p>Draft-only permissions blocked the write. The model still attempted an unapproved action. v3 remains deployed until a rollback receipt returns.</p></div><button className={`${s.btn} mt-4`} onClick={()=>send({type:'rollback'})}>Simulate v2 rollback receipt</button></>}
        {state.phase==='complete'&&<p>The runtime reports v3 and a reviewed canary stayed within scope. That closes this fictional change; it does not prove every future response will be correct.</p>}
        {state.decisionNote&&<div className={s.evidence}><strong>Revision {state.revision} · recorded decision</strong><p>{state.decisionNote}</p></div>}
        <p className={s.small} role="status">{full.includes('governance')?'History limit reached. Reset this request to explore another path.':`Revision ${state.revision} · ${phaseLabel[state.phase]} · runtime ${state.activeModel}.`}</p><div className={s.actions}><button className={s.secondary} onClick={()=>{send({type:'reset'});setAssessmentOpen(false);setRole('reviewer');}}>Reset AI request</button><button className={s.secondary} onClick={()=>setView('history')}>View decision history →</button></div>
      </section></div>
    </>}
    <div className={s.insight}><strong>Governance has to survive an exception.</strong> Returning, revising, re-reviewing and rolling back are part of the same obligation. The asset’s inventory record follows the receipts.</div>
  </>;
}
