'use client';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {useState} from 'react';
import {DECISIONS,evaluateDecision,readAnswers,type Answers} from '@/lib/decision-engine';
import {ECOSYSTEMS} from '@/lib/ecosystem-index';
import {COMPANY_INDEX} from '@/lib/company-index';
import {DestinationIntro,DestinationShell,SourceLink} from './destination-shell';
import {AdoptionGap} from './adoption-gap';

export function DecisionView(){
 const params=useSearchParams(),decision=DECISIONS.find(d=>d.id===params.get('dilemma'))??DECISIONS[0];
 const ecosystem=ECOSYSTEMS.find(e=>e.id===params.get('platform'))??ECOSYSTEMS[0];
 const domains=[...new Set(ecosystem.research.companies.flatMap(c=>c.capabilities.map(f=>f.capability)))].filter(c=>!['Advisory','Implementation','AMS','Resourcing'].includes(c));
 const questions=decision.questions.map(q=>q.id==='domain'?{...q,options:domains.map(id=>({id,label:id}))}:q);
 const answers=readAnswers(decision,new URLSearchParams(params.toString()),domains),complete=questions.every(q=>answers[q.id]);
 const result=complete?evaluateDecision(decision.id,answers):null;
 const company=COMPANY_INDEX.find(c=>c.id===params.get('company'));
 const practices=COMPANY_INDEX.filter(c=>c.ecosystemLinks.some(p=>p.ecosystemId===ecosystem.id&&!p.historical));
 const practice=company&&practices.includes(company)?company:undefined;
 const publicCases=ecosystem.research.customers.filter(c=>c.companyId===practice?.id&&(!answers.domain||c.capabilities.includes(answers.domain))).slice(0,3);
 const [copyState,setCopyState]=useState('');
 const change=(values:Answers,replace=false)=>{const next=replace?new URLSearchParams():new URLSearchParams(window.location.search);for(const [k,v] of Object.entries(values)){if(v)next.set(k,v);else next.delete(k);}window.history.pushState(null,'',`/decisions?${next}`);setCopyState('');};
 const example=()=>change({dilemma:decision.id,...decision.example,...(decision.id==='si'?{platform:'workday'}:{})},true);
 const brief=()=>[decision.title,practice?`${practice.name} · ${ecosystem.name} · ANZ`:'',...questions.map(q=>`${q.title} ${q.options.find(o=>o.id===answers[q.id])?.label??'Unanswered'}`),'',`Next: ${result?.title??'Complete the decision context'}`,result?.because??'',`Prove: ${result?.proof??''}`,`Revisit when: ${result?.nextWhen??''}`,'',window.location.href].filter(Boolean).join('\n');
 const copy=async()=>{try{await navigator.clipboard.writeText(brief());setCopyState('Decision copied');}catch{setCopyState('Copy is unavailable here. Use the page URL to share the same answers.');}};
 const practiceHref=practice?`/atlas/${ecosystem.id}?scope=anz&lens=capability&firm=${practice.id}${answers.domain?`&proof=${encodeURIComponent(answers.domain)}`:''}`:`/atlas/${ecosystem.id}?scope=anz&lens=capability`;
 return <DestinationShell active="decisions">
  <DestinationIntro kicker="Decisions · from evidence to a next step" title="Make the next commitment clear." body="Work through a real dilemma. Change an answer, see why the next step changes, and take the resulting brief into a useful conversation."/>
  <nav className="mb-5 flex flex-wrap gap-2" aria-label="Choose a decision">{DECISIONS.map(d=><Link key={d.id} href={`/decisions?dilemma=${d.id}`} aria-current={d.id===decision.id?'page':undefined} className={`rounded-lg px-4 py-3 text-xs font-semibold ${d.id===decision.id?'bg-[#173C3C] text-white':'border border-black/10 bg-white'}`}>{d.name}</Link>)}</nav>
  <div className="grid items-start gap-5 lg:grid-cols-[1.05fr_1fr]">
   <section className="rounded-2xl border border-black/10 bg-white p-5 sm:p-7">
    <p className="text-[10px] font-semibold uppercase tracking-wider text-[#54716B]">Your decision context</p><h2 className="font-serif-display mt-2 text-3xl">{decision.title}</h2><p className="mt-3 text-sm leading-relaxed text-ink-500">{decision.intro}</p>
    <details className="mt-4 rounded-lg bg-[#F4F5EE] p-3 text-xs"><summary className="cursor-pointer font-semibold">Try a worked example</summary><p className="mt-3 leading-relaxed">{decision.exampleText}</p><p className="mt-2 text-[10px] text-ink-500">Illustrative organisation and assumptions.</p><button onClick={example} className="mt-3 rounded-md bg-[#173C3C] px-3 py-2 font-semibold text-white">Load example answers</button></details>
    {decision.id==='si'&&<div className="mt-6 grid gap-3 rounded-xl border border-black/10 p-4 sm:grid-cols-2"><label className="text-xs font-semibold">Platform<select value={ecosystem.id} onChange={e=>change({platform:e.target.value,company:'',domain:''})} className="mt-2 w-full rounded-md border border-black/15 bg-white p-2">{ECOSYSTEMS.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label className="text-xs font-semibold">Practice<select value={practice?.id??''} onChange={e=>change({company:e.target.value})} className="mt-2 w-full rounded-md border border-black/15 bg-white p-2"><option value="">Choose a practice (optional)</option>{practices.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><p className="text-[11px] leading-relaxed text-ink-500 sm:col-span-2">A public profile does not pre-fill your readiness answers.</p></div>}
    <div className="mt-6 space-y-6">{questions.map((q,i)=><fieldset key={`${decision.id}-${q.id}`} className="border-t border-black/10 pt-5"><legend className="pr-3 text-sm font-semibold"><span className="mr-2 font-mono text-xs text-[#54716B]">0{i+1}</span>{q.title}</legend>{q.help&&<p className="mb-3 text-xs leading-relaxed text-ink-500">{q.help}</p>}{q.id==='domain'?<select aria-label={q.title} value={answers[q.id]??''} onChange={e=>change({[q.id]:e.target.value})} className="w-full rounded-lg border border-black/15 bg-white p-3 text-sm"><option value="">Select a broad domain</option>{q.options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select>:<div className="space-y-2">{q.options.map(o=><label key={o.id} className={`flex cursor-pointer items-start gap-3 rounded-lg border p-3 text-xs leading-relaxed ${answers[q.id]===o.id?'border-[#78988A] bg-[#EFF4EB]':'border-black/10 hover:bg-[#FAFAF6]'}`}><input type="radio" name={`${decision.id}-${q.id}`} value={o.id} checked={answers[q.id]===o.id} onChange={()=>change({[q.id]:o.id})} className="mt-0.5 accent-[#17423B]"/><span>{o.label}</span></label>)}</div>}</fieldset>)}</div>
   </section>
   <div className="space-y-4 lg:sticky lg:top-5">
    <article className="rounded-2xl bg-[#173C3C] p-6 text-white sm:p-8" aria-live="polite"><p className="text-[10px] font-semibold uppercase tracking-wider text-[#D5DFAA]">{complete?'Suggested next commitment':'Build the picture'} · {Object.keys(answers).length}/{questions.length} answers</p><h2 className="font-serif-display mt-3 text-3xl">{result?.title??'What would justify the next step?'}</h2><p className="mt-4 text-sm leading-relaxed text-white/80">{result?.because??'Answer the five questions. “We don’t know yet” is useful evidence; it will lead to a proof step, not an invented readiness score.'}</p>{result&&<><div className="mt-6 rounded-xl bg-white/10 p-5"><h3 className="text-[10px] font-semibold uppercase tracking-wider text-[#D5DFAA]">Prove next</h3><p className="mt-2 text-sm leading-relaxed">{result.proof}</p></div><h3 className="mt-6 text-[10px] font-semibold uppercase tracking-wider text-[#D5DFAA]">What changes the answer?</h3><p className="mt-2 text-sm leading-relaxed text-white/80">{result.nextWhen}</p>{!!result.unresolved?.length&&<p className="mt-5 text-xs leading-relaxed text-white/65">Still to establish: {result.unresolved.join(' · ')}.</p>}<button onClick={copy} className="mt-6 rounded-lg bg-[#D5DFAA] px-4 py-2.5 text-xs font-semibold text-[#173C3C]">Copy decision brief</button></>}<p role="status" className="mt-3 text-xs text-white/70">{copyState}</p><p className="mt-5 border-t border-white/20 pt-4 text-[10px] leading-relaxed text-white/60">Compound’s decision rules, based on your answers. One next commitment; no vendor ranking or probability of success. The URL preserves the selected options.</p></article>
    {decision.id==='si'&&<section className="rounded-xl border border-black/10 bg-white p-5"><p className="text-[10px] font-semibold uppercase tracking-wider text-[#54716B]">Public evidence · separate from your answers</p><h3 className="mt-2 text-lg font-semibold">{practice?.name??`${ecosystem.name} delivery research`}</h3>{publicCases.length?publicCases.map(c=><div key={c.id} className="mt-3 text-xs leading-relaxed"><strong>{c.name}</strong><p className="mt-1 text-ink-500">{c.fact.text}</p><a href={`${practiceHref}&customer=${c.id}`} className="mt-1 inline-block font-semibold underline">Inspect this case →</a></div>):<p className="mt-3 text-xs leading-relaxed text-ink-500">{practice?'No matching customer case is captured here. The profile distinguishes local offers, regional claims and people experience.':'Choose a practice to keep its evidence beside the decision.'}</p>}<Link href={practiceHref} className="mt-4 inline-block text-xs font-semibold underline">Open the capability evidence →</Link></section>}
    <details className="rounded-xl border border-black/10 bg-white p-5 text-xs"><summary className="cursor-pointer font-semibold">Why these questions?</summary><p className="mt-3 leading-relaxed text-ink-500">The sources support the distinctions. Compound supplies the sequence and recommendations; the sources do not prescribe this exact questionnaire.</p><div className="mt-4 space-y-3">{decision.sources.map(s=><p key={s.url}><SourceLink href={s.url}>{s.label}</SourceLink></p>)}</div></details>
    <div className="flex flex-wrap gap-4 p-1 text-xs font-semibold"><Link href="/earth" className="underline">Trace the physical dependencies →</Link><Link href="/technology?view=future" className="underline">See measured change →</Link></div>
   </div>
  </div>
  <details className="mt-8 rounded-xl border border-black/10 p-5"><summary className="cursor-pointer text-sm font-semibold">Why technical capability and adoption move differently</summary><AdoptionGap/></details>
 </DestinationShell>;
}
