'use client';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {CLUSTERS,CONNECTIONS,WORLD_JOURNEYS,EARTH_LAYERS,clusterLayers,connectionsFor,worldSource,worldName,worldHref} from '@/lib/data/earth';
import {COMPANY_INDEX,companyDestination} from '@/lib/company-index';
import {DestinationIntro,DestinationShell,SourceLink} from './destination-shell';
const point=(c:typeof CLUSTERS[number])=>({x:(c.anchor.lon+180)*2.5,y:(90-c.anchor.lat)*2.5});
const offsets:Record<string,[number,number]>={'oberkochen':[28,5],'veldhoven':[-15,-22],'taiwan-foundry':[-24,25],'korea-memory':[25,-18],'china-industry':[-30,-14],'singapore':[0,22]};
export function EarthView(){
 const params=useSearchParams(),journey=WORLD_JOURNEYS.find(j=>j.id===params.get('journey'));
 const layer=EARTH_LAYERS.find(l=>l.id===params.get('layer'))?.id??'all';
 const visible=CLUSTERS.filter(c=>journey?journey.ids.includes(c.id):layer==='all'||clusterLayers(c.id).includes(layer));
 const aliases:Record<string,string>={'anz':'victoria-delivery','north-america':'santa-clara','europe':'veldhoven','east-asia':'taiwan-foundry','china':'china-industry','india':'bengaluru','southeast-asia':'singapore','africa':'johannesburg','latin-america':'canelones','middle-east':'abu-dhabi'};
 const requested=params.get('market')??'',selected=visible.find(c=>c.id===(aliases[requested]??requested))??visible[0];
 const links=connectionsFor(selected.id);
 const href=(id:string,values:Record<string,string>={})=>{const next=new URLSearchParams(params.toString());next.set('market',id);for(const [k,v] of Object.entries(values)){if(v)next.set(k,v);else next.delete(k);}return `/earth?${next}`;};
 const plotted=CONNECTIONS.filter(e=>visible.some(c=>c.id===e.fromId)&&visible.some(c=>c.id===e.toId));
 const companies=COMPANY_INDEX.filter(c=>selected.companyNames.includes(c.name));
 return <DestinationShell active="earth"><DestinationIntro kicker="Global View · places and dependencies" title="Follow the system behind the software." body="Chip design, precision tools, memory, electricity and local delivery form different parts of the same story. Follow a chain, then inspect what each connection actually establishes."/>
  <div className="mb-5 grid gap-2 sm:grid-cols-3">{WORLD_JOURNEYS.map((j,i)=><Link key={j.id} href={href(j.ids[0],{journey:j.id,layer:''})} aria-current={journey?.id===j.id?'true':undefined} className={`rounded-xl border p-4 ${journey?.id===j.id?'border-[#173C3C] bg-[#173C3C] text-white':'border-black/10 bg-white hover:bg-[#EEF2E8]'}`}><span className="text-[10px] opacity-60">0{i+1} · FOLLOW A QUESTION</span><strong className="mt-2 block text-sm">{j.name} →</strong></Link>)}</div>
  {journey&&<div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-lg bg-[#EAF0E4] p-4 text-xs"><p className="max-w-3xl leading-relaxed">{journey.reading}</p><Link href="/earth" className="font-semibold underline">Show all places</Link></div>}
  {!journey&&<nav aria-label="Filter by market role" className="mb-4 flex flex-wrap gap-2">{EARTH_LAYERS.map(l=><Link key={l.id} href={href(selected.id,{layer:l.id})} aria-current={layer===l.id?'true':undefined} className={`rounded-full border px-4 py-2 text-xs font-semibold ${layer===l.id?'border-[#183A3A] bg-[#183A3A] text-white':'border-black/10 bg-white'}`}>{l.name}</Link>)}</nav>}
  <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1.55fr)_minmax(300px,1fr)]">
   <section className="overflow-hidden rounded-2xl bg-[#102A31] text-white" aria-label="Connected market map"><div className="flex flex-wrap justify-between gap-2 px-5 pt-5 text-[10px] uppercase tracking-wider text-[#A0BBB7]"><span>{journey?'A selected dependency story':'Selected global technology clusters'}</span><span>Evidence checked September 2026</span></div>
    <div className="overflow-x-auto"><svg viewBox="0 0 900 440" role="img" aria-labelledby="world-title world-desc" className="w-full min-w-[560px]"><title id="world-title">Places behind the technology</title><desc id="world-desc">Numbered places correspond to the links below. Arrows denote documented relationships, not transport routes. Dashed arrows are announced relationships. Choose a place to inspect the evidence.</desc><defs><marker id="world-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="#D9C16C"/></marker></defs><image href="/earth-land.svg" width="900" height="450"/>{[0,30,-30,60,-60].map(lat=><line key={lat} x1="0" x2="900" y1={(90-lat)*2.5} y2={(90-lat)*2.5} stroke="#91B5B1" strokeOpacity=".1"/>)}
    {plotted.map(e=>{const a=point(CLUSTERS.find(c=>c.id===e.fromId)!),b=point(CLUSTERS.find(c=>c.id===e.toId)!),active=e.fromId===selected.id||e.toId===selected.id;return <path key={e.id} d={`M${a.x} ${a.y} Q${(a.x+b.x)/2} ${Math.min(a.y,b.y)-Math.min(70,Math.abs(a.x-b.x)*.2)} ${b.x} ${b.y}`} fill="none" stroke="#D9C16C" strokeWidth={active?2.5:1.3} strokeOpacity={active?.9:.35} strokeDasharray={e.status==='reported'?'':'5 4'} markerEnd="url(#world-arrow)"><title>{worldName(e.fromId)} → {worldName(e.toId)}: {e.label} · {e.evidenceKind}</title></path>;})}
    {visible.map(c=>{const {x,y}=point(c),[dx,dy]=offsets[c.id]??[0,-19],active=c.id===selected.id,num=CLUSTERS.indexOf(c)+1;return <a key={c.id} href={href(c.id)} aria-label={`${num}. ${c.label}`}><circle cx={x} cy={y} r="4" fill={active?'#F5C518':'#C3D7CC'}/><path d={`M${x} ${y} L${x+dx} ${y+dy}`} stroke="#B5C6B8" strokeWidth="1"/><circle cx={x+dx} cy={y+dy} r="12" fill={active?'#F5C518':'#29474B'} stroke={active?'#F5C518':'#A0BBB7'}/><text x={x+dx} y={y+dy+4} textAnchor="middle" fill={active?'#102A31':'white'} fontSize="11" fontWeight="700">{num}</text><title>{c.label}</title></a>;})}</svg></div>
    <div className="grid gap-1 px-3 pb-4 sm:grid-cols-2">{visible.map(c=><Link key={c.id} href={href(c.id)} aria-current={c.id===selected.id?'true':undefined} className={`flex gap-3 rounded-lg p-3 text-xs ${c.id===selected.id?'bg-white/15':'hover:bg-white/5'}`}><span className={`font-mono ${c.id===selected.id?'text-[#F5C518]':'text-white/50'}`}>{String(CLUSTERS.indexOf(c)+1).padStart(2,'0')}</span><span><strong className="block">{c.label.split(' · ')[0]}</strong><span className="mt-1 block text-[10px] text-[#A0BBB7]">{c.role}</span></span></Link>)}</div><p className="border-t border-white/10 px-5 py-3 text-[10px] leading-relaxed text-[#A0BBB7]">Solid: reported relationship · Dashed: announced relationship. Places anchor specific stories; pins do not represent size, national boundaries or facilities. <SourceLink href="https://www.naturalearthdata.com/about/terms-of-use/">Land: Natural Earth</SourceLink>.</p>
   </section>
   <article className="rounded-2xl border border-black/10 bg-white p-6" aria-live="polite"><p className="text-[10px] font-bold uppercase tracking-wider text-[#57776D]">{selected.country} · {selected.role}</p><h2 className="font-serif-display mt-3 text-2xl leading-tight">{selected.headline}</h2><div className="mt-5 space-y-4">{selected.facts.map((f,i)=><div key={i}><p className="text-xs leading-relaxed">{f.text}</p><p className="mt-2 text-[10px] text-ink-500">{f.observationPeriod??'Undated source'} · {f.status}</p><div className="mt-1 flex flex-wrap gap-2 text-[10px] text-ink-500">{f.sourceIds.map(id=><SourceLink key={id} href={worldSource(id).url}>{worldSource(id).title}</SourceLink>)}</div></div>)}</div><div className="mt-5 border-t border-black/10 pt-4"><h3 className="text-[10px] font-bold uppercase tracking-wider text-[#57776D]">Our reading</h3><p className="mt-2 text-sm leading-relaxed">{selected.editorialImplication}</p></div><p className="mt-4 rounded-lg bg-[#F2F5EE] p-4 text-sm leading-relaxed"><strong className="mb-2 block text-[10px] uppercase tracking-wider text-[#57776D]">Ask in the room</strong>{selected.buyerQuestion}</p><details className="mt-4 text-xs text-ink-500"><summary className="cursor-pointer font-semibold">What this does and does not establish</summary><p className="mt-2 leading-relaxed">{selected.limits}</p></details>{!!companies.length&&<div className="mt-5 flex flex-wrap gap-2">{companies.map(c=>c.studyId||c.ecosystemLinks.length?<Link key={c.id} href={companyDestination(c,'/earth')} className="rounded-md border border-black/10 px-3 py-2 text-xs font-semibold">{c.name} ↗</Link>:<span key={c.id} className="rounded-md bg-[#F2F5EE] px-3 py-2 text-xs font-semibold">{c.name}</span>)}</div>}
   </article>
  </div>
  <section className="mt-6 rounded-2xl border border-black/10 bg-white p-5 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#57776D]">Follow the relationship</p><h2 className="font-serif-display mt-2 text-2xl">{selected.label.split(' · ')[0]} connects to…</h2></div><p className="text-xs text-ink-500">Each arrow keeps its own evidence and meaning.</p></div><div className="mt-5 grid gap-3 md:grid-cols-2">{links.map(e=>{const other=e.fromId===selected.id?e.toId:e.fromId,place=CLUSTERS.find(c=>c.id===other);return <article key={e.id} className="rounded-xl border border-black/10 p-4"><p className="text-[10px] font-semibold uppercase tracking-wider text-[#57776D]">{e.evidenceKind} · {e.status}</p><p className="mt-2 text-xs font-semibold">{worldName(e.fromId)} → {worldName(e.toId)}</p><h3 className="mt-2 text-base font-semibold">{e.label}</h3>{e.meaning&&<p className="mt-2 text-xs leading-relaxed text-ink-500">{e.meaning}</p>}<div className="mt-3 flex flex-wrap gap-3 text-[11px]">{place&&<Link href={worldHref(other)} className="font-semibold underline">Explore {place.label.split(' · ')[0]} →</Link>}{e.sourceIds.map(id=><SourceLink key={id} href={worldSource(id).url}>{worldSource(id).title}</SourceLink>)}</div></article>;})}</div></section>
  <div className="mt-5 grid gap-3 md:grid-cols-3">{[{href:'/technology?view=history&point=euv-volume',title:'Why breakthroughs take decades',body:'Connect the long equipment programme to a usable process.'},{href:'/technology?view=scale',title:'Find the physical bottleneck',body:'Compare bandwidth, sequential waiting and orbital distance.'},{href:`/decisions?dilemma=${clusterLayers(selected.id).includes('delivery')?'si':'platform'}`,title:'Make a concrete buying decision',body:'Separate a plausible target from the next commitment it has earned.'}].map(l=><Link key={l.href} href={l.href} className="rounded-xl border border-black/10 p-5 hover:bg-white"><h3 className="text-sm font-semibold">{l.title} →</h3><p className="mt-2 text-xs leading-relaxed text-ink-500">{l.body}</p></Link>)}</div>
 </DestinationShell>;
}
