'use client';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { useState } from 'react';
import { TURNING_POINTS, EXPLORERS, FUTURES } from '@/lib/data/technology';
import { circularOrbit, networkBudget, formatDuration } from '@/lib/data/technology-math';
import { DestinationIntro, DestinationShell, SourceLink } from './destination-shell';

const tabs=[{id:'history',name:'Turning points'},{id:'scale',name:'How fast, really?'},{id:'future',name:'Possible futures'},{id:'explorers',name:'Explore the planet'}];
export function TechnologyView() {
 const params=useSearchParams(),view=tabs.find(t=>t.id===params.get('view'))?.id??'history';
 return <DestinationShell active="technology"><DestinationIntro kicker="Technology · past, physics & possibility" title="Slow foundations. Sudden breakthroughs." body="Understand what became possible, what made it practical, and what still gets in the way. A few useful ideas connect a computer’s memory to a satellite — and an invention to a business decision." />
 <nav aria-label="Technology topics" className="mb-6 flex flex-wrap gap-2 border-b border-black/10 pb-4">{tabs.map(t=><Link key={t.id} href={`/technology?view=${t.id}`} aria-current={view===t.id?'page':undefined} className={`rounded-lg px-4 py-2 text-xs font-semibold ${view===t.id?'bg-[#173C3C] text-white':'bg-white hover:bg-black/5'}`}>{t.name}</Link>)}</nav>
 {view==='history'&&<History selectedId={params.get('point')}/>} {view==='scale'&&<ScaleLab/>} {view==='future'&&<Future/>} {view==='explorers'&&<Explorers/>}
 </DestinationShell>;
}
function History({selectedId}:{selectedId:string|null}) {
 const point=TURNING_POINTS.find(p=>p.id===selectedId)??TURNING_POINTS[0]; const [choices,setChoices]=useState(30);
 const candidates=2**choices, seconds=candidates/1e9;
 return <><div className="grid gap-4 md:grid-cols-[260px_1fr]"><nav aria-label="Historical turning points" className="flex max-h-[640px] gap-2 overflow-auto rounded-xl border border-black/10 bg-white p-3 md:block md:space-y-1">{TURNING_POINTS.map(p=><Link key={p.id} href={`/technology?view=history&point=${p.id}`} aria-current={point.id===p.id?'true':undefined} className={`block min-w-[190px] rounded-lg p-3 ${point.id===p.id?'bg-[#E8EFE3]':'hover:bg-black/5'}`}><span className="font-mono text-[10px] text-[#54716B]">{p.date}</span><span className="mt-1 block text-xs font-semibold">{p.name}</span></Link>)}</nav><article className="rounded-xl bg-[#15363A] p-6 text-white sm:p-9" aria-live="polite"><p className="text-xs font-semibold text-[#D5DFAA]">{point.date} · Historical evidence</p><h2 className="font-serif-display mt-4 max-w-xl text-3xl sm:text-4xl">{point.title}</h2><div className="mt-8 grid gap-6 lg:grid-cols-2"><div><h3 className="text-[10px] font-bold uppercase tracking-wider text-[#D5DFAA]">What changed</h3><p className="mt-2 text-sm leading-relaxed text-white/85">{point.changed}</p></div><div><h3 className="text-[10px] font-bold uppercase tracking-wider text-[#D5DFAA]">What remained difficult</h3><p className="mt-2 text-sm leading-relaxed text-white/85">{point.remains}</p></div></div><div className="mt-8 border-t border-white/20 pt-5"><p className="text-[10px] font-bold uppercase tracking-wider text-[#D5DFAA]">Why it matters · our reading</p><p className="mt-2 max-w-2xl text-lg leading-relaxed">{point.lesson}</p></div><div className="mt-6 flex flex-wrap gap-4 text-[11px] text-white/70"><SourceLink href={point.url}>{point.source}</SourceLink>{point.extra&&<SourceLink href={point.extra.url}>{point.extra.label}</SourceLink>}</div></article></div>
 <section className="mt-8 grid gap-6 rounded-xl border border-black/10 bg-white p-6 md:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#54716B]">Try the distinction</p><h2 className="font-serif-display mt-2 text-2xl">Turing-complete does not mean practical.</h2><p className="mt-3 text-sm leading-relaxed text-ink-500">A Turing-complete system can express general computation, given sufficient time and memory. That says nothing by itself about speed, cost or intelligence. Real computers have finite resources.</p><p className="mt-3 text-sm leading-relaxed text-ink-500">In this exhaustive-search example, each extra yes/no choice doubles the search space. Better algorithms or structure can avoid exhaustive search; this is a model of growth, not every problem.</p></div><div className="rounded-xl bg-[#F5F5EC] p-5"><label className="text-sm font-semibold" htmlFor="choices">{choices} independent yes/no choices</label><input id="choices" className="mt-4 w-full accent-[#17423B]" type="range" min="10" max="60" value={choices} onChange={e=>setChoices(Number(e.target.value))}/><p className="mt-3 font-mono text-3xl">≈ {new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:2}).format(candidates)}</p><p className="mt-1 text-xs text-ink-500">candidate combinations · 2<sup>{choices}</sup></p><p className="mt-4 text-sm">At an assumed billion checks per second:<br/><strong>{formatDuration(seconds)}</strong></p><p className="mt-3 text-[10px] text-ink-500">Calculated illustration. Ten extra choices multiply the work by 1,024. Check cost and parallelism are held constant.</p></div></section>
 <Link href="/decisions" className="mt-6 block rounded-xl border border-black/10 p-5 text-sm font-semibold">The next gap: technically possible → useful in an organisation. Explore the adoption decision →</Link></>;
}
function Range({id,label,value,min,max,step=1,onChange,display}:{id:string;label:string;value:number;min:number;max:number;step?:number;onChange:(n:number)=>void;display:string}) {return <label htmlFor={id} className="block text-xs font-semibold"><span className="flex justify-between gap-2"><span>{label}</span><span className="font-mono font-normal">{display}</span></span><input id={id} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))} className="mt-3 w-full accent-[#17423B]"/></label>;}
function ScaleLab() {
 const [alt,setAlt]=useState(550),[distance,setDistance]=useState(10000),[size,setSize]=useState(10),[rate,setRate]=useState(1000),[trips,setTrips]=useState(10);
 const orbit=circularOrbit(alt),network=networkBudget(distance,size,rate,trips);
 return <div className="space-y-8"><section><h2 className="font-serif-display text-3xl">“Fast” needs a unit and a job.</h2><p className="mt-3 max-w-3xl text-sm leading-relaxed text-ink-500">Latency is how long you wait. Throughput is how much gets through. A clock measures cycles; memory bandwidth measures bytes. Comparing their biggest numbers tells you very little.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
 ['0.333 ns','A cycle at 3 GHz','Calculated example. One cycle is not one completed instruction.'],['100 ns','An assumed memory wait','Teaching example: roughly 300 cycles at 3 GHz. Actual latency depends on hardware and workload.'],['12 µs','1,500 bytes at 1 Gbit/s','Ideal serialisation only; excludes framing, queues and distance.'],['3.35 TB/s','H100 SXM memory bandwidth','Named NVIDIA specification. Bandwidth is not memory access latency.'],
 ].map(([v,l,b])=><article key={l} className="rounded-xl border border-black/10 bg-white p-5"><p className="font-mono text-2xl">{v}</p><h3 className="mt-3 text-xs font-semibold">{l}</h3><p className="mt-2 text-xs leading-relaxed text-ink-500">{b}</p></article>)}</div><p className="mt-3 flex flex-wrap gap-4 text-[10px] text-ink-500"><SourceLink href="https://www.intel.com/content/www/us/en/gaming/resources/cpu-clock-speed.html">Intel · clock frequency</SourceLink><SourceLink href="https://www.nvidia.com/en-us/data-center/h100/">NVIDIA · H100 specification</SourceLink></p></section>
 <section className="grid gap-6 rounded-2xl bg-[#16393A] p-6 text-white md:grid-cols-2 sm:p-8"><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#D5DFAA]">Distance & dependency lab</p><h2 className="font-serif-display mt-2 text-3xl">More bandwidth does not move light faster.</h2><p className="mt-3 text-sm leading-relaxed text-white/70">Change the useful data rate, then the additional request/response round trips before the payload is sent. A chatty workflow can spend more time waiting than transferring.</p><div className="mt-6 space-y-4"><Range id="distance" label="Actual fibre path, one way" value={distance} min={100} max={20000} step={100} onChange={setDistance} display={`${distance.toLocaleString()} km`}/><Range id="rate" label="Useful data rate" value={rate} min={10} max={10000} step={10} onChange={setRate} display={`${rate.toLocaleString()} Mbit/s`}/><Range id="payload" label="Total payload" value={size} min={1} max={1000} onChange={setSize} display={`${size} MB`}/><Range id="trips" label="Additional sequential round trips" value={trips} min={0} max={20} onChange={setTrips} display={String(trips)}/></div></div><div className="flex flex-col justify-center rounded-xl border border-white/20 p-5" aria-live="polite"><p className="text-xs text-[#D5DFAA]">Idealised elapsed time floor</p><p className="mt-2 font-mono text-5xl">{(network.totalMs/1000).toFixed(3)} <span className="text-xl">s</span></p><dl className="mt-6 space-y-4 text-sm"><div className="flex justify-between"><dt>Payload propagation, one way</dt><dd className="font-mono">{network.oneWayMs.toFixed(1)} ms</dd></div><div className="flex justify-between"><dt>Transfer payload</dt><dd className="font-mono">{network.transferMs.toFixed(1)} ms</dd></div><div className="flex justify-between"><dt>One propagation RTT</dt><dd className="font-mono">{network.rttMs.toFixed(1)} ms</dd></div><div className="flex justify-between border-t border-white/20 pt-4"><dt>{trips} sequential waits</dt><dd className="font-mono">{network.waitMs.toFixed(1)} ms</dd></div></dl><p className="mt-6 text-[11px] leading-relaxed text-white/60">Teaching model = payload / rate + one-way propagation + additional sequential RTTs. Decimal MB. No overlap, processing, congestion or protocol overhead. Fibre group index 1.4682 at 1550 nm; path length is not city-to-city distance.</p><p className="mt-4 text-[10px] text-white/60"><SourceLink href="https://www.corning.com/media/worldwide/coc/documents/Fiber/product-information-sheets/PI-1424-AEN.pdf">Corning · fibre group index</SourceLink></p></div></section>
 <section className="rounded-2xl border border-black/10 bg-white p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#54716B]">Orbit lab · calculated circular examples</p><h2 className="font-serif-display mt-2 text-3xl">Higher orbit. Slower satellite. Longer wait.</h2><p className="mt-3 max-w-2xl text-sm leading-relaxed text-ink-500">Orbital motion and radio propagation are different speeds. A geostationary satellite appears fixed from Earth while moving at about 3 km/s around Earth’s centre.</p></div><Link href="/technology?view=explorers" className="text-xs font-semibold underline underline-offset-4">Open the real explorers →</Link></div>
 <div className="mt-6 flex flex-wrap gap-2">{[{h:550,l:'LEO · 550 km'},{h:8000,l:'MEO · 8,000 km'},{h:35786,l:'GEO · 35,786 km'}].map(p=><button key={p.h} aria-pressed={alt===p.h} onClick={()=>setAlt(p.h)} className={`rounded-full px-4 py-2 text-xs font-semibold ${alt===p.h?'bg-[#173C3C] text-white':'bg-[#F0F3ED]'}`}>{p.l}</button>)}</div>
 <div className="mt-6 grid items-center gap-6 md:grid-cols-[1fr_1.4fr]"><div><svg viewBox="0 0 340 180" role="img" aria-label="Schematic radio relay: ground up to satellite and back to ground, twice for a round trip"><path d="M20 160 Q170 100 320 160" fill="none" stroke="#688C80" strokeWidth="2"/><path d="M95 142 L170 30 L245 142" fill="none" stroke="#B59622" strokeWidth="2" strokeDasharray="5 4"/><circle cx="170" cy="30" r="7" fill="#173C3C"/><circle cx="95" cy="142" r="5" fill="#173C3C"/><circle cx="245" cy="142" r="5" fill="#173C3C"/><text x="182" y="30" fill="#173C3C" fontSize="11">satellite</text><text x="170" y="170" textAnchor="middle" fill="#54716B" fontSize="10">Schematic only · not to scale</text></svg><Range id="altitude" label="Altitude above Earth" value={alt} min={160} max={35786} onChange={setAlt} display={`${alt.toLocaleString()} km`}/></div><div aria-live="polite" className="grid gap-3 sm:grid-cols-3">{[[orbit.speedKmS.toFixed(2),'km/s','Orbital speed'],[(orbit.periodMin/60).toFixed(2),'hours','Orbital period'],[orbit.propagationRttMs.toFixed(1),'ms','Relay RTT floor']].map(([v,u,l])=><div key={l} className="rounded-lg bg-[#F4F5EE] p-4"><p className="font-mono text-3xl">{v}</p><p className="mt-1 font-mono text-xs text-[#54716B]">{u}</p><p className="mt-3 text-xs font-semibold">{l}</p></div>)}</div></div>
 <details className="mt-5 border-t border-black/10 pt-4 text-xs leading-relaxed text-ink-500"><summary className="cursor-pointer font-semibold">What the numbers mean</summary><p className="mt-3">Circular orbit: v = √(μ/r), period = 2π√(r³/μ). Earth radius 6,371 km; μ = 398,600.4418 km³/s². Speed is relative to Earth’s centre. GEO also requires a circular, equatorial orbit with Earth’s rotation; altitude alone does not make an orbit geostationary.</p><p className="mt-2">Ideal relay round trip = 4 × altitude / light speed. It assumes minimum vertical radio legs, no other satellites and no terrestrial path. Real separated endpoints generally cannot attain that geometry; slant range, routing, processing and queues add time. The diagram shows a relay, not the minimum vertical geometry.</p><p className="mt-2">For context, Starlink reported 25.7 ms median peak-hour US latency in June 2025. That operator measurement is a dated service result, not a global promise and not the 550 km physics floor.</p><div className="mt-3 flex flex-wrap gap-4"><SourceLink href="https://www.esa.int/Enabling_Support/Space_Transportation/Types_of_orbits">ESA · orbit types</SourceLink><SourceLink href="https://ssd.jpl.nasa.gov/astro_par.html">JPL · physical parameters</SourceLink><SourceLink href="https://physics.nist.gov/cuu/Constants/Value/c.html">NIST · light speed</SourceLink><SourceLink href="https://starlink.com/gu/updates/network-update">Starlink · June 2025 measurement</SourceLink></div></details></section>
 <div className="rounded-xl border border-black/10 p-5 text-sm leading-relaxed"><strong>Rockets do not have one speed.</strong> They accelerate and stage. A broadcast velocity needs its mission time and reference frame. An illustrative airliner at 900 km/h is travelling at 0.25 km/s; our 550 km satellite is about 7.59 km/s relative to Earth’s centre. Wind changes aircraft ground speed. These examples are not live tracking.</div>
 </div>;
}
function Future() {return <><div className="mb-6 rounded-xl border border-[#D5DDBC] bg-[#EFF2E4] p-5"><h2 className="font-serif-display text-2xl">Several futures can be true at once.</h2><p className="mt-2 max-w-3xl text-sm leading-relaxed text-ink-500">These are Compound scenarios, not predicted dates or winners. Each has conditions, observable signals and a practical response. A breakthrough in one task can coexist with slow adoption elsewhere.</p></div><div className="grid gap-4 md:grid-cols-2">{FUTURES.map((f,i)=><article key={f.id} className="rounded-xl border border-black/10 bg-white p-6"><p className="font-mono text-xs text-[#54716B]">0{i+1} · Conditional pathway</p><h2 className="font-serif-display mt-3 text-2xl">{f.title}</h2><dl className="mt-5 space-y-4 text-sm leading-relaxed">{[['If',f.condition],['Watch',f.watch],['Response',f.response]].map(([l,b])=><div key={l}><dt className="text-[10px] font-bold uppercase tracking-wider text-[#54716B]">{l}</dt><dd className="mt-1">{b}</dd></div>)}</dl><details className="mt-5 border-t border-black/10 pt-4 text-xs"><summary className="cursor-pointer font-semibold">What would change this view?</summary><p className="mt-2 leading-relaxed text-ink-500">{f.change}</p></details><p className="mt-4 text-[10px] text-ink-500"><SourceLink href={f.url}>{f.source}</SourceLink></p></article>)}</div><Link href="/decisions" className="mt-6 block rounded-xl bg-[#173C3C] p-5 text-sm font-semibold text-white">Turn these possibilities into an investment sequence →</Link></>;}
function Explorers() {return <><h2 className="font-serif-display text-3xl">The planet is already instrumented.</h2><p className="mt-3 max-w-3xl text-sm leading-relaxed text-ink-500">Go straight to the people who operate the data. “Moving on screen” can mean an observation, an orbital model or a scheduled event. These links keep that distinction visible.</p><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{EXPLORERS.map(e=><article key={e.name} className="flex flex-col rounded-xl border border-black/10 bg-white p-5"><p className="text-[10px] font-semibold uppercase tracking-wider text-[#54716B]">{e.mode}</p><h3 className="font-serif-display mt-3 text-2xl"><SourceLink href={e.url}>{e.name}</SourceLink></h3><p className="mt-1 text-xs font-semibold text-ink-500">{e.provider}</p><p className="mt-4 flex-1 text-sm leading-relaxed text-ink-500">{e.body}</p><p className="mt-5 text-[10px] text-ink-500"><SourceLink href={e.method}>How to read the data</SourceLink></p></article>)}</div><details className="mt-6 rounded-xl border border-black/10 p-5 text-xs leading-relaxed"><summary className="cursor-pointer font-semibold">Go deeper: orbital data and network measurements</summary><div className="mt-4 grid gap-4 sm:grid-cols-2"><p><SourceLink href="https://celestrak.org/NORAD/elements/">CelesTrak orbital data</SourceLink><br/>Check the element epoch. Propagated position estimates become less reliable as data ages or spacecraft manoeuvre.</p><p><SourceLink href="https://atlas.ripe.net/docs/getting-started/what-is-ripe-atlas">RIPE Atlas</SourceLink><br/>Measurements from selected probes, targets and protocols. Results describe those paths and times, not one universal internet speed.</p></div></details><p className="mt-4 text-[10px] text-ink-500">Links and operator documentation checked 11 September 2026. External services control their coverage, access and freshness. Some features require an account or payment.</p></>;}
