export type Answers = Record<string,string>;
export type Question = {id:string; title:string; help?:string; options:{id:string;label:string}[]};
export type Decision = {id:string; name:string; title:string; intro:string; questions:Question[]; example:Answers; exampleText:string; sources:{label:string;url:string}[]};
const opts = (...values:string[]) => values.map(v=>{const [id,...label]=v.split('|');return {id,label:label.join('|')};});
export const DECISIONS:Decision[]=[
 {id:'ai',name:'AI authority',title:'How much should this AI be allowed to do?',intro:'Start with the task and the evidence. More autonomy is useful only when it improves the whole job.',example:{task:'fixed',consequence:'contained',access:'tested',proof:'demo',benefit:'unknown'},exampleText:'A facilities team wants to route routine, non-sensitive requests into known queues. The action boundary is tested; the only performance evidence is a successful demo.',sources:[{label:'Anthropic · workflows and agents · 2024',url:'https://www.anthropic.com/engineering/building-effective-agents'},{label:'ACSC · agentic AI guidance · May 2026',url:'https://www.cyber.gov.au/business-government/secure-design/artificial-intelligence/careful-adoption-of-agentic-ai-services'}],questions:[
 {id:'task',title:'What must it finish?',options:opts('draft|Find, explain or prepare work for a person','fixed|Perform a known sequence of changes','adaptive|Choose its next action from what it discovers')},
 {id:'consequence',title:'What happens if it acts incorrectly?',options:opts('contained|A limited, reversible, non-sensitive internal change','material|Money, permissions, external commitments or sensitive work','unknown|We have not mapped this')},
 {id:'access',title:'Can the system enforce its boundary?',help:'For drafts, consider permitted data. For actions, include logs, interruption and recovery.',options:opts('tested|The permitted boundary has been exercised','designed|A scoped design exists, but has not been exercised','broad|Broad access or no clear boundary')},
 {id:'proof',title:'What has it actually passed?',options:opts('representative|Representative work, exceptions and realistic failures','demo|The happy-path demo','failed|It failed a material acceptance case','unknown|We have not tested it')},
 {id:'benefit',title:'Does it improve the whole task?',help:'Include review, correction, operating cost and work shifted to other people.',options:opts('observed|Observed improvement after all that work','unknown|Not measured end to end','negative|Review, rework or cost removes the benefit')}]},
 {id:'platform',name:'Suite or specialist',title:'Consolidate the platform or keep the specialist?',intro:'Separate the architecture you want from the next change you can justify.',example:{reason:'handoffs',coreFit:'proven',specialistEdge:'optional',boundary:'unproven',transition:'untested'},exampleText:'An ANZ services business has duplicate employee records. The core passed its onboarding cases; the specialist has no proven outcome advantage. The migration has not been rehearsed.',sources:[{label:'GDS · integrate and adapt technology · 2025',url:'https://www.gov.uk/guidance/integrate-and-adapt-technology'},{label:'AWS · incremental replacement and coexistence',url:'https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/strangler-fig.html'}],questions:[
 {id:'reason',title:'What is forcing this decision?',options:opts('handoffs|Repeated handoffs, duplicate data or inconsistent controls','capability|A specialist requirement materially affects the work','renewal|Cost or an approaching renewal')},
 {id:'coreFit',title:'Has the core platform done the required work?',options:opts('proven|Representative workflow and important edge cases passed','gap|A material requirement is unmet','unknown|Only a feature list or demo')},
 {id:'specialistEdge',title:'Is the specialist advantage material?',options:opts('essential|A proven advantage on the required outcome','optional|Useful convenience, not material to the outcome','unknown|Not compared on the same work')},
 {id:'boundary',title:'Can we operate the system boundary?',help:'Consider record ownership, IDs, reconciliation, failed handoffs and export.',options:opts('owned|The boundary and its ownership are understood and tested','unproven|A design exists but has not been exercised','unclear|No accountable owner or reliable boundary')},
 {id:'transition',title:'What transition evidence exists?',options:opts('ready|Cutover and recovery rehearsed; whole change cost accepted','costOnly|Commercial estimate or licence saving only','untested|No representative rehearsal')}]},
 {id:'si',name:'Delivery partner',title:'How far can we commit to this delivery partner?',intro:'Assess one practice and one scope. Public cases explain where to investigate; your answers establish readiness for this engagement.',example:{service:'implementation',domain:'Payroll',localProof:'published',team:'practice',ownership:'partial'},exampleText:'A Workday payroll candidate has a relevant published Australian case and known practice leaders. The actual payroll lead and post-go-live ownership are still unresolved.',sources:[{label:'ServiceNow · partner strategy workbook · 2021',url:'https://www.servicenow.com/community/s/cgfwn76974/attachments/cgfwn76974/it-asset-management-kb/158/1/Develop%20Your%20ServiceNow%20Partner%20Strategy.pdf'},{label:'Workday · deployment testing · August 2026',url:'https://community-content.workday.com/en-us/public/learn/resources/customer-deployment/launch-flex-overview/Customer-Deployment-Testing.html'}],questions:[
 {id:'service',title:'What are you buying?',options:opts('implementation|A deployment or change outcome','ams|Ongoing operation and improvement','advisory|A decision or design','resourcing|Named people for work we manage')},
 {id:'domain',title:'Which capability must they prove?',options:[]},
 {id:'localProof',title:'What comparable local work have you verified?',help:'For resourcing, evaluate the proposed practitioner. A public case is not a buyer-verified reference.',options:opts('verified|Comparable ANZ work verified for this decision','published|Relevant public local evidence, not yet checked with the buyer','unknown|Global material, credentials or insufficient local evidence')},
 {id:'team',title:'Who is actually assigned?',options:opts('confirmed|Named, available people with relevant roles and allocation checked','practice|Credible practice leaders, but assignment is not confirmed','unknown|A delivery promise without an established team')},
 {id:'ownership',title:'Who owns the difficult work and the handover?',options:opts('agreed|Acceptance, delivery/support boundary and escalation are explicit','partial|Implementation scope exists; support or handover is unresolved','unknown|No shared operating responsibility')}]},
];
export type DecisionResult={id:string;title:string;because:string;proof:string;nextWhen:string;unresolved?:string[]};
const result=(id:string,title:string,because:string,proof:string,nextWhen:string):DecisionResult=>({id,title,because,proof,nextWhen});
export function evaluateDecision(id:string,a:Answers):DecisionResult {
 const definition=DECISIONS.find(d=>d.id===id);
 if(!definition||definition.questions.some(q=>!a[q.id]||(q.id!=='domain'&&!q.options.some(o=>o.id===a[q.id]))))return result('incomplete','Complete the decision context','Some answers are missing or invalid.','Choose an answer to each question; unknown is valid where offered.','The task and evidence are explicit enough to identify a next step.');
 if(id==='ai'){
  if(a.benefit==='negative'||a.proof==='failed')return result('redesign','Redesign the task first','The observed work has not earned a larger commitment. Controls cannot repair a failed acceptance case or negative benefit.','Change the task, interface or division of work; rerun the failed case and measure the whole task.','A revised task passes representative cases and produces an observed benefit.');
  if(a.task==='draft')return result('assist','Keep a person in the action loop',a.proof==='representative'&&a.benefit==='observed'?'This bounded assistant has task and benefit evidence.':'The output can remain reviewable while you establish its value.','Use permitted data, review the output and measure completed work including correction. The person commits the action.','Repeat benefit on the same task before adding scope. Write access requires a separate assessment.');
  if(a.consequence!=='contained'||a.access==='broad')return result('prepare','Prepare the change; let a person commit it','The consequence or action boundary is too broad for this lightweight autonomous-write path.','Produce a concrete proposed change. Establish permitted data, actions and a reviewable handoff before any production write.','A narrower, reversible task with an enforceable boundary can move to a shadow trial.');
  if(a.access!=='tested'||a.proof!=='representative'||a.benefit!=='observed')return result('shadow','Run it in shadow first','A contained action still needs tested boundaries, representative performance and a measured benefit.','Replay real work without committing actions. Include ambiguous cases, duplicated responses, retries, recovery and human handling effort.','The boundary is exercised, representative cases pass, and the complete task improves.');
  return a.task==='fixed'?result('workflow','Use a constrained workflow','The sequence is known, the boundary is tested and observed results support this task.','Trial the known sequence with code-owned action limits. Review completion, exceptions and recovery before expanding.','Repeated operation confirms the benefit. A new adaptive task needs fresh evidence.'):result('agent','Trial a bounded agent','The task needs adaptive steps and has passed the checks for this reversible action class.','Permit only the tested actions, with a named operator, stop condition, recovery route and exception handoff.','Sustained results on this defined workflow justify a separately reviewed expansion.');
 }
 if(id==='platform'){
  if(a.coreFit==='unknown'||a.specialistEdge==='unknown')return result('compare','Compare the same workflow first','A suite label and a specialist claim do not yet establish the better outcome.',`Have both options complete the same ${a.reason==='handoffs'?'cross-team handoff':a.reason==='renewal'?'observed workload and cost comparison':'specialist requirement'}, including edge cases and usable returned records.`,'A common acceptance exercise establishes core fit and whether the specialist advantage matters.');
  if(a.coreFit==='gap'&&a.specialistEdge!=='essential')return result('rescope','Re-scope the shortlist','The core misses a material requirement and this specialist has not proved the necessary advantage.','Define the unmet outcome; test another configuration or provider before funding migration.','At least one option proves the missing outcome.');
  if(a.specialistEdge==='essential')return result(a.boundary!=='owned'?'specialist-boundary':a.transition!=='ready'?'specialist-rehearse':'specialist-stage','Preserve the specialist capability','The outcome evidence supplies a concrete reason to retain it.',a.boundary!=='owned'?'Prove record ownership, failed handoffs, reconciliation and export across the boundary.':a.transition!=='ready'?'Rehearse the affected migration, recovery and service handover.':'Stage the specialist alongside the core with explicit record and support ownership.','The boundary and transition are exercised; ongoing benefit still exceeds the extra operating work.');
  if(a.reason==='renewal'&&a.transition!=='ready')return result('economics','Test the renewal economics','Licence savings alone have not established the case for change.','Compare renewal with migration, dual-running, integration, operations and the capability relinquished. A short bridge may preserve the option.','Accepted whole-change economics and a rehearsed transition justify one consolidation slice.');
  return result(a.transition==='ready'?'consolidate':'rehearse',a.transition==='ready'?'Consolidate one workflow':'Rehearse the consolidation first','The core has proved the required work and the specialist advantage is optional.',a.transition==='ready'?'Move the smallest useful slice. Reconcile the records before retiring its old duplicate work.':`Rehearse one end-to-end path, data correction and recovery.${a.boundary!=='owned'?' Establish a workable cutover boundary; do not assume effortless coexistence.':''}`,'The slice works through exceptions and has a named operating owner before further migration.');
 }
 const scope=`${a.domain || 'selected domain'} ${a.service==='ams'?'support':a.service==='resourcing'?'resourcing':a.service==='advisory'?'advisory':'implementation'}`;
 const proof=a.service==='ams'?`Walk a realistic ${scope} incident from detection through correction, escalation and resolution, plus a routine release.`:a.service==='advisory'?`Produce a usable ${scope} decision on one real problem, including constraints and rejected alternatives.`:a.service==='resourcing'?`Have the named assigned person complete a relevant ${scope} task; confirm availability and handoff expectations.`:`Have the proposed team walk an end-to-end ${scope} process, data correction and cutover exception.${a.domain==='Payroll'?' Include parallel-run reconciliation.':''}`;
 let r:DecisionResult;
 if(a.localProof==='unknown')r=result('fit','Verify delivery fit',`Relevant local ${scope} has not yet been established.`,`Ask what the firm or proposed practitioner actually owned in a comparable engagement. ${proof}`,'The work is relevant to this scope and you can validate it through a reference or equivalent evidence.');
 else if(a.localProof==='published')r=result('reference','Validate the comparable work','Published local evidence is a starting point; it has not been verified for your decision.',`Establish what was delivered, by whom, when and where. ${proof}`,'Buyer-held evidence confirms comparable work; then validate the actual assignment.');
 else if(a.team!=='confirmed')r=result('team','Validate and reserve the actual team','The relevant work is verified, but practice reputation does not reserve delivery capacity.','Meet the proposed people against the scope. Confirm their allocation, start window and substitution arrangements.','Named people with relevant experience are available and assigned.');
 else if(a.ownership!=='agreed')r=result('boundary','Set the operating boundary','Delivery evidence and the assigned team are established; acceptance or ongoing responsibility is unresolved.',proof,'Delivery, customer and support responsibilities survive the handoff and exception exercise.');
 else r=result('phase','Commission the first accountable phase','Comparable local work, an assigned team and the operating boundary are established.','Commission one meaningful outcome with explicit acceptance, responsibilities and a review point. This is a phase commitment, not a guarantee.',`Actual performance on ${scope} earns the next scope increment.`);
 r.unresolved=[a.localProof!=='verified'?'Comparable work needs buyer verification':'',a.team!=='confirmed'?'Actual team not yet confirmed':'',a.ownership!=='agreed'?'Operating boundary unresolved':''].filter(Boolean);
 return r;
}
export function readAnswers(decision:Decision,params:URLSearchParams,domains:string[]=[]):Answers {
 return Object.fromEntries(decision.questions.flatMap(q=>{const value=params.get(q.id);const valid=q.id==='domain'?domains:q.options.map(o=>o.id);return value&&valid.includes(value)?[[q.id,value]]:[];}));
}
